### ISSUE TITLE
Problems with adding math formula in README.md

### ISSUE THREAD

**Issue by SarahQiong** [STAT545-UBC/Discussion#102]
I want to insert some math formulas in README file. I just type something like this $Y=F(X)$, Just as what I did in latex. When I click *Preview HTML*, it looks good, the math formulas are right. However, when I open the README file in browser, those formulas show as the code I typed in instead of what they should be. How can I show those formulas correctly?

**Comment by jennybc** [comment]
AFAIK formulas will only look good in true rendered HTML. It's just not compatible with Markdown, which is super-simple by design.

**Comment by oganm** [comment]
There does seem to be a hacky way to do so through an external service. With some work it should be possible to write an R wrapper for this that outputs the required image link given a latex formula.

http://stackoverflow.com/questions/11256433/how-to-show-math-equations-in-general-githubs-markdownnot-githubs-blog

**Comment by jennybc** [comment]
There's also this nice explanation from @mikelove:

[How to use latex math in Rmd to display properly on GitHub Pages](https://mikelove.wordpress.com/2015/07/01/how-to-use-latex-math-in-rmd-to-display-properly-on-github-pages/)

but I suspect his solution also only applies to rendered HTML. In his case, to HTML rendered by Jekyll, not RStudio. So not totally relevant to @SarahQiong's question but good to put on the radar here.

**Comment by daattali** [comment]
Just wanted to add an upvote for what @oganm said - I personally used that solution in the past. Here's an example (these comment boxes actually render markdown the same way as GitHub will render your README.md, so if something works here it means you can also put it in your README.md) 

![equation](http://latex.codecogs.com/gif.latex?Concentration%3D%5Cfrac%7BTotalTemplate%7D%7BTotalVolume%7D)  

The above was created with this code:

```
![equation](http://latex.codecogs.com/gif.latex?Concentration%3D%5Cfrac%7BTotalTemplate%7D%7BTotalVolume%7D)  
```

**Comment by SarahQiong** [comment]
@daattali I just try to add on that way, it works. It's just like using other website to form a picture and then using markdown syntax for adding a picture.

**Comment by daattali** [comment]
@SarahQiong yes that's exactly what's happening, you got it. It's not exactly the perfect solution but it's a fair workaround

**Comment by oganm** [comment]
By the way the website I just sent doesn't seem to work with github but from @daattali's site you can define a function like

```
latexImg = function(latex){
    
    link = paste0('http://latex.codecogs.com/gif.latex?',
           gsub('\\=','%3D',URLencode(latex)))
    
    link = gsub("(%..)","\\U\\1",link,perl=TRUE)
    return(paste0('![](',link,')'))
}
```

in any inline location you can do `` `r latexImg('a = \\frac{b}{c}')` `` to place the image you want
