### ISSUE TITLE
Software Carpentry + Data Carpentry Instructor & Helper Retreat

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#103]
http://swcarpentry.github.io/instructor-retreat-2015/
November 14, 2015

UBC will be one of the hosts sites for this. By November, many of you might want to consider being Software or Data Carpentry helpers and eventually going through instructor training. If that sounds at all appealing, consider attending this day-long event.

Much more detail at the link above.

**Comment by yosukesugishita** [comment]
What are you planning to do on the day of the retreat?  It wasn't very clear to me from the link.

**Comment by jennybc** [comment]
The info available there is all I have -- I am not an organizer.

Or do you mean what am I planning to present personally?
