### ISSUE TITLE
Peer review for hw01 is open

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#104]
You have all been added to the `2015_students` team, which has pull (or "read") access to each student's private repository. I suspect that will trigger a notification but not an invitation. When you view [our Organization](https://github.com/STAT545-UBC), you should see ALOT of repositories now, instead of just the public ones and your own.

You have been assigned 2 peer reviews. I would expect each of those issues to trigger a notification. Please do as the issue says!

Let me know if your experience does NOT match with what I predict above.

**Comment by AdrianLJones** [comment]
Looking under the notifications button I don't see anything about peer review.  After this issue, the  only notification I see is about the Bioinfomatics scholarship

I do see 4 pages worth of private repos under the stat 545 section.

Adrian

**Comment by samhinshaw** [comment]
@AdrianLJones To find your peer review assignments, check "Issues" at the top of the page, then the "Assigned" tab.

**Comment by AdrianLJones** [comment]
I have some things under the mentioned and created tabs but nothing under assigned.  It says "no results match your search"

**Comment by jennybc** [comment]
@AdrianLJones Hmmm .... I don't seem to have assigned you any issues, nor was anyone assigned to review your work. I will figure out what went wrong.....

**Comment by jennybc** [comment]
@AdrianLJones OK I see the problem. You are not the only one affected but are the only to complain. :smile: There may be enough of you to do another wave of peer review assignments within the group. I'll figure something out.

**Comment by jennybc** [comment]
@AdrianLJones Dude, are you even registered in this class? You are not showing up in the official class list yet, which is the root cause of this problem. Are there other people in @AdrianLJones's situation? I assume this: you are registered in your mind but some paperwork (?) is still working its way throught the official system. I'd like to know who else affected before I deal with it.

**Comment by namanpaul** [comment]
@jennybc I have been assigned to review the homework of just **ONE** peer. 
Reading through the comments, I think, I have to wait a bit, to do another round of peer review for hw01 :smile:

**Comment by AdrianLJones** [comment]
@jennybc  I thought I was registered, but currently on the ssc it looks like I'm not.  I'll see what I can do to sort out the problem.  I certainly would like to be registered and be a part of the course!

**Comment by AdrianLJones** [comment]
@jennybc Okay, I registered for sure now according to the ssc, hopefully that sorts out the problem.

**Comment by RashedHUBC** [comment]
@jennybc It seems my homework 01 is assigned to two persons. I haven't got anyone's homework to review. Should I review someone's homework?

**Comment by jennybc** [comment]
@RashedHUBC Yes I'll assign you something. It seems two people have dropped (so I deleted their teams and repos) and @AdrianLJones has now officially registered. I'm working this out. You'll get a notification.

**Comment by jennybc** [comment]
@AdrianLJones you have been assigned the work of 2 peers to review. Two peers have been assigned to review your work.

@namanpaul You've been given another peer review to do.

@RashedHUBC You've been given two peer reviews to do.

I think we're done here?

**Comment by namanpaul** [comment]
Thank you @jennybc

**Comment by RashedHUBC** [comment]
Thank you @jennybc . As a peer reviewer I should see the homework done and then make comments in the box below. Am I right? Also there is a rubric for marking. Where should I submit the marks? I am not clear about "Does it take you directly to their README?". According to submission guideline we should copy the last commit and submit that one along tagging you and peer reviewers. Is it okay? Can you clarify this please?

**Comment by namanpaul** [comment]
@RashedHUBC 
For this particular homework, we need to mark according to this [rubric.](http://stat545-ubc.github.io/hw01_edit-README.html#rubric)
We are required to submit our comments, alongwith the grade,
 i.e. whether a check +, check or check -  *depends on the rubric*

**Comment by jennybc** [comment]
@RashedHUBC Yes check out their work. Make comments in the issue thread (yes "in the box below"). You don't need to do anything else. You don't even have to say "check minus, check, check plus". The TAs and I will do that. I point you towards the rubric just so you know what to look for. This will make more sense when the assignment has more substance.

"Does it take you directly to their README?" means this: is there a link you can click on and go directly to the thing you're supposed to read? In this case, their README.

**Comment by jennybc** [comment]
@wang114 was left out of peer review. Figure out why.
