### ISSUE TITLE
"Keep markdown source file" as a global option

### ISSUE THREAD

**Issue by MingWan10** [STAT545-UBC/Discussion#106]
Hi all, for each R markdown files we can toggle the option to "keep markdown source file" from "Edit R markdown document options for the current file", but this option is not checked by default if you create a new R markdown file. Is there a way to set "keep markdown source file" as a global option for every new Rmd file I created? Thanks!

**Comment by oganm** [comment]
This seems to be a common issue. For no apparent reason, there doesn't seem to be any way to set the default output style to md files. To consistently get markdown outputs you can render your files by using `rmarkdown::render('insertYourFileName.Rmd','md_document')` or just by setting the default output to 
```
output: md_document
```

all of which needs to be done manually.

**Comment by ksamuk** [comment]
If you want to get fancy, you can make your own Rstudio template:

**Comment by jennybc** [comment]
Yes I just got confirmation from RStudio that, for now, the best way to achieve this is to create your own custom document template.

**Comment by MingWan10** [comment]
@ksamuk I just created a new markdown template and it did exactly as I wanted, although I had to create all the template files manually and move it into the rmarkdown templates folder, which is quite a hassle.
