### ISSUE TITLE
Relationship between RMarkdown and knitr

### ISSUE THREAD

**Issue by mstrimas** [STAT545-UBC/Discussion#107]
Does anyone understand the relationship between these packages? When going from an `.rmd` file to an  html file, what specifically is each package doing?

**Comment by jennybc** [comment]
`knitr` processes first and specifically processes R chunks. Typically this means each R chunk will be run and -- it its place -- formatted code and output will be inserted into ....

`knitr`'s output, which is Markdown. So `knitr` is responsible for doing this: `foo.Rmd` --> `foo.md`.

Pandoc takes `foo.md` and produces the requested output format, such as html. Pandoc is responsible for doing this: `foo.md` --> `foo.html` or `foo.docx` or what have you.

The rmarkdown package -- specifically the `render()` function -- coordinates those moving parts. This is a very simplified account, but hopefully useful to you.
