### ISSUE TITLE
hw02 - full gapminder or excerpt

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#108]
The homework page (https://stat545-ubc.github.io/hw02_explore-gapminder-use-rmarkdown.html) contains conflicting information.

The update suggests that the homework will be switched over to use to the gapminder package. Later on, it says to use the excerpt in the form of a txt file

Which are we meant to use for the homework?

I believe results will be different depending on what is used. For example, I tried using read.table(url) but it complains about number of elements. Presumably this would not be a problem with the gapminder package

**Comment by RashedHUBC** [comment]
But I think @jennybc wants from us to work with the Gapminder excerpt data, not the data in the "gapminder" package. Using read.table directly is problematic and she wants how we overcome this problem (changing default settings of read.table). Thanks.

**Comment by Haycen** [comment]
I've got the same error with the `gapminder` package, so I suppose they both provide the same data table but from different sources.
As @RashedHUBC mentionned, you probably have to figure out how to overcome this error by changing some default arguments in the `read.table()` function.
Have a look to `read.table()` [documentation](http://www.rdocumentation.org/packages/utils/functions/read.table) and find out what's the difference between `read.table()` and `read.delim()`.

**Comment by jennybc** [comment]
Work with the main data.frame provided by the `gapminder` package. I'll edit the homework to make this more clear shortly. Thanks for the question.

**Comment by jennybc** [comment]
They are the same data, so any work you've done already will be useful in your HW submission BTW.

**Comment by wang114** [comment]
If we use the gapminder package, then we don't need to read in data?

**Comment by jennybc** [comment]
Correct @wang114. You can do `library(gapminder)` just as we did in class the other day. Then do basic exploration and make some figures.
