### ISSUE TITLE
YAML in .R and .Rmd

### ISSUE THREAD

**Issue by min110** [STAT545-UBC/Discussion#109]
This is an extension question from today's class:
It is a couple of lovely **"---"** that distinguish Yaml from other parts of the code in R Markdown; meanwhile it might be painful to type **#'** if I want Yaml in normal R script . Are there more fancy ways to deal with ? @jennybc 
Thanks!

**Comment by daattali** [comment]
I'm not sure I completely understand the question, but in general YAML only goes in rmarkdown, and not in regular R scripts. Also note that the YAML has to be the first thing in the document.  I don't think I've answered your question though

**Comment by jennybc** [comment]
We're talking about the easiest ways to get YAML front matter [like so](https://gist.github.com/jennybc/402761e30b9be8023af9) for plain R scripts. Studio says the best plan for now is to use the [snippet mechanism](https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets).

**Comment by jennybc** [comment]
Putting the YAML for `.R` inline to make this more clear:

```
#' ---
#' title: "Something fascinating"
#' author: "Jenny Bryan"
#' date: "10 September, 2014"
#' output:
#'   html_document:
#'     keep_md: TRUE
#' ---
```
