### ISSUE TITLE
Purposly including faulty code in a markdown file

### ISSUE THREAD

**Issue by AdrianLJones** [STAT545-UBC/Discussion#110]
In the process of working through homework 2 I encountered some errors in a code chunk that I'd like to talk about.  But of course when I try to knit the mardown document it throws the error and so the knitting fails.  Is the only way to include the code that produces the error with the `inline text` code formatting?

**Comment by ksamuk** [comment]
Probably looking for `eval` e.g. {r, eval=FALSE} (i.e. don't evaluate this chunk)

**Comment by oganm** [comment]
If you want to execute errors and show the message as well, you can try `{r, error=T}`.

**Comment by jennybc** [comment]
This is in the troubleshooting section here:

http://stat545-ubc.github.io/block007_first-use-rmarkdown.html#troubleshooting

Sidebar: I also recommend full use of `TRUE` and `FALSE` instead of `T` and `F`, regardless of context.
