### ISSUE TITLE
what if our assignment is not marked?

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#113]
What happens if one of our peers didn't mark our homework?

**Comment by BernhardKonrad** [comment]
It won't have any negative consequences for you, of course. A TA is going over your work and the peer review to assign your (and your reviewer's) grade.

**Comment by jennybc** [comment]
Yes what @BernhardKonrad. It is a bummer, of course, because it's good to get eyeballs and feedback on your work. But this is unlikely to happen to you again. At least it was just the first assignment.

**Comment by wang114** [comment]
Will we know our assignment grades?

**Comment by jennybc** [comment]
Yes once marking is done (which will be several days), we send you email.
