### ISSUE TITLE
use our own data for homework 2

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#115]
@jennybc how do we get permission from you to use other dataset for homework2? I want to use a dataset I collected for my psychology research to do homework2. The dataset contains participants' responses on personality questionnaire scales. Is that ok?

**Comment by jennybc** [comment]
Can you open an issue in your own repo and tag me?

  * Do you have necessary ethics approval to expose this data and analzye within the course organization?
  * Is it rectangular?
  * How many variables? Are there __multiple__ quantitative __and__ categorical variables?
  * How many observations?

I need a clear YES on first 3 and # obs should be ~1,000 or ~10,000, not ~100 or ~100,000.

**Comment by cathyxijuan** [comment]
@jennybc Thank you very much for your reply! 
I need to think about it more. For some items, I do have more than 1000 data points but not all items because there are different conditions. I will get back to you about this!
