### ISSUE TITLE
issue related to assignment2(sorry that I can't think out a title for it)

### ISSUE THREAD

**Issue by SarahQiong** [STAT545-UBC/Discussion#116]
I intended to randomly pick a country in the dataset and drew a picture of gdpPercap to see the change during 12 years. But the problem I met: each time you click knit HTML, the country picked would be different from the former one which means the picture looks different. But you need to upload the picture in order to see the it on github. Are there any ways that I can solve the problem without abandoning randomness?

**Comment by jennybc** [comment]
Use `set.seed()`. Read the help and let me know if you need more guidance.

**Comment by SarahQiong** [comment]
@jennybc thank you Jenny

**Comment by jennybc** [comment]
Proposed title: how to do something random in a repeatable way? :smile:
