### ISSUE TITLE
read.delim vs. read.table in hw 2

### ISSUE THREAD

**Issue by JoeyBernhardt** [STAT545-UBC/Discussion#117]
Hi guys,

When I started the homework the other day, I swear there was an exercise on how to import the gapminder data using read.delim and read.table...and you had to modify the arguments of read.table to import the data in the same was read.delim.  And now that I go back to continue working on the homework, I can't find that exercise. 

Has anyone else encountered this issue?

Thanks!

**Comment by JoeyBernhardt** [comment]
Sorry, made a typo! meant to say 'import the data in the same way as read.delim'

**Comment by ksamuk** [comment]
Hmm! The exercise was updated yesterday to use Jenny's `gapminder` package, so that part was removed. @jennybc, can you confirm this is no longer part of the homework?

**Comment by jennybc** [comment]
Correct. Feel free to use data.frame from gapminder package. You can bank what you learned about importing delimited files and use it in a subsequent homework.

**Comment by JoeyBernhardt** [comment]
ok great, thanks for the quick replies!
J.

**Comment by jennybc** [comment]
And, for any one else, if you went ahead and did this from data imported from delimited file, that's fine. Don't redo it. It's the same data.
