### ISSUE TITLE
difference between class and mode

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#118]
What is the difference between the class and mode of an R object? Why is a data.frame's mode is list?

**Comment by ksamuk** [comment]
I think this is the best explanation of that distinction (emphasis mine):

https://stat.ethz.ch/pipermail/r-help/2008-April/158990.html

>
**'mode' is a mutually exclusive classification of objects according to
their basic structure.**  The 'atomic' modes are numeric, complex,
charcter and logical.  Recursive objects have modes such as 'list' or
'function' or a few others.  An object has one and only one mode.
>
**'class' is a property assigned to an object that determines how generic
functions operate with it.**  It is not a mutually exclusive
classification.  If an object has no specific class assigned to it, such
as a simple numeric vector, it's class is usually the same as its mode,
by convention.
>
Changing the mode of an object is often called 'coercion'.  The mode of
an object can change without necessarily changing the class.  e.g.

also the last sentence:
>
In practice, mode is not used very much, other than to define a class
implicitly when no explicit class has been assigned. 

Re: data.frame's mode being 'list', data.frames *are* lists, but a special case. For more explanation on that see here: http://stackoverflow.com/questions/15901224/what-is-difference-between-dataframe-and-list-in-r

**Comment by daattali** [comment]
PS. @cathyxijuan don't worry if you don't fully understand this yet, I believe we will learn about mode and class more in depth is cm008: basic flavours of R objects ([syllabus](http://stat545-ubc.github.io/syllabus.html))

**Comment by jennybc** [comment]
Yes, we haven't talked about this. I threw those functions out there in the general sense of "get to know what your objects are". And read the docs for `class()` and `mode()`, which will go some way towards explanation.

**Comment by cathyxijuan** [comment]
@jennybc @daattali  Thank you very much for you clarification!! I was a bit confused because homework 2 asked about them and I don't remember we went over the distinction in class.
