### ISSUE TITLE
question about .Rproj.user files

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#122]
Hi, 

I am curious about what I should do with .Rproj.user files. We may have talked about this issue in class when we went over various files created by R and R studio but I don't remember what had been said about the .Rproj.user files. Sorry if we have already went over this. 
Should I keep the .Rproj.user files? Another problem I am having is that these files are hidden so I can't see in the folder on my laptop but it got pushed to github somehow.. How can I make the files visible to me? I am using Mac

**Comment by dchiu911** [comment]
Hi @cathyxijuan you will learn eventually (I think nearing the end of the course) some of the uses of having an `.Rproj` file. You can add this to your `.gitignore`, but not sure if this was mentioned in class as well!

**Comment by jennybc** [comment]
When you create a new RStudio Project that is also a Git repo, you will notice that the `.gitignore` file holds this by default:

```
.Rproj.user
.Rhistory
.RData
```

Go ahead ... try it! Learning by doing!

This means that these files will not be part of your Git repository. You will not be prompted to stage or commit them, etc. I think it's a good way to go.

You can always edit your `.gitignore` at any time, so if these lines are not in your `.gitignore`, feel free to add them.

How to delete that `.Rproj.user` file you have commited and pushed without actually deleting it locally? Do this in the shell to stop tracking it but NOT delete the file itself.

```
git rm --cached <filename goes here>
```

Then push. And make sure you've added that stuff to `.gitignore` to keep it from happening again.

On a Mac, if you want dotfiles to be visible in the Finder (I certainly do): do this in the shell:

```
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder
```

That is one of the first things I do on a new Mac.


@dchiu911 Note this is different from the `.Rproj` file, which you often do want to keep in the repo.

**Comment by dchiu911** [comment]
Ah yes, missed that

**Comment by cathyxijuan** [comment]
@jennybc  Once again, thank you very much for your help! I got it solved!
