### ISSUE TITLE
markdown workflow on large projects

### ISSUE THREAD

**Issue by AdrianLJones** [STAT545-UBC/Discussion#124]
So I just commited my homework 2.  Looking at the [markdown file](https://github.com/STAT545-UBC/adrian_jones/blob/master/Homework/Homework2/Homework02.Rmd) it is long and has a bunch of figures that are only passingly useful, and it is quite a pain to go and change the formatting if I decide that I want to use the header structure a different way, so the formatting leaves much to be desired for clarity's sake.  I imagine that as I work on larger projects this will only get more problematic.

At what point do people start splitting their markdowns into sections like "data cleaning" "initial visualization" "final plots" etc.  Or is there another way to deal with this issue?

Thanks

Adrian

**Comment by dchiu911** [comment]
Hi @AdrianLJones it really depends on when you feel like the report is getting too long. One scenario where you might want to split up your reports into multiple markdown files is if you only want to keep re-running a certain section of code, while keeping other sections untouched. 

You can look into the R Markdown chunk option `child`, which essentially lets a "parent" R Markdown call one or more "children" R markdown files.

Usage: `{r, child="path/to/file/child_1.Rmd}` for the chunk header.

I don't anticipate there being future projects being too large however.
