### ISSUE TITLE
How to share private github repository

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#125]
Hi, 

I am wondering how I can share my homework with friends who are not in the class. My friend told me that he can't open my homework file but I really want to show people my graphs. LOL

**Comment by jennybc** [comment]
This is not very easy to do with our setup. Do you have any private GitHub repos in your own name yet? Then you could fork your STAT545/firstname_lastname repo to YOU/firstname_lastname and have it track your coursework. Then you could grant these friends read access to YOU/firstname_lastname.

I suppose you could also add a private Bitbucket remote to your course repo and push there as well as GitHub. Then, again, add these friends as collaborators with read access to the Bitbucket repo.

**Comment by cathyxijuan** [comment]
@jennybc  Thank you again! You know what. I just figure out that I can just knit my Rmarkdown into pdf and send to my friend. LOL Rmarkdown is AWESOME. Thanks for teaching me this!

**Comment by jennybc** [comment]
:smiley:
