### ISSUE TITLE
Are captions an archaic vestige of the print-based publication model?

### ISSUE THREAD

**Issue by npjc** [STAT545-UBC/Discussion#127]
There was good discussion in class today questioning the use of captions in your drafts.

The vast majority of periodicals require figure captions and the readers of periodicals expect them.

Continue this here. Aim your brain power at the following questions:

1. But what is the _purpose_ of captions?
2. Are captions really the _best_ way to achieve that purpose?
3. Given your thoughts in 1,2 how would you describe the state of scientific communication?

If you're interested in a recent attempt at modernizing this: [elife lens](http://lens.elifesciences.org/#state=main;0.searchQuery=%7B%22searchStr%22%3A%22%22%2C%22filters%22%3A%7B%7D%7D) Do you think this is better, worse, what would you change?

**Comment by jennybc** [comment]
I love how the figs pop up next to the text in elife!

**Comment by cathyxijuan** [comment]
I just like captions. I can use an analogy for this. For research article, we have abstract to summarize what our paper is about but we still make up a title for the paper. So what is the purpose of a title there?  I think the purpose (at least one of the purposes) is to give you an even succinct summary of the article.

**Comment by npjc** [comment]
So the purpose of captions are there to summarise / describe the contents of a figure in a succinct manner? I buy it! I don't know if I think it's the best solution given the tools we have available. Also, browsing through this week's Science Mag doesn't doesn't convince me this is actually how captions are used in practice.

**Comment by cathyxijuan** [comment]
How are captions used in figures in Science magazines then?

**Comment by npjc** [comment]
Great question! If only I could get actual data on this that would be awesome.

I was quite vague before my bad; let me elaborate: I suppose I'm thinking captions often provide detailed descriptions of a figure panel as oppose to a guided flow through to the main observation in the figure. I'm quite used to reading papers and so I've learned to parse this stuff pretty efficiently but I always wonder if there's a better way. (I'm not against them, but I am interested in evaluating alternatives!)

For an example of what I consider to be a guided flow in a caption that I really like see the caption to this figure on wiki: [Geometric visualisation of the variance of the example distribution](https://en.wikipedia.org/wiki/Standard_deviation#/media/File:Variance_visualisation.svg)

**Comment by cathyxijuan** [comment]
But a lot of times, the readers just want to skim through the paper or just look at the graph. Then caption will tell them right away what they are looking at. It is like literature research on google scholar or something. If the articles don't have titles, it will be very hard for us to find relevant papers quickly.

**Comment by ksamuk** [comment]
My purely stylistic opinion: I would say captions are necessary if you are preparing a document for formal publication. However, this is often not what we are doing in In terms of the R/Rmarkdown/Github workflow (although people do prep full manuscripts using this method!). To me, one of the main aims of the R/Rmarkdown document model is to narrate an analysis in prose while exposing the code used to generate everything, including the figures. In my opinion, if done correctly, this makes captions redundant. Totally up to the individual author and dependant on the target audience/usage of the document.

**Comment by cathyxijuan** [comment]
I feel it is depends on who are you target audience. If your target audience is just your TA, who has the patience to read over your Rmarkdown carefully, then of course you may not need captions. In that case, you may not even need axis labels. But if you want to share your Rmardown with other people online, do you expect them to read over your Rmarkdown carefully? With today's information overload on the Internet, I just can't make that assumption.

**Comment by npjc** [comment]
I think you've hit the nail on the head! The tl;dr is really the bigger problem here. Now fixing that is a whole other issue!
