### ISSUE TITLE
Counting in `dplyr`

### ISSUE THREAD

**Issue by npjc** [STAT545-UBC/Discussion#128]
In class today we counted a lot! As Jenny says this is an extremely common thing to do! So `dplyr` provides shorthand functions to do this. For those who dislike typing : what does `count()` do? check `?count`

Longest
```r
gtbl %>%
  group_by(continent) %>%
  summarize(n = n())
```
Shorter
```r
gtbl %>%
  group_by(continent) %>%
  tally()
```
Shorter still
```r
gtbl %>%
  count(continent)
```

**Comment by jennybc** [comment]
I got some really great answers to a counting question on Twitter recently:

https://gist.github.com/jennybc/04b71bfaaf0f88d9d2eb

Specifically about cross-tabulation of two factors and very flexible ways to do it and reshape it.
