### ISSUE TITLE
not knitting anymore... supposedly missing object

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#129]
@jennybc , @daattali, @ksamuk (by the way, should I always include all the TAs or just Jenny),
I work on my homework and it worked for quite some time (including the repeated `knitting`) till it just stopped, giving me the error message:
![errormessage_knitting](https://cloud.githubusercontent.com/assets/11307637/10234212/f2366f08-6847-11e5-991a-e434236edd12.png)

I will give my RMarkdown code that I want to have knit in my next post

**Comment by ahippman** [comment]
---
title: "HW03 dplyr and ggplot - friends forever"
author: "Anna A. Hippmann"
date: "October 1, 2015"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


 
###Libraries used
```{r libraries, eval=FALSE, include=TRUE}
library(gapminder)
library(ggplot2)
library(dplyr)
library(rmarkdown)
```
***
### Mission

Pick at least three of the tasks suggested and attack each with a table and figure.

* Get the maximum and minimum of GDP per capita for all continents
* How is life expectancy changing over time on different continents?
* Report the absolute and/or relative abundance of countries with low life expectancy over time by continent
* Maybe one more of own creation? we will see

### 1) Get the maximum and minimum of GDP per capita for all continents

```{r access_gapminder, echo=TRUE}
gtbl <- gapminder
#just to have a nice short named dataframe... 
                      #one moment, just to make sure...

is.data.frame(gtbl)   #TRUE, thought so
glimpse(gtbl)         #just to remind myself of the variables and names again
```

**Comment by ahippman** [comment]
What I tried so far:
*opening and closing RStudio
*copying and pasting into new .rmd file
*double and triple checking that gapminder is really there
*creating an actual object called "gapminder" 
```{r, eval=TRUE}
gapminder <- gapminder
```
and also
```{r, eval=TRUE}
gapminder <- library(gapminder)
```
I am out of my wits and ready to throw out my laptop (which always helps, right?!)
Thanks for any help
Cheers
Anna

**Comment by cathyxijuan** [comment]
Can you push the code to github so we can take a look at it?

**Comment by ahippman** [comment]
which code do you mean?

**Comment by jennybc** [comment]
Is this in your course repo? Because I can just look at it there.

**Comment by ahippman** [comment]
[https://github.com/STAT545-UBC/anna_hippmann]
[HW03...](https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW03_AnnaHippmann_dplyrANDggplot_reloaded.md)

**Comment by ahippman** [comment]
Thats the pushed but somehow mutilated version

**Comment by ahippman** [comment]
This is now the .md file of my homework saved as `r-script` in RStudio, then pushed to github

[https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW03_AnnaHippmann_dplyrANDggplot_reloaded.r]

**Comment by ksamuk** [comment]
Just ran the code and it knitted successfully, no errors. Can you explain how you are generating the error you posted?

**Comment by ahippman** [comment]
So, it knitted now in RStudio again as well. I just left it (my computer) in peace for 25 min and didnt change / open/close anything. 
However, on Github, it still doesn't include the output of the R chunks, even though in the chuck code it does state `{r nameOfChunk, eval=TRUE}`
hmmm

**Comment by ksamuk** [comment]
Are you sure you successfully knitted the .Rmd? The .md still has the YAML header and no chunk output, which indicates it might not have actually been knitted from the .Rmd. 

Try this:

* Delete the .md and .html output, and the folder of images
* Open the .rmd file
* Click Knit HTML
* Examine the freshly made .md file: does it have a YAML header?/chunk output?

**Comment by ahippman** [comment]
@Kiaron @jennybc Thanks so far! I did everything you suggested, plus trying it out in explorer and firefox, cleaning up my harddrive...

* the plots are showing up now (I had totally forgotten to push the plots as well!)
BUT
the rest is still wrong (read below)

I don't understand, that in RStudio when I knit my .rmd
* it saves the .md
* it saves the .html
* the .html looks PERFECT in both **RStudio** and opened with **my browser**
 + `r code` in grey 
 + `r code output` in white
 + knitr table nicely formatted

BUT once I commit and push it to github and open the .md file there **in Github**:
* `r code` in grey - correct
* `r code output` in grey - **WRONG**
* knitr table format busted - **WRONG**

**Question**
when you look at my [anna_hippmann/HW03_AnnaHippmann_dplyrANDggplot_reloaded.md](https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW03_AnnaHippmann_dplyrANDggplot_reloaded.md), do you see it the same (WRONG) way, I am seeing it, or is showing it correctly?

Cheers
Anna

**Comment by dchiu911** [comment]
Have you tried knitr::kable(x, format = "markdown")?

**Comment by ahippman** [comment]
Thanks @dchiu911, the table looks now good! Even in the github repository: [HW03_AnnaHippmann](https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW03_AnnaHippmann_dplyrANDggplot_reloaded.md)

However, the issue with the grey background under the OUTPUT of `rcode` is still not solved

In contrast, the corresponding html published from rmarkdown in RStudio onto RPubs looks like this:
[http://rpubs.com/ahippman/115313]

**Comment by dchiu911** [comment]
Not sure it is an "issue". Someone correct me if I'm wrong, but I believe this is one of the differences between a `.md` and `.html` report. Another such difference is the rendering of the table of contents (using YAML).

**Comment by oganm** [comment]
When you knit to html, it will look more or less exactly the same independent of the setting (except browser differences and all). The md document on the other hand is subject to rendering settings of the platform you placed it in. For github's renderer, there is no difference between the code block defined for the r code you have written or the code block that is the output of the real code chunk. If you check your md file, you'll see that the output is marked with the same ``` you use to mark your own code.

**Comment by oganm** [comment]
Side note: you don't have to mention anyone I believe. We get notifications of every new issue

**Comment by ahippman** [comment]
Thanks for the background @oganm!
