### ISSUE TITLE
suggestions for the ideal 'commit' message?

### ISSUE THREAD

**Issue by JoeyBernhardt** [STAT545-UBC/Discussion#130]
Hi all,

Does anyone have any recommendations about what to include in a commit message? I'm never sure what to write, and/or how specific to be. I realize this is probably a highly personal preference type of thing, but it would be useful to hear suggestions on best practices, so as to make the version control process most useful.

Thanks!

**Comment by oganm** [comment]
I try to be as specific as I can while remaining concise. In your repo for instance I see tons of "delete files" commits. In long term project it could have been helpful to write what did you delete and why are they gone. You are writing those messages to your future self and your collaborators if you have any so better transparency is always useful.

**Comment by namanpaul** [comment]
I once had referred to this [wiki](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
Hope this would be helpful!

**Comment by jennybc** [comment]
You might find these helpful:

http://chris.beams.io/posts/git-commit/

http://willi.am/blog/2014/05/06/git-for-devs-who-cant-commit-good/

And this is just plain delightful:

http://www.threechords.org/blog/how-animated-gif-selfies-fixed-our-teams-morale/
