### ISSUE TITLE
tbl_df not working

### ISSUE THREAD

**Issue by jillguerra** [STAT545-UBC/Discussion#131]
Hi, 
I am having trouble using the tbl_df function. It worked in class but now, whether in a new file or when revisiting my class notes file, I get an error message that says "Error: could not find function "tbl_df"" 

This is the code I am using - pulled from class notes...  

```{r}
#install.packages("dplyr")

## from GitHub using devtools (which you also might need to install!):
#if (packageVersion("devtools") < 1.6) {install.packages("devtools")}
#devtools::install_github("hadley/lazyeval")
#devtools::install_github("hadley/dplyr")
#suppressPackageStartupMessages(library(dplyr))
library(gapminder)

gtbl <- tbl_df(gapminder) 
gtbl
```

I have tried it with and without the lines commented out in case it was something to do with previous packages being installed. 

The error comes up in the line gtbl <- tabl_df(gapminder)

Any thoughts?

**Comment by oganm** [comment]
You never libraried dplyr. R doesn't keep packages loaded when you restart it Add `library(dplyr)` to the beginning of your code

**Comment by jennybc** [comment]
What @oganm says.

You need to __uncomment__ the line that will load `dplyr` here:

``` r
#suppressPackageStartupMessages(library(dplyr))
library(gapminder)
```

**Comment by jillguerra** [comment]
Great, thank you! It is working now.
