### ISSUE TITLE
how do I plot the min and the max of in the same y- axis?

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#133]
Hello,

I've been working on the min and the max of the gdp, but I cannot seem to find the correct code to plot the min and the max in the same plot.
Here's the table I got:

m <- gtbl %>% group_by(continent) %>% 
summarize(min_gdp = min(gdpPercap), max_gdp = max(gdpPercap)) %>%
arrange(min_gdp, max_gdp)
m

but when I try to add

m + ggplot... 

I cannot plot it...

I found a page where they do it this way:
m + ggplot(m) + geom_point(aes(x = factor(continent), y = min_gdp), color = 'blue') + geom_point(aes(x = factor(continent), y = max_gdp), color = 'red')

but it wont work in this case..

What else can I try?

Thanks!
Brenda

**Comment by Haycen** [comment]
I suspect that: `m + ggplot` should be `m %>% ggplot` instead.

**Comment by jennybc** [comment]
``` r
library(ggplot2)
library(gapminder)
library(dplyr)

gapminder_tbl <- tbl_df(gapminder)

ggplot(gapminder_tbl, aes(x = continent, y = gdpPercap)) +
  scale_y_log10() +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4) +
  stat_summary(fun.y = min, colour = "blue", geom = "point", size = 5) +
  stat_summary(fun.y = max, colour = "orange", geom = "point", size = 5)
```

![](http://i.imgur.com/YcVy5Ri.png)

**Comment by jennybc** [comment]
I'm not claiming that's beautiful but should show you how this is done.

**Comment by bdacunha** [comment]
Thanks! I'll work according to this.

**Comment by wang114** [comment]
I also want to ask about how to display y-values beside points? I tried geom_text(), but I can only use that for a single point (by putting the y-value for the label = "y" argument). I don't think it's a clever way, and I don't know how to do this for all the points at once.

**Comment by MagdaPrice** [comment]
Adding to Jenny's code - try this, I plotted the mins for each group. Remember that this is on a log10 scale. Use the hjust and vjust arguments to modify the location of the labels. 

    ggplot(gapminder, aes(x = continent, y = gdpPercap)) +
      scale_y_log10() +
      geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4) +
      stat_summary(fun.y = min, colour = "blue", geom = "point", size = 5) +
      stat_summary(fun.y = max, colour = "orange", geom = "point", size = 5)+
      stat_summary(aes(label=round(..y..,2)), fun.y=min,geom="text", size=6, hjust = -0.3)

![image](https://cloud.githubusercontent.com/assets/13424175/10269459/82fa2696-6a8d-11e5-8daa-d6a714082885.png)

**Comment by hui-tony-zk** [comment]
check out [geom_errorbar](http://docs.ggplot2.org/0.9.3.1/geom_errorbar.html)

**Comment by eacton** [comment]
If you want to use your m frame and just plot the continents, min and max gdp - I would first reshape your data using the reshape2 package.  This way you can have your min/max as a variable that can be a factor, which makes it much easier to plot.  Here is some VERY minimalist code to achieve that.

```{r}
m <- melt(m, id.vars = "continent", value.name="gdpPerCap", variable="min_max")

mplot <- ggplot(m, aes(x=continent,y= gdpPerCap , colour = min_max)) + geom_point()
```

![minmax](https://cloud.githubusercontent.com/assets/6351674/10316530/8c355784-6c14-11e5-9f7a-1f76143207f7.png)

**Comment by MaryHe** [comment]
@eacton This is amazing!
I did similar things by making a new data frame that looks the same as the one you made with the function `melt`. However, using `melt` is so much easier! But I do not understand how did `melt` work. Could you please explain a little more how did `melt` work in this case?

**Comment by gjahesh** [comment]
@MaryHe 
I think melt is defined as way to change between wide-data(observations in the rows and variables in the columns) to long-data ( basically variables (i.e id.variables) and their measured values) I found this useful:
http://www.r-bloggers.com/reshape-and-aggregate-data-with-the-r-package-reshape2/

**Comment by jennybc** [comment]
We are working up to data reshaping and the idea of tidy data FYI. Soon!

**Comment by jennybc** [comment]
Aw, man, I made this yesterday but forgot to post. Here it is anyway. Here's how I would work with precomputed summary stats. Did I just post this on some other thread or am I going insane?

``` r
library(gapminder)
library(ggplot2)
library(dplyr)

m <- gapminder %>%
  group_by(continent) %>% 
  summarize(min_gdp = min(gdpPercap), max_gdp = max(gdpPercap)) %>%
  arrange(min_gdp, max_gdp)
m
#> Source: local data frame [5 x 3]
#> 
#>   continent    min_gdp   max_gdp
#>      (fctr)      (dbl)     (dbl)
#> 1    Africa   241.1659  21951.21
#> 2      Asia   331.0000 113523.13
#> 3    Europe   973.5332  49357.19
#> 4  Americas  1201.6372  42951.65
#> 5   Oceania 10039.5956  34435.37

ggplot(gapminder, aes(x = continent, y = gdpPercap)) +
  scale_y_log10() +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4) +
  geom_point(data = m, aes(x = continent, y = min_gdp), colour = "blue", size = 5) +
  geom_point(data = m, aes(x = continent, y = max_gdp), colour = "orange", size = 5)  
```

![](http://i.imgur.com/b89EMI9.png)
