### ISSUE TITLE
HW3 layout and table stretch goal

### ISSUE THREAD

**Issue by wang114** [STAT545-UBC/Discussion#135]
In homework 3 under **But I want to do more!** it says there will be links and tricks for placing table and figure side by side and table helper packages.  I couldn't find anything on the course website. Did I miss it or we are supposed to find out the answers to these problems by ourselves (for now at least)?

**Comment by jennybc** [comment]
This Gist has one very quick and dirty way to do it.

https://gist.github.com/jennybc/e9e9aba6ba18c72cec26

If anyone wanted to pursue this further and find or devise alternate approaches, that would be great. But it's totally an optional thing.

**Comment by mstrimas** [comment]
At the bottom of the [general homework guidelines](http://stat545-ubc.github.io/hw00_homework-guidelines.html#make-pretty-tables) page there are a few points on making nice tables. [This flowchart](https://twitter.com/polesasunder/status/464132152347475968) seems like a good place to start.
