### ISSUE TITLE
Hyperlink to place/header within the .rmd file?

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#138]
Hello! 
Just a relatively general question: I do know how to put links in an .rmd file. And it works (I am still amazed by this... every time! :) )
I was just wondering, **how I can put a link to a place further down within the same file**. E.g. to a different header further below etc.. It mus be possible, as @jennybc makes it happen all the time in her files.

Nothing super crucial right now... I was just wondering... can also ask it in class tomorrow
Cheers
Anna

**Comment by jennybc** [comment]
You need to use HTML anchor tags. Markdown itself doesn't really support this but you can usually put HTML in Markdown to achieve slightly fancier things and this is a good example.

Let's say you write this at the place you want to leave an internal link:

```
Take me to [your leader](#your_leader)
```

Then elsewhere in the document -- wherever the leader is! -- put this **anchor tag**:

```
<a id="your_leader"></a>
```

Yes that last part will be invisible in the rendered result, but it provides a destination to jump to.

If the destination is, say, a header it might look like this:

```
### <a id="your_leader"></a>Your leader
```

You can get some internal links "for free" in Rmd by requesting a table of contents in your YAML front matter. Here's an example of YAML that will produce a TOC:

```
---
title: "Something fascinating"
output:
  html_document:
    toc: true
    toc_depth: 4
---
```

**Comment by ahippman** [comment]
Awesome, thanks! I'll try it out later!





Anna Hippmann, PhD Student

Department of Earth, Ocean and Atmospheric Sciences
The University of British Columbia
Room 2041, Earth Sciences Building
2207 Main Mall
Vancouver, British Columbia
Canada, V6T 1Z4

ahippman@eos.ubc.ca
office +1-604-827-5459
cell +1-604-771-8346

**Comment by ahippman** [comment]
It's working and it's so much nicer to jump between headers to check up on things in my homework... and hopefully later on in my own stuff. Yeahy

**Comment by ahippman** [comment]
The only thing funny is that ti shows perfectly well on github but a wee bit out of tune in RStudio html version

**Comment by eacton** [comment]
Also @ahippman, opts_chunk$set(comment = NA) should remove the ## in your chunk output globally or comment=NA in individual chunks.
