### ISSUE TITLE
Customizing Xtable

### ISSUE THREAD

**Issue by eacton** [STAT545-UBC/Discussion#142]
Today at office hours a student asked me about how to customize column widths in xtable, which had looked  a somewhat syntax nightmare.  It looks like to me like making a custom template might be one way to go. 

https://nsaunders.wordpress.com/2012/08/27/custom-css-for-html-generated-using-rstudio/

Keep in mind, however, that it WAS found in a blog called "What You're Doing Is Rather Desperate", so I am sure someone out there has better ideas.  Please post them here.

**Comment by jennybc** [comment]
I feel like the "fancy tables in Rmd" world has advanced alot since 2012, so my instinct is that there are more fruitful avenues to be pursuing here.

**Comment by eacton** [comment]
I agree totally.  I think curiousity will kill the cat on this one.

**Comment by eacton** [comment]
Closed #142
