### ISSUE TITLE
can't knit a file if I haven't run the code chunks first

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#144]
I think this might be an issue best addressed in person at office hours. However, I wanted to

1. see if anybody else has encoutered this problem 
2. check if there is a quick fix in the settings 
3. remind myself not to forget to adress it

#### So, what is the issue?
When I start a new RStudio session and open up my .rmd homework file and want to knit it to double check the state of the file, it gives me one error message after another:
It can't find the libraries, the objects etc... even though the libraries and objects etc are all called up / created within the r chunks of the .rmd files. 

#### How do I get around it at this point?
Manually, I execute all of the code chunks. Then I knit.

Any ideas? anybody encountered this problem?

Cheers
Anna

**Comment by jennybc** [comment]
Have you pushed the exact Rmd file in question to your course repo? Because a TA or I should just look at that directly.

**Comment by ahippman** [comment]
Yes, both [.rmd](https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW03_AnnaHippmann_dplyrANDggplot_reloaded.Rmd) and [.md](https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW03_AnnaHippmann_dplyrANDggplot_reloaded.md) file

WAIT, I just restarted RStudio, just to make sure that it's still going on... and this time, it knitted no problem. I do not understand. Sorry! Will repost, when I encounter the same problem again.

**Comment by jennybc** [comment]
The "restart RStudio" lesson is a good one to learn :smile:.

Power cycling works in so many domains!

**Comment by cathyxijuan** [comment]
R does crash sometimes. I have seen some weird behaviour in R when it crashes. Sometimes, it doesn't seem to be freezing for real but it still has weird behaviour.
