### ISSUE TITLE
DPLYR: How can I filter rows via "NA"

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#146]
Hello,
I tried to find an answer in the web and tried out several combination of my own make up... can anybody help?

```{r, eval=TRUE}
x <- 1:10
y <- c(1, 2, 3, 4, NA, 6, 7, NA, 9, 10)
df <- data.frame(x,y)
```
how can I subset or filter the rows that have NA in them?

I tried, e.g.:

```{r, eval=TRUE}
df.na <- df %>% filter(y !is.na) error # Error: filter condition does not evaluate to a logical vector.

df.na <- df %>% filter (y == "NA") #will result in a df without any rows, just header
```

**Comment by ksamuk** [comment]
Try `df.na <- df %>% filter(!is.na(y))`

**Comment by cathyxijuan** [comment]
try use `complete.cases()`
`myData %>% filter(complete.cases(.))`

**Comment by ahippman** [comment]
@ksamuk works perfect!
@cathyxijuan might be useful later when I want to filter all that have an actual value and no NA.
 Thanks a bunch guys!!!!
