### ISSUE TITLE
HW01 marks mailed, HW02 marking underway, HW03 peer review open

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#147]
HW01 marks mailed. Did you get an email from me? No? Get in touch because that means the email address I got from the survey isn't working.

HW02 marking underway. Expect to see a TA coming through in the coming days.

HW03 peer review open. Did you get assigned 2 peers to review? Did 2 peers get assigned to review your work? No? Get in touch!

**Comment by wang114** [comment]
I didn't get the email about HW1 marks. (I did get emails for HW3 peer review). @jennybc
