### ISSUE TITLE
Do I have to give a mark for peer review?

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#148]
I have always given mark for the peer review. I am wondering if it is necessary. I have seen peer review that didn't give a mark at the end, and I would really prefer not giving a mark, just give comments.

**Comment by bdacunha** [comment]
I think Jenny said in class that you don't really have to leave a mark, just your comments. The TA's will take care of the marking :)

**Comment by cathyxijuan** [comment]
Thanks!

**Comment by jennybc** [comment]
Correct. You certainly can, but you don't have to leave a check plus / check / check minus type of mark.
