### ISSUE TITLE
Elections Canada

### ISSUE THREAD

**Issue by martinsing** [STAT545-UBC/Discussion#149]
Need a quick job that pays well for a day or two of work?

Check out [elections.ca](www.elections.ca) to find your electoral district and give them a call to see if they still need workers or at least standby poll workers. 

Pay is roughly:
* ~$180 for working the poll day (October 19)
* ~$600 for working advance polls (October 9-12)
* $50 for each training session
* up to $800

If you live in the Vancouver-Granville Electoral District, see below, then please contact me for more information. martinsing@gmail.com or 778-386-0322. Thanks.

![Vancouver-Granville](http://www.vancouverobserver.com/sites/vancouverobserver.com/files/images/article/body/vancouver_granville_federal_riding_-_vancouver_observer.jpg)

**Comment by gjahesh** [comment]
Thanks Martin for the information. I'll be working as a deputy register officer in the SUB(Student Union Building) on Monday Oct 19. I just wanted to share information about the election day and encourage all whore are qualified to vote, to come and exercise their right :

As you might know the Federal Election is taking place on Monday Oct.19 and for those of you who are eligible and have not already voted on he advance voting, Monday Oct.19 is the last day to exercise your right. 

To be eligible to vote you need to be:

1. 18 years old or older on the election's day
2. a Canadian Citizen
3. Resident in your electoral district
4. Registered on the voters list ( also called the list of electors)

Are you registered for the election?

To check if you are already registered to vote , please check Elections Canada' s website:

http://www.elections.ca/home.aspx

Note that although Elections Canada emphasizes strongly that the voters have to register, you could still vote even  if you are not registered, if and only if  you meet the first 3 requirements  mentioned above.  To do so, you must prove your identity and address to vote on the election. 

IDs to Vote:

The complete list of accepted IDs can be found here:

http://www.elections.ca/content2.aspx?section=id&document=index&lang=e#name

Tips for student voters:

You can prove your identity with your student ID card.
You can prove your address with any document issued by your school that shows your home address.
If you live in a student residence, you can ask the residence administrator for a Letter of Confirmation of Residence that says you live there. You can use it to prove your address.
for more info please refer to:
http://www.elections.ca/content2.aspx?section=stu&dir=id&document=index&lang=e

Have you recently moved?

Elections Canada requires one(1) of the two(2) IDs to have the current address but 
If you recently moved and still have not changed your address of resident,  Elections Canada's solution is as follow:

 If your ID does not have your current address, take an oath

Show two pieces of ID with your name and have someone who knows you attest to your address. This person must show proof of identity and address, be registered in the same polling division, and attest for only one person.

Please note that the person who testifies for you need to be eligible as a voter, hence must fulfil the requirements menioned above.

Where to vote on Campus:

If you live on campus your electoral district is Vancouver Quadra and you could easily vote on campus here:

Student Union Building (SUB)
Ballroom
6138 Student Union Boulevard
Vancouver, BC V6T 1Z1

Voting Hours On Monday Oct19

7:00 Am to 7:Pm 

List of Candidates:

http://www.elections.ca/Scripts/vis/candidates?L=e&ED=59039&EV=41&EV_TYPE=1&PC=v6t1z4&QID=-1&PAGEID=17

Don't live on Campus?

And just in case you (or friends) don't live on campus check your voting station here:

http://www.elections.ca/Scripts/vis/Voting?L=e&ED=59039&EV=41&EV_TYPE=1&PC=v6t1z4&QID=3&PAGEID=31

FAQs:

http://www.elections.ca/content2.aspx?section=faq&dir=reg&document=index&lang=e#reg2
