### ISSUE TITLE
HW04

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#150]
Just wondering when HW4 is due?

cm009 overview says it will likely be due later next week, but I don't believe we've learnt about split-apply-combine yet (unless thats just another way of saying "use dplyr"...), so even if it will be due Thursday that would only give us 2 days after learning split-apply-combine on Tues

I'd like to get started on the HW due to limited time next week, are there any big changes from last years HW4 (https://stat545-ubc.github.io/hw04_write-function-use-plyr.html)?

**Comment by jennybc** [comment]
I just took a closer look at the existing 2014 HW04. The only change you will see is that I will open up the *how*, i.e. I won't insist you use `plyr::ddply()`. On Tuesday I will show various strategies for split-apply-combine, with more of an emphasis on newer packages, such as `dplyr` and maybe even `purrr`(?). But the material on `plyr::ddply()` already exists and it's still a viable option.

I was thinking of due date = Friday October 16. I think that will still be comfortable.

But if there is mass anxiety, we'll just push it back to Monday October 19. Let's see how Tuesday's class goes. I will not stick to some pre-conceived due date if it's clear the students need more time.
