### ISSUE TITLE
animated gapminder inspiration

### ISSUE THREAD

**Issue by SarahUBC** [STAT545-UBC/Discussion#151]
Hi all. For the most recent homework assignemnt, I recommend checking out this site with [animated visualizations of the gapminder data](http://www.gapminder.org/world/#$majorMode=chart$is;shi=t;ly=2003;lb=f;il=t;fs=11;al=30;stl=t;st=t;nsl=t;se=t$wst;tts=C$ts;sp=5.59290322580644;ti=2013$zpv;v=0$inc_x;mmid=XCOORDS;iid=phAwcNAVuyj1jiMAkmq1iMg;by=ind$inc_y;mmid=YCOORDS;iid=phAwcNAVuyj2tPLxKvvnNPA;by=ind$inc_s;uniValue=8.21;iid=phAwcNAVuyj0XOoBL_n5tAQ;by=ind$inc_c;uniValue=255;gid=CATID0;by=grp$map_x;scale=log;dataMin=194;dataMax=96846$map_y;scale=lin;dataMin=23;dataMax=86$map_s;sma=49;smi=2.65$cd;bd=0$inds=;example=75).

I particularly like the feature of turing a tail on when viewing the country data over time so you can easily see when there are rapid changes in life expectancy and/or GDP per capita. 

Any super-keeners have pointers on learning how to animate data in R? 

Best,
Sarah

**Comment by farnushfarhadi** [comment]
Hi Sarah, 

Your question is interesting to me.  I have searched for it and I came up with using `ggplot2` and `animation

**Comment by farnushfarhadi** [comment]
Hi Sarah, 

Your question is interesting to me.  I have searched for it and I came up with using `ggplot2`, `animation` and `anim.plots`. 

For creating an animated plot, you can use `anim.plot()` function by installing `anim.plots

**Comment by jennybc** [comment]
I'm getting nostalgic now. Back when I taught this course using base and lattice graphics, I made some really low-tech animations. I present them here to lay down the gauntlet. 😁

Here's base graphics:

![gapminder](https://cloud.githubusercontent.com/assets/599454/10444141/d03c9ed0-7117-11e5-9d28-09bb8f8243c1.gif)

Here's with lattice:

![gapminder](https://cloud.githubusercontent.com/assets/599454/10444145/dec1c372-7117-11e5-8479-1e46d3b65211.gif)

**Comment by farnushfarhadi** [comment]
Hi Sarah,

Your question is interesting to me. I have searched for it and I came up with using ggplot2, animation and anim.plots.

For creating an animated plot, you can use anim.plot() function by installing `anim.plots` package in R. Here is an example I found by this [link](https://cran.r-project.org/web/packages/anim.plots/anim.plots.pdf):

```{r}
anim.plot(x, y = NULL, times = 1:length(x), speed = 1,
show = TRUE, use.times = TRUE, window = if (identical(fn, lines)) t:(t +
1) else t, window.process = NULL, xlim = NULL, ylim = NULL,
col = par("col"), xaxp = NULL, yaxp = NULL, pch = par("pch"),
cex = 1, labels = NULL, asp = NULL, lty = par("lty"),
lwd = par("lwd"), fn = plot)
```

For adding a trail to follow a global view of change of your data, I found this [stack **overflow**](http://stackoverflow.com/questions/21018026/producing-an-animated-comet-plot-in-r) post useful. 

I think this code is for controlling the trail in your plot: 
```{r}
saveGIF({
 lapply(1:nrow(path),function(x)plot_arrow(max(1,x-5):x))
},movie.name="comet.gif",interval=0.2)
```

You can change the parameter in `plot_arrow()` to get more trail effects. I run the code with `x-100` and I could see the trail of the point. 
I hope it helps. 

Best,
Farnush

**Comment by SarahUBC** [comment]
Thanks Jenny and Farnush. Great tools for animated visualizations!
~Sarah

**Comment by jennybc** [comment]
This gist from @jeroenooms shows another quick and dirty way to get animation using things you already know:

https://gist.github.com/jeroenooms/fa60515cd84dd1ce6e61
