### ISSUE TITLE
Stata or R for survey data analysis?

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#152]
Has anyone worked with both Stata and R for survey data analysis? Any strong preferences there? 
I use Stata, but I'm loving the plots in R and thinking about switching over to the 'survey' package in R. 

Cheers
Poushali

**Comment by jennybc** [comment]
Use R! And I trust @tslumley implicitly, therefore survey must be awesome :smile:.

http://r-survey.r-forge.r-project.org/survey/

**Comment by tslumley** [comment]
Stata has a wider range of regression models for survey data (though [they can be added](http://notstatschat.tumblr.com/post/119901462361/zero-inflated-poisson-from-complex-samples) to R); 'survey' in R has a wider range of designs and weight calibration methods, and has better graphics and survival analysis support.

**Comment by Poush87** [comment]
Thanks! :)
A quick stackoverflow search says the practical limit for dataframes in R is about  2^31. Just wondering if R complains at all while dealing with large data files - I have survey data of about 7GB (I won't be loading all of it at once, but it'll still be a large file)?

**Comment by tslumley** [comment]
Depends on how much memory you have.  The theoretical limit is 2^31 *rows*, not bytes, but a more important limit is that R gets slow when a single object takes up more than about 1/3 of physical ram. 

The database-backed survey objects in the survey package automatically load only the variables actually used in any given computation, which makes it (just) possible to analyse BRFSS (half a million large records) with 2Gb RAM, as I did when writing my book. With modern laptops BRFSS isn't a problem.

For really large surveys you might look at the [sqlsurvey package](http://sqlsurvey.r-forge.r-project.org/), which does most of the computations in the MonetDB column-store database and can analyse files from the American Community Survey (10^7 records) on a laptop, more or less interactively.  This package isn't on CRAN, and it has fewer methods implemented than 'survey', but it's got all the basics.

**Comment by oganm** [comment]
As a side note: dpylr package works with databases as well while trying to touch them as little as possible. As long as you subset your data nicely, you shouldn't encounter any problems. Below is a tutorial on using dplyr with databases
https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html

**Comment by tslumley** [comment]
Yes, it does, and I may try to rewrite sqlsurvey using dplyr.  However, dplyr isn't a substitute at the moment because it doesn't know how to do the probability-weighted analyses.   

MonetDB is still worth knowing about for large data sets, since it's very fast at aggregation operations (column-store, and optimised for scientific computation)
