### ISSUE TITLE
Statistics crash course for HW04

### ISSUE THREAD

**Issue by hui-tony-zk** [STAT545-UBC/Discussion#153]
In [HW04](https://stat545-ubc.github.io/hw04_write-function-split-apply-combine.html#inspiration-for-what-to-compute) under "inspiration for what to compute", there is a lot of discussion regarding models/fits/etc. The following is an excerpt 

>**...Fit a regression using ordinary least squares and a robust technique. Determine the difference in estimated parameters under the two approaches....**

>**Wear your statistical hat and characterize how well/poorly the simple linear model is working. Via residual analysis. Or by fitting something more complicated (but still appropriate for n = 12!) – like a degree 2 polynomial. Retain quantities that speak to goodness-of-fit and explore that across all 142 countries.**

Could I get a crash course on statistics? Either some help or links to resources? The extent of my knowledge about statistics is t-tests, pvalues, z-scores (UBC STAT 200).

* What are ordinary least squares?
* What is a robust technique?
* What are estimated parameters?
* How does one characterize how well/poorly the simple linear model is working via residuals? In fact, what is a residual?
* What is a degree 2 polynomial fit? Is it just an x^2 fit? How do I go about doing this in R?
* What does it mean to "retain quantities that speak to goodness-of-fit and explore that across all 142 countries"?

**Comment by jennybc** [comment]
OK STAT grad students, here is your moment to shine!

I will also come back soon with some answers.

**Comment by dchiu911** [comment]
>What are ordinary least squares?

This is the least squares method of linear regression you learned in STAT 200.

>What is a robust technique?

A robust technique is one that is not sensitive to outliers.

>What are estimated parameters?

In simple linear regression, the estimated parameters are the intercept and slope.

>How does one characterize how well/poorly the simple linear model is working via residuals? In fact, what is a residual?

In a residual plot, there should be no systematic patterns. A residual is the difference between the response (y) and the estimated response (y_hat) from regression.

>What is a degree 2 polynomial fit? Is it just an x^2 fit? How do I go about doing this in R?

The response (y) is modeled by the explanatory variables (x) where the highest degree for x for any term is 2. For example, y = B0 + B1x + B2x^2 and y = B0 + B1x^2 are both degree 2 polynomial fits.

>What does it mean to "retain quantities that speak to goodness-of-fit and explore that across all 142 countries"?

Some goodness-of-fit quantities in regression are R-squared and AIC.

**Comment by hamid-omid** [comment]
This online course might be of help, specifically linear regression part:
https://www.coursera.org/learn/machine-learning

Although elementary, the material in this link has the asnwer to some of your questions:
https://courses.edx.org/c4x/UTAustinX/UT.7.01x/asset/Week_5_-_Optional.pdf

**Comment by daattali** [comment]
A couple of additions to above:

**ordinary least squares**:
After reading the help for `lm` in R, I believe that ordinary least squares is what's used in `lm` as long as you don't provide a `weights` argument. 

**robust methods**
After a quick Google, I found that you can do a robust fitting using `MASS::rlm`. Here's a very basic example: 

```
# create x, y with clear relationship (y = x), except the last observation is an outlier
df <- data.frame(x = 1:50, y = c(1:49, 0))  
lm(x ~ y, data = df)$coefficients
MASS::rlm(x ~ y, data = df)$coefficients
```

We expect the intercept to be 0 and the slope to be 1.  You can see that the `lm` model is very sensitive to the outlier, but the `rlm` model is much better

**Comment by jennybc** [comment]
What are ordinary least squares?

> Unless you make a special effort, any model you fit will probably be via least squares. "Find the line that minimizes the sum of squared difference between observed and predicted/fitted."

What is a robust technique?

> Robust techniques use a fitting criterion that is less influenced by one or a small handful of data points. In the assignment itself, I recommend you use `robustbase`. It would be interesting to fit the model using least squares (the `lm()` default) and `robustbase::lmrob()`. How similar / different are they? When they are different, what does the data tend to look like? Is there an outlier, i.e. do robust methods deliver what they promise?

How does one characterize how well/poorly the simple linear model is working via residuals? In fact, what is a residual?

> Residual = observed y (life expectancy) - fitted/predicted y (a point on the fitted line).
> Look at the Zimbabwe example we did in class. Terrible fit, right? A line is an awful idea in that case. What is true about the residuals? Is there a pattern? Could you use `dplyr` and `do` to analyze the residuals from all 142 country-specific regressions to find other countries where the linear model is a terrible fit?

What is a degree 2 polynomial fit? Is it just an x^2 fit? How do I go about doing this in R?

``` r
lm(y ~ poly(x, degree = 2, raw = TRUE), my_data)
```

What does it mean to "retain quantities that speak to goodness-of-fit and explore that across all 142 countries"?

> Residuals, summary statistics of residuals, estimated error variance, R-squared, etc. all speak to how much of the variability in life expectancy is "explained" by your linear or polynomial model based on year.

**Comment by hui-tony-zk** [comment]
Thank you all for your comments. I played around with Zimbabwe, taking into account all that I've learned here. You can see the README here: https://github.com/STAT545-UBC/tony_hui/tree/master/random_class_stuff/stats_crash_course

Just some follow-up questions:
* Ordinary least squares = line that minimizes residuals right? Is this why ordinary least squares method lines are "better" than robust methods because they include outliers (and robust methods throw out outliers)?
* How does a robust linear method determine if something is an outlier? Apparently there are two methods: M and MM, where MM is the following (could I get a translation on what this means?):

>Selecting method = "MM" selects a specific set of options which ensures that the estimator has a high breakdown point. The initial set of coefficients and the final scale are selected by an S-estimator with k0 = 1.548; this gives (for n >> p) breakdown point 0.5. The final estimator is an M-estimator with Tukey's biweight and fixed scale that will inherit this breakdown point provided c > k0; this is true for the default value of c that corresponds to 95% relative efficiency at the normal. 

* Are more polynomials always better fitting (e.g. x^3 > x^2 > x) in terms of minimizing residuals?

* What does `the difference in estimated parameters` between two models tell you?

**Comment by jennybc** [comment]
Ordinary least squares = line that minimizes residuals right?

> Minimizes the sum of __squared__ residuals. Hence the name.

Is this why ordinary least squares method lines are "better" than robust methods because they include outliers (and robust methods throw out outliers)?

> You cannot say either is better globally, no matter what. But I tend to think the other way around. Robust methods are probably safer because they will behave better on more datasets in real life.

How does a robust linear method determine if something is an outlier?

> There are very many ways and I'm not going to get into that here. For this homework, it really is enough to know that robust methods are supposed to be less sensitive to one or two weird data points and, therefore, are more practical to use. Because you don't need to manually and subjectively flag outliers yourself. Managing this tension is what things like AIC and BIC are meant to do. Again, beyond scope of what we've covered, so don't go there if it's new to you.

Are more polynomials always better fitting (e.g. x^3 > x^2 > x) in terms of minimizing residuals?

> The more terms in a model, the better it will fit the data. Put in one term per data point and the fit will be perfect! But use that to predict future data and performance will be terrible. That's called __overfitting__.

What does the difference in estimated parameters between two models tell you?

> I'm actually going to leave this one for you to ponder.
