### ISSUE TITLE
Dataframe contains lists not vectors

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#154]
I have an issue where using my function on the gapminder dataset results in a dataframe that contains lists and not vectors: https://github.com/STAT545-UBC/simon_ho/blob/master/Homework/homework_04.md

So, my all_rate_of_change dataframe contains a bunch of lists. This creates a whole bunch of problems later.

How do I turn the lists into vectors?

I have tried `df2 <- as.data.frame(lapply(all_rate_of_change, unlist))` but it gives me an error:

`Error in data.frame(country = 1:142, mean = c(1.36609090909091, 1.92663636363636,  : 
  arguments imply differing number of rows: 142, 143`

I'm not even sure how I ended up with lists in the first place. Any advice?

**Comment by oganm** [comment]
The problem is with Malaysia. When you are finding the max rate of change, Malaysia has two years where rate of change is equal to the max value. This results in the function returning an unexpected variable, breaking everything else downstream.

This might happen when you rely on absolute matches especially with large datasets with low precision.

**Comment by jennybc** [comment]
Let's see if I can flush out some great material on this issue:

https://twitter.com/JennyBryan/status/654307664155947008

But @sho-87 I'll try to take a look at your specific code later.

**Comment by sho-87** [comment]
@oganm so I took a look at Malaysia and it doesn't seem like its any different than the other countries. When passed into the function, the number of rows is equal to 12 (same as other countries), and when the object is returned it correctly returns, averages, mins and maxes.

So even if malaysia has a double data point it doesn't seem like thats changing the return of the function at all

**Comment by sho-87** [comment]
@oganm nevermind. I understand what you mean now and fixed the problem. This then allowed me to convert everything back into vectors, so all is good now!
