### ISSUE TITLE
testing function only with different countries?

### ISSUE THREAD

**Issue by zhamel** [STAT545-UBC/Discussion#155]
I have created a function which return the maximal rate of change in life expectancy in a country and the interval (years) over which it happens. And I am not sure how much I can "test" my code except trying different countries and see that it matches with the graph.

It is sort of like the linear regression function we did in class, where we simply checked our function with different countries (different from range where we could input 'anything').
- Do I still need to assume I may get "weird" inputs (my only input is x = country)? 
- Should I assume I may get NA values, or vectors of the 'wrong' size? 
- Or can I just assume everything will work nicely?

Thanks!

**Comment by jennybc** [comment]
You are welcome to adjust your paranoia to what you know about the Gapminder data. It's very clear and you'll be calling your function in very limited, controlled circumstances. So, unless you just feel like it, you don't need to go to extremes on HW04 with runtime assertions or unit tests. Alot of that was just to make sure you know about that stuff in the future.
