### ISSUE TITLE
problems with setNames and converting to data.frame

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#156]
Hi

I've been trying to convert the output of my function to a data.frame, just like we did in class, but I can't do it so far. Also, I can't change the names... is there something that I'm missing?
I've tried:

le_diff <- function(dat, offset = 1952) {
  the_fit <- lm(gdpPercap ~ I(year - offset), dat)
  setNames(data.frame(t(coef(the_fit))), c("intercept", "slope"))
  the_robust <- lmrob(gdpPercap ~ I(year - offset), dat)
  setNames(data.frame(t(coef(the_robust))), c("intercept", "slope"))
  coef(the_fit) - coef(the_robust)
  }
le_diff(b_dat) 

and also:

le_diff <- function(dat, offset = 1952) {
  the_fit <- lm(gdpPercap ~ I(year - offset), dat)
  the_robust <- lmrob(gdpPercap ~ I(year - offset), dat)
  setNames(data.frame(t(coef(the_fit) - coef(the_robust)), c("intercept_diff", "slope_diff"))
  coef(the_fit) - coef(the_robust)
  }
le_diff(b_dat)

And almost every possible variation of this... but it won't work

Suggestions very much appreciated!

Brenda

**Comment by sho-87** [comment]
what are you wanting to return? What do you expect to see and what do you actually see?

Because it looks like you're creating a dataframe out of the coefficients, but actually returning coef(the_fit) - coef(the_robust), which I assuming is the subtraction of 2 vectors, hence returning a vector of the differences.

**Comment by bdacunha** [comment]
well I wanted to see the difference between the least squeare fit and the robust fit...and that's what I came up with... and I want to get a data.frame so I can apply this to every country

**Comment by jennybc** [comment]
Your `setNames(...)` commands are being executed **but not assigned to any object**. So names of `the_fit` and `the_robust` are not being actually set or changed. I would also return all of the estimate coefficients and -- once collected for all 142 countries -- initiate explorations. Which could include take the difference, as you do. But you want the actual estimates so you can make, e.g., some exploratory plots.

**Comment by sho-87** [comment]
Something like this?

library(gapminder)
library(robust)

b_dat <- gapminder

le_diff <- function(dat, offset = 1952) {
    the_fit <- lm(gdpPercap ~ I(year - offset), dat)
    the_robust <- lmrob(gdpPercap ~ I(year - offset), dat)

    setNames(data.frame(t(coef(the_fit) - coef(the_robust))), c("intercept_diff", "slope_diff"))
    
}

test <- le_diff(b_dat)
class(test)

In your earlier examples you were converting the interim coefficients to dataframes, when really you want to compute the difference and then convert that to a dataframe. Without explicitly invoking `return()`, the thing that will return is the last thing that was evaluated (which in your case above was not a dataframe).

**Comment by jennybc** [comment]
Hopefully this helps

``` r
x <- 1:3
x
#> [1] 1 2 3
## sure this executes but ...
setNames(x, c('one', 'two', 'three'))
#>   one   two three 
#>     1     2     3
## it HAS NO EFFECT ON x because there's no assignment back into x!!
x
#> [1] 1 2 3
## make an assignment to x or new_x or whatever
x <- setNames(x, c('one', 'two', 'three'))
## now it has an effect
x
#>   one   two three 
#>     1     2     3
```

**Comment by jennybc** [comment]
@sho-87 is also giving good advice to do all the computations and, only at the last moment, put things into a data.frame. But I still think you should return all 4 parameter estimates and do your exploration and differencing once you've collected them across all countries.

**Comment by min110** [comment]
this might be irrelevant, and u highly likely already know , but I use tidy() and augments() to avoid resetting the names @bdacunha

**Comment by bdacunha** [comment]
thanks! I will try to use that in the next assignment!
