### ISSUE TITLE
Issue when applying function to all countries

### ISSUE THREAD

**Issue by ninafebner** [STAT545-UBC/Discussion#158]
I wrote this function to look at max absolute residuals:

residualfinal <- function(x) {
  jFit <- lm(lifeExp ~ I(year - min(x$year)), x)
  jCoef <- coef(jFit)
  names(jCoef) <- NULL
  return(c(intercept = jCoef[1],
           slope = jCoef[2],
           maxResid = max(abs(resid(jFit)))))
  data.frame(t(residualfinal))
}

It works when I do this:

residualfinal(gapminder %>% filter(country == "Zimbabwe"))

But not when I do this:

residuals_all <- gapminder %>%
  group_by(country) %>%
  do(residualfinal(.))

I get an error saying that the results are not in data frames at potions....
I think I might have written my original function incorrectly? Or am writing the wrong dplyr::do to get max absolute residuals for all countries. Eventually I want to be able to try and get the country with the biggest residual for each continent, so any help with that would be appreciated as well. Thanks!

**Comment by ksamuk** [comment]
I think you have to assign the output of 'do' to a name, like in 'summarise'. So try:

```
residuals_all <- gapminder %>%
	group_by(country) %>%
	do(resid = residualfinal(.))
```
Which returns a data_tbl with a list-column 'resid':
```
> residuals_all
Source: local data frame [142 x 2]
Groups: <by row>

       country    resid
        (fctr)    (chr)
1  Afghanistan <dbl[3]>
2      Albania <dbl[3]>
3      Algeria <dbl[3]>
4       Angola <dbl[3]>
5    Argentina <dbl[3]>
6    Australia <dbl[3]>
7      Austria <dbl[3]>
8      Bahrain <dbl[3]>
9   Bangladesh <dbl[3]>
10     Belgium <dbl[3]>
..         ...      ...
```

and then

```
residuals_all$resid[1]
```

too access individual results.

And then perhaps
```
lapply(residuals_all$resid, function(x) x[3])
```
to extract all the 'maxresid' values

**Comment by bdacunha** [comment]
I don't know if I'm having the same issue, but I get these warnings when I try to run my function le_diff which is the difference between the linear fit and the robust fit. This function works fine for individual countries, but not for the data.

Function:
le_diff <- function(dat, offset = 1952) {
  the_fit <- lm(gdpPercap ~ I(year - offset), dat)
  the_robust <- lmrob(gdpPercap ~ I(year - offset), dat)
  x <- coef(the_fit) - coef(the_robust)
  x <- setNames(data.frame(t(x)), c("intercept_diff", "slope_diff"))
  x
  }
le_diff(b_dat)

The function in gapminder:

diff_1 <- gapminder %>%
+   group_by(country) %>% 
+   do(test=le_diff(.))
Warning messages:
1: In lmrob.fit(x, y, control, init = init, mf = mf) :
  M-step did NOT converge. Returning unconverged SM-estimate
2: In lmrob.S(x, y, control = control, mf = mf) :
  find_scale() did not converge in 'maxit.scale' (= 200) iterations
3: In lmrob.S(x, y, control = control, mf = mf) :
  find_scale() did not converge in 'maxit.scale' (= 200) iterations
4: In lmrob.fit(x, y, control, init = init, mf = mf) :
  M-step did NOT converge. Returning unconverged SM-estimate

**Comment by ninafebner** [comment]
Thanks @ksamuk !

**Comment by ninafebner** [comment]
do you have any advice for getting code about finding the nation in each continent with the largest residual?

**Comment by jennybc** [comment]
The process would look something like:

  * Fit country-specific regressions.
  * Use `broom::augment()` to get all the residuals.
  * Then `group_by()` continent.
  * Get within-continent ranks on (absolute?) residuals.
  * Pull out the row of the max resid for each continent.

It has some elements in common with our Grand Finale example from the dplyr lesson in class:

http://stat545-ubc.github.io/block010_dplyr-end-single-table.html#grand-finale
