### ISSUE TITLE
gather() question

### ISSUE THREAD

**Issue by molliejmcdowell** [STAT545-UBC/Discussion#160]
Hello! We wrote this line in class:
gather(cases, "year", "n", 2:4)

But @jennybc said that she would change 2:4 to the actual years (2011, 2012, 2013) in her code so that it would be easier to read.

I am trying to figure out how to actually change 2:4 into 2011, 2012, 2013... @ksamuk figured out a sort of complicated way of doing it:
gather(cases, "year", "n", which(names(cases) %in% c("2011", "2012", "2013")))

but that just doesn't seem like it's easier to read. Any suggestions?

thanks! 
mollie

**Comment by hamid-omid** [comment]
Try this:
gather(cases, "year", "n", -country,v-2011, -2012,v-2013)

It works for me!

**Comment by molliejmcdowell** [comment]
Thanks Hamid! That works for me too. Can you explain the syntax? I just want to make sure I know what's going on.

**Comment by jennybc** [comment]
Here I might do one of these ways:

```
gather(cases, "year", "n", starts_with("201"))
gather(cases, "year", "n", matches("201[0-9]{1}"))
```

**Comment by jennybc** [comment]
More full demo of what's going on:

``` r
library(EDAWR)
cases
#>   country  2011  2012  2013
#> 1      FR  7000  6900  7000
#> 2      DE  5800  6000  6200
#> 3      US 15000 14000 13000
grep("^201", names(cases), value = TRUE)
#> [1] "2011" "2012" "2013"
gather(cases, "year", "n", starts_with("201"))
#>   country year     n
#> 1      FR 2011  7000
#> 2      DE 2011  5800
#> 3      US 2011 15000
#> 4      FR 2012  6900
#> 5      DE 2012  6000
#> 6      US 2012 14000
#> 7      FR 2013  7000
#> 8      DE 2013  6200
#> 9      US 2013 13000
grep("^201[0-9]{1}", names(cases), value = TRUE)
#> [1] "2011" "2012" "2013"
gather(cases, "year", "n", matches("201[0-9]{1}"))
#>   country year     n
#> 1      FR 2011  7000
#> 2      DE 2011  5800
#> 3      US 2011 15000
#> 4      FR 2012  6900
#> 5      DE 2012  6000
#> 6      US 2012 14000
#> 7      FR 2013  7000
#> 8      DE 2013  6200
#> 9      US 2013 13000
```

I want to describe the variables to be gathered in a way that I can understand it 6 months from now. So I like to do something based on names, not column numbers. So I use regular expressions to describe I want the variables that are named after years. Regular expressions are one of those topics at the start of STAT 547M that I think most of you will want to know more about.

**Comment by hamid-omid** [comment]
By using "-" I'm excluding that column. I made a typo in last comment. It should be like:

gather(cases, "year", "n", -country)

Actually, I'm wondering why my last code gives the correct result! ( gather(cases, "year", "n", -country,-2011, -2012,-2013) ) @jennybc

**Comment by molliejmcdowell** [comment]
great, thanks Jenny! I understand that syntax.

**Comment by jennybc** [comment]
@hamid-omid Yeah, good question! I suspect it's like so: `-country` has the desired result, i.e. dropping `country`. And then `-2011`, etc. is requesting removal of variables 2011, 2012 and 2013, in the column number sense. Which don't exist. Which therefore has no effect? So you get right result for wrong reasons.
