### ISSUE TITLE
using the tidy function with outputs from lmrob()?

### ISSUE THREAD

**Issue by JoeyBernhardt** [STAT545-UBC/Discussion#162]
I'm trying to compare model fits using lm and lmrob. I'm able to use broom to tidy my lm outputs but not lmrob. 

Has anyone tried to tidy the outputs from lmrob() using the broom package? From the broom documentation it looks like you can use it for S3 objects from lm, glm etc., but not lmrob (from robustbase, which I used as per Jenny's suggestion). Does anyone have any ideas for work arounds...or maybe I'm missing something?

Thanks!

**Comment by bdacunha** [comment]
Hi Joey,

Sorry I'm not answering your questions, but I'm working too with lm and lmrob... just wanted to know if you found any major differences in the fittings. I haven't so far. When I applied both to gdpPercap they look pretty much the same. 

Brenda

**Comment by ksamuk** [comment]
Good question! Looks like `tidy` doesn't have a method for `lmrob` objects. You can get pretty close with `summary(lm_rob)$coefficients`.

e.g.
```
lm_rob <- lmrob(lifeExp ~ year, data = gapminder)

> summary(lm_rob)$coefficients
Estimate  Std. Error   t value     Pr(>|t|)
(Intercept) -633.1150208 38.84764243 -16.29739 1.333777e-55
year           0.3500189  0.01961893  17.84088 2.111442e-65
```

And then do some mild massaging to get it to play nice with the `tidy` output.

**Comment by JoeyBernhardt** [comment]
Hey Brenda,

I'm actually not using the gapminder data...but my fish dataset (which you might remember from my homework you reviewed--btw, thanks for that!).

But, in short, I see some very small differences in the estimated parameters from the two approaches. These are summaries for the two model fits, the first using the lmrob, and second just lm. You can see that they are pretty similar. Hopefully that helps!

>   knitr::kable(lmrob.table, align = 'c', format = 'markdown', digits = 4)


|              | Estimate | Std. Error | t value | Pr(>&#124;t&#124;) |  2.5 %  | 97.5 %  |
|:-------------|:--------:|:----------:|:-------:|:------------------:|:-------:|:-------:|
|(Intercept)   |  3.9781  |   0.1824   | 21.8142 |       0.0000       | 3.6181  | 4.3381  |
|log(max_size) | -0.2328  |   0.0720   | -3.2328 |       0.0015       | -0.3750 | -0.0906 |
>   knitr::kable(lm.table, align = 'c', format = 'markdown', digits = 4)


|              | Estimate | Std. Error | t value | Pr(>&#124;t&#124;) |  2.5 %  | 97.5 %  |
|:-------------|:--------:|:----------:|:-------:|:------------------:|:-------:|:-------:|
|(Intercept)   |  4.0459  |   0.1188   | 34.0685 |         0          | 3.8115  | 4.2804  |
|log(max_size) | -0.2296  |   0.0439   | -5.2269 |         0          | -0.3163 | -0.1429 |

**Comment by JoeyBernhardt** [comment]
by the way, the way I would reach a conclusion from model fits is by looking at two things: 1. what is the slope estimate? and 2. do the confidence intervals on that slope estimate overlap 0? You can see from the tables above that in both cases the 95% confidence intervals do NOT overlap 0, which tells me that max_size has a negative effect on my response variable.

**Comment by JoeyBernhardt** [comment]
great, thanks @ksamuk !

**Comment by jennybc** [comment]
Sounds like `broom` does not have a built-in tidier for `lmrob` output. It's possibly you could fool it with some class funny business.... But it probably means you need to write your own function for extracting the fit info you want into a data.frame. And stick that function inside `do()`.
