### ISSUE TITLE
If the output of a function is a plot, how to use dplyr::do()?

### ISSUE THREAD

**Issue by SarahQiong** [STAT545-UBC/Discussion#163]
I want to interpolating cubic spline in my assignment.  I know we should use ggplot2, but cubic spline is hard to fit in ggplot2, so I first want to use base R to test if my function works. Here is my function:
```{r}
cubic_fit <- function(data){
    the_fit <- spline(data$year~data$lifeExp)
    plot(data$lifeExp,data$year,xlab="lifeExp" ,ylab="year")
    lines(the_fit, col="red")
```
It works well when I test it on just one country,
```{r}
only_china <- gapminder %>% filter(country=="China")
cubic_fit(only_china)
```
Then I want to test it on several countries, par(mfrow) in R base allows you divide the  plotting region into different pieces, but it can't work. 
```{r}
par(mfrow=c(2,2))
gapminder %>% filter(country %in% c("China", "France", "America", "Canada"))%>% do(cubic_fit(.))
```
Does anyone know how to do this? I just want to have a try on different type of output of a function. Thanks:)

**Comment by SarahQiong** [comment]
Actually, I think the function can work, I can get the results in R script. The Error says: Results are not data frames, execution halted. What could I do?

**Comment by cheny19** [comment]
`gapminder %>% filter(country %in% c("China", "France", "America", "Canada"))` returns one data frame, instead of four. If you want to draw four plots, you need four data frames. `gapminder %>% filter(country %in% c("China", "France", "America", "Canada")) %>% group_by(country) %>% do(cubic_fit())` will give you the plot you want. 

To suppress the error "Results are not data frames at positions: 1, 2, 3", you need to add an return statement to your function. Something like `setNames(data.frame(the_fit), c("intercept", "slope"))` to make sure the return value is a data frame.

By the way, there is no country called "America" in gapminder, it should be "United States".

**Comment by SarahQiong** [comment]
Thanks for your reminding, I noticed the misspelling. The output of my function is a plot, so I don't know how to add a data frame return value. I also added `group_by`, same error shows as:  Results are not data frames

**Comment by SarahQiong** [comment]
I tried 
```{r}
cubic_fit <- function(data){
  the_fit <- spline(data$year~data$lifeExp)
  plot(data$lifeExp,data$year,xlab="lifeExp" ,ylab="year")
  lines(the_fit, col="red")
}
par(mfrow=c(2,2))
gapminder %>% filter(country %in% c("China", "France", "United States", "Canada"))%>% group_by(country) %>% do(cubic_fit(.))
```
in R script, the Error says:Results are not data frames at positions: 1, 2, 3, 4, but even there's an error, the plots show on the screen. How to do this correctly in a chunk? Seems like there's some solution on this [website](http://yihui.name/knitr/demo/output/), but hard for me to read

**Comment by cheny19** [comment]
Just add the line `setNames(data.frame(the_fit), c("intercept", "slope"))` to your function. The value of the last line of a function will be it's return value. So your function would be:
```{r}
cubic_fit <- function(data){
    the_fit <- spline(data$year~data$lifeExp)
    plot(data$lifeExp,data$year,xlab="lifeExp" ,ylab="year")
    lines(the_fit, col="red")
    setNames(data.frame(the_fit), c("intercept", "slope"))
}
```

**Comment by SarahQiong** [comment]
@cheny19 There's still an error, but at least it works. Thanks a lot

**Comment by jennybc** [comment]
Here's how someone uses the `dplyr::do()` structure to work with plots and fake an animation:

https://gist.github.com/jeroenooms/fa60515cd84dd1ce6e61

**Comment by cheny19** [comment]
I just ran it again and there is no error message. Could you show me your script and your error message?

**Comment by SarahQiong** [comment]
@cheny19  I ran it again, this time there's no error message. Thank you so much:)
