### ISSUE TITLE
problems with do(), my functions and the gapminder data

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#164]
I have these two functions that, when applied to the gapminder data, won't work. They work for individual countries, but not for the whole set. First I thought the problem was with lmrob(), but the other function works with the regular lm() and I get no output... so I'm thinking it's not about lmrob() but with me doing something wrong.

Here are the functions:

For the residuals:

le_max_resid <- function(dat, offset = 1952) {
  the_fit1 <- lm(gdpPercap ~ I(year - offset), dat)
  x <- max(abs(resid(the_fit1)))
  y <- setNames(data.frame(t(x)), c("max_residual"))
  y
  }
le_max_resid(gapminder %>% filter(country == "Peru"))

Until here it's fine, but:

resid_1 <- gapminder %>%
  group_by(country) %>% 
  do(test = le_max_resid(.))

this won't work

The other function is:
le_diff <- function(dat, offset = 1952) {
  the_fit <- lm(gdpPercap ~ I(year - offset), dat)
  the_robust <- lmrob(gdpPercap ~ I(year - offset), dat)
  x <- coef(the_fit) - coef(the_robust)
  x <- setNames(data.frame(t(x)), c("intercept_diff", "slope_diff"))
  x
  }
le_diff(gapminder %>% filter(country == "Peru"))

this also works until here, but:

diff_1 <- gapminder %>%
  group_by(country) %>% 
  do(test=le_diff(.))

this one doesn't work...

Any suggestions?

Thanks!

**Comment by ksamuk** [comment]
I think in the case of your function, you can omit 'test=' from do, and just make it `do(le_max_resid(.)) `

So:

```R
library(dplyr)
library(robustbase)
library(gapminder)

le_max_resid <- function(dat, offset = 1952) {
	the_fit1 <- lm(gdpPercap ~ I(year - offset), dat)
	x <- max(abs(resid(the_fit1)))
	y <- setNames(data.frame(t(x)), c("max_residual"))
	y
}
le_max_resid(gapminder %>% filter(country == "Peru"))


resid_1 <- gapminder %>%
group_by(country) %>% 
do(le_max_resid(.)) 
```

And we get:
```
Source: local data frame [142 x 2]
Groups: country [142]

       country max_residual
        (fctr)        (dbl)
1  Afghanistan     184.0218
2      Albania    1438.6527
3      Algeria    1158.4317
4       Angola    1829.5458
5    Argentina    2111.1755
6    Australia    2716.3448
7      Austria    1013.8378
8      Bahrain    4032.0132
9   Bangladesh     284.8422
10     Belgium    1198.6454
..         ...          ...

```

**Comment by ksamuk** [comment]
Just a follow up. I think you can omit the 'var_name = function(.)' specification if your function returns an object of class 'data.frame'. Otherwise, e.g. if your function returns a vector of length 1 like `mean()`, you need to specify a new column name.

**Comment by bdacunha** [comment]
Thanks Kieran

I tried this but something must be wrong with my R because I get no output at all... not an error, nothing.. the function just runs but won't return anything

**Comment by bdacunha** [comment]
Thanks Kieran!
