### ISSUE TITLE
question about do() function

### ISSUE THREAD

**Issue by AriaGuo** [STAT545-UBC/Discussion#165]
@jennybc 

I have a quick question:
When I copy the class note and try to fun the following codes in my Rstudio:

>fits <- gapminder %>% 
  group_by(country, continent) %>%
  do(fit = lm(lifeExp ~ I(year - 1952), .))
>fits

I get a different result from the class notes:

Source: local data frame [142 x 3]
Groups: <by row>

       country continent     fit
        (fctr)    (fctr)          (chr)
1  Afghanistan      Asia <S3:lm>
2      Albania    Europe <S3:lm>
3      Algeria    Africa <S3:lm>
4       Angola    Africa <S3:lm>
5    Argentina  Americas <S3:lm>
6    Australia   Oceania <S3:lm>
7      Austria    Europe <S3:lm>
8      Bahrain      Asia <S3:lm>
9   Bangladesh      Asia <S3:lm>
10     Belgium    Europe <S3:lm>
..         ...       ...     ...

Apparently "fit" is a list, but why it indicated "(chr)" in the result under "fit" column?

Thank you for explaining!

**Comment by jennybc** [comment]
I don't know! I get list.

``` r
library(gapminder)
library(dplyr)

fits <- gapminder %>% 
  group_by(country, continent) %>%
  do(fit = lm(lifeExp ~ I(year - 1952), .))
fits
#> Source: local data frame [142 x 3]
#> Groups: <by row>
#> 
#>        country continent     fit
#>         (fctr)    (fctr)  (list)
#> 1  Afghanistan      Asia <S3:lm>
#> 2      Albania    Europe <S3:lm>
#> 3      Algeria    Africa <S3:lm>
#> 4       Angola    Africa <S3:lm>
#> 5    Argentina  Americas <S3:lm>
#> 6    Australia   Oceania <S3:lm>
#> 7      Austria    Europe <S3:lm>
#> 8      Bahrain      Asia <S3:lm>
#> 9   Bangladesh      Asia <S3:lm>
#> 10     Belgium    Europe <S3:lm>
#> ..         ...       ...     ...
```

That's weird. Maybe you should re-start R or RStudio or re-install `dplyr`?
