### ISSUE TITLE
How can we compute AIC value for Robust Regression?

### ISSUE THREAD

**Issue by RashedHUBC** [STAT545-UBC/Discussion#167]
I tried to compare the goodness of fit for linear regression model (`lm()`) and robust regression (`lmrob()`). Unfortunately I can't find the AIC value from `lmrob()`. I can get results using

`ls_aic <- function(dat, offset = 1952) {
  lm_fit <- lm(lifeExp ~ I(year - offset), dat)
  AIClm <- AIC(lm_fit)
  setNames(data.frame(t(AIClm)), "AIC value")
}
ls_aic(gapminder %>% filter(country == "Zimbabwe"))'

but the following is not working

`rob_aic <- function(dat, offset = 1952) {
  rob_fit <- lmrob(lifeExp ~ I(year - offset), dat)
  AICrob <- AIC(lmrob)
  setNames(data.frame(t(AICrob)), "AIC value")
}
rob_aic(gapminder %>% filter(country == "Zimbabwe"))'

Can anyone give any suggestion?

**Comment by jennybc** [comment]
I think you have stumbled into something that borders on a research topic. Here's a related, unanswered AFAICT, question on R-help from 2011:

http://r.789695.n4.nabble.com/AIC-for-robust-regression-td3426655.html

I think, for these models, you are fine using simple funcional form (linear or quadratic), easily accessible fitting criteria (least squares via `lm()` and robust methods bia `robustbase::lmrob()`, and residual analysis for investigating fit. If you wanted to look at AIC, you'd have to stay within linear models, e.g. polynomials of different degree, but I'd be surprised if there's much of a story there.

**Comment by RashedHUBC** [comment]
I got it @jennybc . Thanks.
