### ISSUE TITLE
Issues with RStudio

### ISSUE THREAD

**Issue by jillguerra** [STAT545-UBC/Discussion#168]
Hi, 
Perhaps a simple solution, but I'm having trouble with a few things in RStudio. First, when I clear the Environment and then quit R I am used to the environment staying cleared. However, in the last few days I keep having the same objects and values appear upon restart even if they haven't been used in days...
![image](https://cloud.githubusercontent.com/assets/8070891/10548486/f78029d2-73ef-11e5-912a-d335a2cfacbf.png)

I'm not sure if it is related, but my Rmd files are not changing colour in the chunks like normal..

See this...
![image](https://cloud.githubusercontent.com/assets/8070891/10548507/19e7de3e-73f0-11e5-9f01-c323cdd31d7a.png)

Versus this older file...
![image](https://cloud.githubusercontent.com/assets/8070891/10548513/29a1d802-73f0-11e5-8bd9-3956256d6d00.png)

Also perhaps related..I can't put in a break here as usual..
![image](https://cloud.githubusercontent.com/assets/8070891/10548522/44d39502-73f0-11e5-9f61-cff74e6764af.png)

I'm not sure what I could have done for all these things to start malfunctioning at once. Any thoughts?

**Comment by ksamuk** [comment]
For the first issue, have a look at these settings:

![menu](https://cloud.githubusercontent.com/assets/8412607/10548935/e83a0936-73f2-11e5-9182-90358423c05c.png)

For the second issue, did you perhaps accidentally change the the file extensions from .Rmd to something else? Can't see from the screen shot.

**Comment by jennybc** [comment]
It can't hurt to re-install RStudio Preview.

**Comment by jillguerra** [comment]
Great. First issue solve. 
Second issue has been solved as well..It reverts to normal depending on how many dashes are under the 'Developing and Testing my New Function' line. 

![image](https://cloud.githubusercontent.com/assets/8070891/10549587/d4ae9702-73f6-11e5-87f5-6049accf9996.png)

Thanks for the help!
