### ISSUE TITLE
'filter' gives only 12 observations

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#169]
Hi there
I have a dataframe 'extrSlope' with 6 observations and 3 variables- each observation for a distinct country, slope and intercept. 

When I try using the country names in extrSlope to filter gapminder data, instead of getting all 12 observations for each country (total of 72 observations), I get only 2 per country ( total of 12 observations)

extrSlopedet <- gapminder %>% filter(country ==extrSlope$country)
Any explanations/suggestions to fix this ? 

Thanks a lot!

**Comment by ksamuk** [comment]
You'd need to use %in% for that, e.g.

filter(country %in% levels(extrSlope$country))

worked example:

```R
set.seed(10)
country_subset_names <- sample(levels(gapminder$country), 3)

gapminder_sub <- gapminder %>%
	filter(country %in% country_subset_names)
```

**Comment by Poush87** [comment]
Thanks Kieran. 
For some reason, the levels in extrSlope$country still remain 142 although there are 6 countries in extrSlope. 
I tried filter(country %in% extrSlope$country) without using levels, which seemed to work.

**Comment by ksamuk** [comment]
Right, that makes sense! I should have said `unique` in my example if anything. Factors will 'remember' their levels even if you subtract out all instances of the level.

**Comment by jennybc** [comment]
That's what the bit about `droplevels()` was about in class yesterday. :smile:
