### ISSUE TITLE
SHA clipboard icon is gone?!!

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#170]
I remember there was a SHA clipboard icon. But it is gone now?!! Is that correct?

**Comment by Poush87** [comment]
I couldn't find it either but then the anti-clockwise symbol on the top-right for 'Browse commits' led me to the SHA clipboard.

**Comment by cathyxijuan** [comment]
close@170

**Comment by cathyxijuan** [comment]
close #170

**Comment by jennybc** [comment]
I've learned that my clipboard icons disappeared at some point because I no longer had Flash or Flash was not current (I use Safari), so this could be a browser issue.

**Comment by gjahesh** [comment]
That's right,I used an older version of Firefox and had the same issue,Chrome however seems to be Ok.
