### ISSUE TITLE
Using Own Data for HW3

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#173]
Hi Jenny,

I am finally starting to look at my own dataset and
made a nice clean data.frame out of it.

I am looking into
differential protein expression in response to different stresses. I have
~ 2,000 proteins that have been found in my samples. This results in
different ratios (Treatment/Control) per Strain (2 strains used),
Treatment (3 treatments + control), cellular fraction (2: soluble,
insoluble cell fraction).

Here is a link to a very brief rmd
file in my github repo so you can haveÂ  a tiny glance at the data:

https://github.com/STAT545-UBC/anna_hippmann/blob/master/Anna_ProteomicData.md

I thought of trying to give R a shot and maybe even trying to
write a tiny function for it such as spitting out the mean , median,
quantiles of the UP regulated proteins in the different treatments. 

Cheers
Anna

**Comment by jennybc** [comment]
Will you take the text above and open the issue on your own repo? Also, we're talking about HW04, I think?

**Comment by ahippman** [comment]
uupsi. yes and yes. sorry!
