### ISSUE TITLE
scaling up function to all countries

### ISSUE THREAD

**Issue by molliejmcdowell** [STAT545-UBC/Discussion#174]
Hi,
I have a working function for finding the largest residual of life expectancy for a country...

maxresidualfunction <- function(mycountry){
  gtbl <- tbl_df(gapminder)
  mydata <- gtbl %>% filter(country == mycountry) %>% select(year, lifeExp)
  myfit <- lm(lifeExp ~ I(year - 1952), mydata)
  absresiduals <- abs(myfit$residuals)
  mydataplusresiduals <- cbind(mydata, absresiduals)
  arrangedataplusresiduals <- arrange(mydataplusresiduals, desc(absresiduals))
  maxresidual <- head(arrangedataplusresiduals, n=1) %>% select(year, absresiduals)
  return(maxresidual)
}

I'm not sure if that's totally an efficient way of doing it, because it seems like other folks have very short functions, so if anyone has suggestions for making it more concise (or if my problem for scaling up lies within), I'm totally open to that.

Anyway, it works for a country:

maxresidualfunction("Canada")
  year absresiduals
1 1972    0.3812308

But then I try to scale up to all countries...

maxresidualfunctionall <- gtbl %>% group_by(country) %>% do(maxresidualfunction(.))
 Error: comparison of these types is not implemented 
In addition: Warning message:
In eval(substitute(expr), envir, enclos) :
  Incompatible methods ("Ops.factor", "Ops.data.frame") for "=="

Any ideas about what I'm doing wrong? Or how to make my function better in general?

thank you!

**Comment by oganm** [comment]
The point of `do` is not to pass a single variable to a function but the entire subset of the table. Your function attempts to do the subsetting of the data itself by taking a character output.

`gtbl %>% group_by(country) %>% do(maxresidualfunction(.))` while doing this what you input to the function are subsets of `gtbl` separated into countries. So the reason for the error is the same as the error you'd get if you ran the following:
```
gtbl %>% filter(country==Canada) %>% maxresidualfunction
```

**Comment by jennybc** [comment]
Things can be much shorter:

``` r
library(gapminder)
library(dplyr)
library(broom)
gap_aug <- gapminder %>%
  group_by(country) %>%
  do(augment(lm(lifeExp ~ I(year - 1952), .)))
head(gap_aug)
#> Source: local data frame [6 x 10]
#> Groups: country [1]
#> 
#>       country lifeExp I.year...1952.  .fitted   .se.fit      .resid
#>        (fctr)   (dbl)          (dbl)    (dbl)     (dbl)       (dbl)
#> 1 Afghanistan  28.801              0 29.90729 0.6639995 -1.10629487
#> 2 Afghanistan  30.332              5 31.28394 0.5799442 -0.95193823
#> 3 Afghanistan  31.997             10 32.66058 0.5026799 -0.66358159
#> 4 Afghanistan  34.020             15 34.03722 0.4358337 -0.01722494
#> 5 Afghanistan  36.088             20 35.41387 0.3848726  0.67413170
#> 6 Afghanistan  38.438             25 36.79051 0.3566719  1.64748834
#> Variables not shown: .hat (dbl), .sigma (dbl), .cooksd (dbl), .std.resid
#>   (dbl)
gap_aug %>%
  summarise(max_resid = max(abs(.resid)))
#> Source: local data frame [142 x 2]
#> 
#>        country max_resid
#>         (fctr)     (dbl)
#> 1  Afghanistan 1.6868450
#> 2      Albania 3.9991282
#> 3      Algeria 2.4992354
#> 4       Angola 2.1228497
#> 5    Argentina 0.5520221
#> 6    Australia 1.0249883
#> 7      Austria 0.6716154
#> 8      Bahrain 2.8271282
#> 9   Bangladesh 1.6657564
#> 10     Belgium 0.6336154
#> ..         ...       ...
```

The `augment()` function from the `broom` package will take a fitted linear model and give you back a data.frame with one row per original observation, plus other observation-level stuff, including the **residuals**. Then you can ask for the max for each country via `summarize()` -- the "grouped by country" property propagates to the augmented model output.

Your function is doing alot of computation within it that is best accomplished outside and that is redundant with stuff already done elsewhere. The task of dividing `gtbl` into mini data.frames by country and then submitting each to a function is precisely what `group_by(country) %>% do(...)` does. So you don't want to re-create `gtbl` inside the function, nor do you need to do the filtering for a specific country.

The rest of your function looks ok, although the `select()` statements are not necessary. One strong point: it is a really good idea to do stuff "by hand" sometimes / at first, so it's great you are doing so. Maybe it would be worthwhile to tweak your function and compare it's output to some version of mine, which uses `broom::augment()`. And keep tweaking until they agree. Trying to match the output of a "gold standard" for a specific case can be a nice way to check how your own development is going.
