### ISSUE TITLE
Assigning a default for an argument

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#175]
My function may not be sophisticated, but if it works it will be so amazing!!! (OK, maybe just amazing for me in my own little world, but that's fine with me)

I have several numeric vectors in my data.frame.
My function will summarize one verctor and spit out a nice object with its mean, max, min etc based on a `dplyr::group_by` command. 

The basic function seems to be working. Now I want to be able to probe different variables. Hence, I want to make the variable an argument with the default value being the variable `Average`.

With `Average` it works. Both if I specify the variable or if I don;t use it. But if I try to use a different numeric variable it doesn;t work. :rotating_light:  Any idea why this is? Do I need to specify the argument `variable` somewhere else?

Here is my function so far:

```{r myfunction,eval=TRUE}
a 
Summary_per_Treatment_mod03 <- function(x, variable = x$Average, na.rm=TRUE) {
  if(!is.data.frame(x)){
    stop("Sorry, you will need to provide a data.frame as input!\n",
         "You have provided an object of class: ", class(x))
  }
  if(!is.numeric(variable)){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n", 
          "The variable you want to query is of class: ", class(variable))
  }
  return (x %>% 
  group_by(Ratio.type) %>% 
  summarise(length (variable), min(variable), max(variable), mean(variable), median(variable)))
}
```

Now I tried to make it more general so I can paste it here and one can re-run it:
```{r foo-df, eval=TRUE}
df <- as.data.frame(df)
is.data.frame(df)
df$a <- as.factor(df$a)
foo(df)
foo(df, b)
foo(df, c)
foo <- function(x, variable = x$b, na.rm=TRUE) {
  if(!is.data.frame(x)){
    stop("Sorry, you will need to provide a data.frame as input!\n",
         "You have provided an object of class: ", class(x))
  }
  if(!is.numeric(variable)){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n", 
         "The variable you want to query is of class: ", class(variable))
  }
  return (x %>% 
            group_by(a) %>% 
            summarise(length (variable), min(variable), max(variable), mean(variable), median(variable)))
}
```
and with this one it works!!! I dont know why!
I checked my `variables` and `str()` it... I don't know what's wrong

If you want to can have a direct look at my function development in my [repo](https://github.com/STAT545-UBC/anna_hippmann/blob/master/HW04_a_MyFirstOwnFunction_Works.md#IssueStart) ... I even put a link under **Overview** called "Issue", which takes you directly down to the area I am talking about within subsection of 4c) Breaking the Function.

Any help appreciated. :)

Thanks
Anna

**Comment by jennybc** [comment]
This will be short -- getting kids ready for school!

``` r
library(gapminder)
library(dplyr)

jfun <- function(df, variable = "pop", na.rm=TRUE) {
  if(!is.data.frame(df)){
    stop("Sorry, you will need to provide a data.frame as input!\n",
         "You have provided an object of class: ", class(df))
  }
  if(!is.numeric(df[[variable]])){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n",
         "The variable you want to query is of class: ", class(df))
  }
  df %>%
    group_by(continent) %>%
    summarise_each_(funs(length, min, max, mean, median), variable)
}
jfun(gapminder)
#> Source: local data frame [5 x 6]
#> 
#>   continent length     min        max     mean   median
#>      (fctr)  (int)   (dbl)      (dbl)    (dbl)    (dbl)
#> 1    Africa    624   60011  135031164  9916003  4579311
#> 2  Americas    300  662850  301139947 24504795  6227510
#> 3      Asia    396  120447 1318683096 77038722 14530830
#> 4    Europe    360  147962   82400996 17169765  8551125
#> 5   Oceania     24 1994794   20434176  8874672  6403492
jfun(gapminder, "gdpPercap")
#> Source: local data frame [5 x 6]
#> 
#>   continent length        min       max      mean    median
#>      (fctr)  (int)      (dbl)     (dbl)     (dbl)     (dbl)
#> 1    Africa    624   241.1659  21951.21  2193.755  1192.138
#> 2  Americas    300  1201.6372  42951.65  7136.110  5465.510
#> 3      Asia    396   331.0000 113523.13  7902.150  2646.787
#> 4    Europe    360   973.5332  49357.19 14469.476 12081.749
#> 5   Oceania     24 10039.5956  34435.37 18621.609 17983.304
jfun(gapminder, "lifeExp")
#> Source: local data frame [5 x 6]
#> 
#>   continent length    min    max     mean  median
#>      (fctr)  (int)  (dbl)  (dbl)    (dbl)   (dbl)
#> 1    Africa    624 23.599 76.442 48.86533 47.7920
#> 2  Americas    300 37.579 80.653 64.65874 67.0480
#> 3      Asia    396 28.801 82.603 60.06490 61.7915
#> 4    Europe    360 43.585 81.757 71.90369 72.2410
#> 5   Oceania     24 69.120 81.235 74.32621 73.6650
```

Two main things:

  * As I alluded to in the [bit about programming around other people's functions](http://stat545-ubc.github.io/block025_lm-poly.html), if you can find a version of a function that uses *standard evaluation* (SE), life is better. Luckily, all the `dplyr` verbs have such companion functions, i.e. for `summarise()` there is `summarise_()`.
  * Also, you want to apply a bunch of summarizing functions to a single variable, so I took the liberty of switching over to `summarize_each()`, which is convenient. Then also used the SE version of it = `summarize_each_()`.

**Comment by jennybc** [comment]
Also, I give you a B+ on asking the question in a way I can answer it. I can tell you made a real effort to put up code I could run or modify. The thing that would elevate from B+ to A is the use of `gapminder` or `iris` or some dataset I have access to. But still, good work asking your question! This is a skill worth learning.

**Comment by ahippman** [comment]
Thanks for shortening the code and the links!

I modified it to fit my dataset (see bolt parts of function), but somehow it still doesn;t work. I also tried it with gapminder and there the switching of the variables works like a charm (I wanted to rule out that it has something to do with my RStudio etc., I also reopened RStudio for the same purpose). 

jfun**_average** <- function(df, variable = **"Average"**, na.rm=TRUE) {
  if(!is.data.frame(df)){
    stop("Sorry, you will need to provide a data.frame as input!\n",
         "You have provided an object of class: ", class(df))
  }
  if(!is.numeric(df[[variable]])){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n",
         "The variable you want to query is of class: ", class(df))
  }
  df %>%
    group_by(**Ratio.type**) %>%
    summarise_each_(funs(length, min, max, mean, median), variable)
}

All of this leads me to believe that it has to do with my dataset / my particular variables. However, when I `str()` and `glimpse()` my dataset, it tells me they (variable `Average`, as well as the other potential variable `RatioA`, `RatioB` and `RatioC` are the same flavour:

 ``` {r str, eval=TRUE}
 **str(lowCu)** #nope, still RatioA, B, C and Average are all the same flavour: "num"
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1161 obs. of  14 variables:
 $ TO1005.original_Row     : int  2 5 6 8 9 10 11 12 14 17 ...
 $ TO1005.orig.Row.LongForm: int  2 5 6 8 9 10 11 12 14 17 ...
 $ Strain                  : Factor w/ 1 level "1005": 1 1 1 1 1 1 1 1 1 1 ...
 $ Ratio.type              : Factor w/ 6 levels "lowCu","lowFe ",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ fraction                : Factor w/ 2 levels "Insol","Sol": 1 1 1 1 1 1 1 1 1 1 ...
 $ Diff.Expr               : Factor w/ 1 level "UP": 1 1 1 1 1 1 1 1 1 1 ...
**$ RatioA**                  : num  0.983 1.336 2.525 1.563 2.082 ...
**$ RatioB**                 : num  1.041 1.008 0.909 0.794 NA ...
**$ RatioC**                : num  1.086 1.005 0.901 0.753 NA ...
 **$ Average**               : num  1.04 1.12 1.45 1.04 2.08 ...
$ z.test                  : num  0.109 0.145 0.205 0.445 NA ...
 $ Annotation_Combined     : chr  "kegg_desc: PSAF; PSAF, photosystem I reaction center subunit; K02694 photosystem I subunit III; KO_desc: photosystem I subunit "| __truncated__ "kegg_desc: rplK; 50S ribosomal protein L11; K02867 large subunit ribosomal protein L11; KO_desc: large subunit ribosomal protei"| __truncated__ "kegg_desc: RK1; RK1, ribosomal protein 1; KO_desc: ; Pfam_desc: Ribosomal protein L1p/L10e family; Fasta_header:  50S ribosomal"| __truncated__ "kegg_desc: RR2; RR2, ribosomal protein 2; KO_desc: ; Pfam_desc: Ribosomal protein S2; Fasta_header:  30S ribosomal protein S2 ("| __truncated__ ...
 $ KO                      : chr  "K02694" "K02867" "" "" ...
 $ GO_terms                : chr  "0009522||0009538||0015979" "0000315||0003735||0005840||0006412||0022625" "0000311||0003735||0006412||0022625" "0000314||0003735||0005622||0005840||0006412||0022627" ...
> 
```

If you have **any** idea from just looking at it, what I might want out check out/test further, I will gladly do it. Otherwise, I will just use the function for now with a hardwired use of variable "Average" and will come to the office hours to ponder together with the TAs. I am at my wits end (whatever that might say about my wits)

**just one more question**:
in regards to the second error message
``` {r error01, eval=TRUE}
  if(!is.numeric(df[[variable]])){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n",
         "The variable you want to query is of class: ", **class(df)**)
  }
```
I changed it to.
``` {r error02, eval=TRUE}
 if(!is.numeric(df[[variable]])){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n",
         "The variable you want to query is of class: ", **class(df[[variable]])**)
  }
```
this way it tells me the variable class in the error message. Hope, that's OK.

**Comment by ahippman** [comment]
And... next time I will have an example using `gapminder`! :)

**Comment by ahippman** [comment]
Now I "CLOSED" this issue by accident! It's not closed though.

**Comment by jennybc** [comment]
What error message do you get?

**Comment by ahippman** [comment]
That's the funny thing: I do not get an error message but the table I get has NAs and no values in it.
Here is the function when it works on the assigned variable `Average` (and it also works when I don't specify the `argument` "variable", but call the function with default value, i.e. 
Summary_per_Treatment_mod04 (lowCu):
``` {r good output, eval=TRUE}
 Summary_per_Treatment_mod04 (lowCu,  variable="Average") #works!
Source: local data frame [1 x 6]

  Ratio.type length      min    max    mean median
      (fctr)  (int)    (dbl)  (dbl)   (dbl)  (dbl)
1      lowCu   1161 1.000253 8.2847 1.35132 1.2444
```
SO, now I want to look at different numerical variable `RatioA`:
``` {r badoutput, eval=TRUE}
> Summary_per_Treatment_mod04 (lowCu, variable="RatioA")
Source: local data frame [1 x 6]

  Ratio.type length   min   max  mean median
      (fctr)  (int) (dbl) (dbl) (dbl)  (lgl)
1      lowCu   1161    NA    NA    NA     NA
```
No error message, just unuseful NAs

**Comment by ahippman** [comment]
Just so you don't have to scroll UP and DOWN, here is the `str()` of my data.frame "lowCu"

 ``` {r str, eval=TRUE}
 **str(lowCu)** #nope, still RatioA, B, C and Average are all the same flavour: "num"
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1161 obs. of  14 variables:
 $ TO1005.original_Row     : int  2 5 6 8 9 10 11 12 14 17 ...
 $ TO1005.orig.Row.LongForm: int  2 5 6 8 9 10 11 12 14 17 ...
 $ Strain                  : Factor w/ 1 level "1005": 1 1 1 1 1 1 1 1 1 1 ...
 $ Ratio.type              : Factor w/ 6 levels "lowCu","lowFe ",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ fraction                : Factor w/ 2 levels "Insol","Sol": 1 1 1 1 1 1 1 1 1 1 ...
 $ Diff.Expr               : Factor w/ 1 level "UP": 1 1 1 1 1 1 1 1 1 1 ...
**$ RatioA**                  : num  0.983 1.336 2.525 1.563 2.082 ...
**$ RatioB**                 : num  1.041 1.008 0.909 0.794 NA ...
**$ RatioC**                : num  1.086 1.005 0.901 0.753 NA ...
 **$ Average**               : num  1.04 1.12 1.45 1.04 2.08 ...
$ z.test                  : num  0.109 0.145 0.205 0.445 NA ...
 $ Annotation_Combined     : chr  "kegg_desc: PSAF; PSAF, photosystem I reaction center subunit; K02694 photosystem I subunit III; KO_desc: photosystem I subunit "| __truncated__ "kegg_desc: rplK; 50S ribosomal protein L11; K02867 large subunit ribosomal protein L11; KO_desc: large subunit ribosomal protei"| __truncated__ "kegg_desc: RK1; RK1, ribosomal protein 1; KO_desc: ; Pfam_desc: Ribosomal protein L1p/L10e family; Fasta_header:  50S ribosomal"| __truncated__ "kegg_desc: RR2; RR2, ribosomal protein 2; KO_desc: ; Pfam_desc: Ribosomal protein S2; Fasta_header:  30S ribosomal protein S2 ("| __truncated__ ...
 $ KO                      : chr  "K02694" "K02867" "" "" ...
 $ GO_terms                : chr  "0009522||0009538||0015979" "0000315||0003735||0005840||0006412||0022625" "0000311||0003735||0006412||0022625" "0000314||0003735||0005622||0005840||0006412||0022627" ...
> 
```

**Comment by jennybc** [comment]
Perhaps you have `NA`s in those variables and have not specified how you want `NA`s to be handled. And the default is to propagate? What happens if you just take the, e.g., min max median etc. of one of those variables without your function?

**Comment by ahippman** [comment]
But I did specify the `na.rm = TRUE `. Exactly because I thought this might be the culprit. And it seems to be the culprit, as:
```{r narm, eval=TRUE}
> mean(lowCu$Average)  # works
[1] 1.35132
> mean(lowCu$RatioA) #doesn't work
[1] NA
> mean(lowCu$RatioA, na.rm = TRUE) #works now as na.rm=TRUE is set
[1] 1.357935
> 
```
So maybe I have to specify na.rm=TRUE somewhere else? It is specified in the function already
``` {r 02, eval=TRUE}
> Summry_per_Trtmnt(lowCu, "Average") # works
Source: local data frame [1 x 6]

  Ratio.type length      min    max    mean median
      (fctr)  (int)    (dbl)  (dbl)   (dbl)  (dbl)
1      lowCu   1161 1.000253 8.2847 1.35132 1.2444


> Summry_per_Trtmnt(lowCu, "RatioA") # doesn;t work, even thought na.rm is supplied in the default arguments
Source: local data frame [1 x 6]

  Ratio.type length   min   max  mean median
      (fctr)  (int) (dbl) (dbl) (dbl)  (lgl)
1      lowCu   1161    NA    NA    NA     NA


> Summry_per_Trtmnt(lowCu, "RatioA", na.rm=TRUE) #doesnt' work, even thought I even specified na.rm=TRUE right there
Source: local data frame [1 x 6]

  Ratio.type length   min   max  mean median
      (fctr)  (int) (dbl) (dbl) (dbl)  (lgl)
1      lowCu   1161    NA    NA    NA     NA
```

weirrd, isn't it?

**Comment by jennybc** [comment]
Sure you have an argument for `na.rm = TRUE` in the function definition, but it's not getting passed down into the functions like `mean()`, `min()`, etc. So it has no effect.

**Comment by ahippman** [comment]
OK, so I need to specify it down in the actual function under 
``` {r sh, eval=TRUE}
 df %>%
    group_by(continent) %>%
    summarise_each_(funs(length, min, max, mean, median), variable)
```
I'll try and report back! :)

**Comment by ahippman** [comment]
Almost there!!! 
This works now for the `mean()`, `min()` etc:

```{r na.rm, eval=TRUE}
Summary_per_Treatment_mod05 <- function(x, variable = "Average", na.rm=TRUE) {
  if(!is.data.frame(x)){
    stop("Sorry, you will need to provide a data.frame as input!\n",
         "You have provided an object of class: ", class(x))
  }
  if(!is.numeric(x[[variable]])){
    stop("Sorry, the variable you want to have summarized, needs to be numeric!\n",
         "The variable you want to query is of class: ", class(x[[variable]]))
  }
  x %>%
    group_by(Ratio.type) %>%
    summarise_each_(funs(length, min(.,na.rm=TRUE), max(.,na.rm=TRUE), mean (.,na.rm=TRUE), median(.,na.rm=TRUE)), variable)
}
```
BUT... just need to find a solution for `length()` so it will omit to use NAs... I tried to investigate other functions, such as `count`, or `dplyr::n` but these are not suitable for one reason or another
I found this work around for length():
  ``` {r bla, eval=TRUE}
  # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }
```

but looks a bit creepy to me.

**Comment by jennybc** [comment]
`length2()` does not look creepy to me.

I wonder if there's a more compact way to send `na.rm = TRUE` through to all those functions? But I can't investigate that right now.

**Comment by ahippman** [comment]
I tried a couple of ways but so far no luck... will keep on trying.., but right now I am on _part 2 of HW4_ to actually use the Function :)
`length2()` within my function hasn't worked so far either... tried it several ways
