### ISSUE TITLE
Problem with do()

### ISSUE THREAD

**Issue by farnushfarhadi** [STAT545-UBC/Discussion#176]
Hi, 

I have wrote a function `fitModels(models , data , y , x)` which gets 4 arguments as input. I want to test this function with the `gapminder` data. I group the gapminder data based on three countries and then try to use `do()` but I do not know how to pass different arguments of the `fitModels()` to `do()`. 
I searched a lot and checked the class notes but all the functions that I have seen in `do()` examples, have only one argument. 

```{r}
data <- gtbl %>% 
filter (country == c("Iran" , "United States" ,"Zambia")) %>% 
group_by(country) %>%
#do (fitModels(models=c("lm" , "rlm" , "pm") , y="lifeExp" , x="year"))
# I gussed the function would identify the data input that's why I did not pass it to fitModels
```

Can you edit the line in comments so that it works?

thanks! :)

**Comment by jennybc** [comment]
I think you either need to absorb those different models into `fitModels()`, i.e. hard-wire them, or you'll have to look at other ways of iterating, which can handle marching through multiple inputs at once. But I think it's a little late to start the second option. So I suggest you do option 1 = just fit all models or fit exactly one model inside `do()`.

**Comment by farnushfarhadi** [comment]
I think I did not get it... how can I pass different arguments of `fitModels()` by option 1?

**Comment by farnushfarhadi** [comment]
my function looks like this: 

```{r}
fitModels <- function(models , data , y , x)
{
# body
}
```

The problem is I need to pass `models`, `y` and `x` to `do(fitModels(..)). Is there any way I can do this?

Thanks.

**Comment by sho-87** [comment]
Given the way you've set up the function (specifically: models=c("lm" , "rlm" , "pm")), you need some way of iterating through that object to determine which models to fit. This is going to take more work.

Without the option of iterating within the function, you would just pass your data to the function, then within the function use that data to fit your lm, rlm, pm models manually

it might look something like:

myFunc <- function(data){
lmFit <- lm(data)
rlmFit <- rlm(data)
pmFit <- pm(data)

items_of_interest <- whatever it is from the models that you're interested in

return(items_of_interest)
}

I believe this is the hardwiring option @jennybc is referring to

**Comment by farnushfarhadi** [comment]
I got your answer. thanks. But I want to iterate the `fitModels()` function for my data. I think I have not clarified my question well.. 

This is my data **`D`** for different countries: 
         country continent  year lifeExp       pop gdpPercap
          (fctr)    (fctr) (dbl)   (dbl)     (dbl)     (dbl)
1           Iran      Asia  1952  44.869  17272000  3035.326
2           Iran      Asia  1967  52.469  26538000  5906.732
3           Iran      Asia  1982  59.620  43072751  7608.335
4           Iran      Asia  1997  68.042  63327987  8263.590
5  United States  Americas  1957  69.490 171984000 14847.127
6  United States  Americas  1972  71.340 209896000 21806.036
7  United States  Americas  1987  75.020 242803533 29884.350
8  United States  Americas  2002  77.310 287675526 39097.100
9         Zambia    Africa  1962  46.023   3421000  1452.726
10        Zambia    Africa  1977  51.386   5216550  1588.688
11        Zambia    Africa  1992  46.100   8381163  1210.885
12        Zambia    Africa  2007  42.384  11746035  1271.212

I want to iterate my `fitModels()` function for three different countries in **`D`**.
So, I thought I can do iterating with `dplyr::do()` function. But it seems that it only iterates functions with one input argument. My function has 4 input arguments though. So, can I use `do()`? or I need another function? 

Thanks

**Comment by jennybc** [comment]
To easily work with `do()` as we're currently using it, your function needs to look more like this:

```
fitModels <- function(data , y , x)
{
model1_output <- rlm(...)
model2_output <- lmrob(...)
model3_output <- lm(...)
list(model1_output, model2_output, model3_output)
}
```

But then you'll have something rather complicated to work with at the end. Unless you go ahead and do the extraction of, e.g., estimated coefficients inside and return a nice simple data.frame. That might be an attractive option.

You could also do one model at the time, and take full advantage of `broom`'s tidiers, for example. Then column or row bind the results or use joins to bring them together. Then do your comparisons. That sounds easier to me at this point.

**Comment by jennybc** [comment]
You want the iterating by country to happen via `gapminder %>% group_by(country %>% do()` by the way.

**Comment by farnushfarhadi** [comment]
Thank you Jenny.

**Comment by farnushfarhadi** [comment]
@jennybc Hi again 

I understand the code style of your suggested `fitModels()` function. Well, the question is how do you pass arguments `x` and `y` to the `fitModels` by using `do()`? According to my experience with `apply()`, my guess is something like t:

```{r}
do (data , fitModels , x = .. , y = ... )
```

Is it possible to pass multiple arguments by using `do()`?
Thank you.

**Comment by npjc** [comment]
@farnushfarhadi `do(data, fitModels(x, y))`

**Comment by jennybc** [comment]
I think I answered that here:

http://stat545-ubc.github.io/block025_lm-poly.html
