### ISSUE TITLE
How to call data right from github?

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#177]
In my homework 2, the TA left a comment saying: "In the
future, using read.delim("https://raw.githubusercontent.com/STAT545-UBC/cathy_zhang/master/Homework%202/project_data.csv?token=AGDrOkPouN8ujsZpJCQ87ai-AQ2YNWYvks5WIZEDwA%3D%3D",
sep=",") will allow knitr to run successfully without others having to
download your data."

My question is how to create/find that link the TA has given me?

**Comment by dchiu911** [comment]
Hi Cathy,

You can find the link by pressing the **Raw** button [here](https://github.com/STAT545-UBC/cathy_zhang/blob/master/Homework%202/project_data.csv). However, I would advise not to read from the raw link since your data is coming from a private repo (yours), and the token at the end of the URL will change periodically.

**Comment by jennybc** [comment]
Can one of you clarify exactly what this is about? I think it's reading data that's in the repo itself? If true, I'd expect the read to look much simpler, i.e. to read from local:

```
read.delim("project_data.csv")
```

Only @cathyxijuan or someone else with a clone of the repo would knit. It feels like you are discussing as if knitting is being done on GitHub or when someone views the file, but that is not the case.

Let me know if I'm confused and not answering the right question.

**Comment by cathyxijuan** [comment]
That is what I did. But this way you need to download my data  and then run my code? I think the TA is suggesting a way to get the  right  from the github?

But I think Derek is right. The raw link changes. That raw link already changed, I think.

**Comment by jennybc** [comment]
I'm satisfied if we adopt this convention: if something is in the repo, then the "right" way to get it is to clone the repo and run the script / render the Rmd as the original author did. Even if that never happens, I think it's OK for the code to assume that workflow.
