### ISSUE TITLE
How do you make a ggplot plot taller?

### ISSUE THREAD

**Issue by yksugi** [STAT545-UBC/Discussion#178]
I'm seeing something like this, and I'm wondering how I can make the plot taller?
![image](https://cloud.githubusercontent.com/assets/1811651/10615471/da87fe2c-7714-11e5-8262-3980e56a254b.png)

**Comment by cheny19** [comment]
If you want to save your plot to a file and make it taller, you can specify the height and width in ggsave.
`ggsave(file=p1, width=2, height=4)`  

If you want your plot to be taller in your markdown and html file, you can specify them in the r chunk.
`{r fig.width=7, fig.height=4}`
