### ISSUE TITLE
Contour Plots

### ISSUE THREAD

**Issue by jeffbone** [STAT545-UBC/Discussion#179]
Hi Guys,

I'm wondering if anyone knows a good R package for making contour plots (does ggplot have an option?). 

I'm looking for the most flexible possible. Most of the ones I've found require a specified grid of points to be used for plotting but this isn't ideal for my purpose. 

Any recommendations would be appreciated!

**Comment by ksamuk** [comment]
Not sure how flexible it is , but in ggplot, its `geom_density2d()`:

```R
library(gapminder)
library(ggplot)
gapminder %>%
	ggplot(aes(x = lifeExp, y = gdpPercap)) +
	geom_density2d()
```

**Comment by ksamuk** [comment]
Might want to look at the stat_density2d page here as well:

http://docs.ggplot2.org/current/stat_density2d.html
