### ISSUE TITLE
Problem with commiting latest revision SHA (clipboard icon not availabe)

### ISSUE THREAD

**Issue by gjahesh** [STAT545-UBC/Discussion#181]
Hi there,

I had difficulty submitting my latest homework revision , I basically can't copy the revision SHA  number on clipboard, there's no icon available. WHen I click on the latest commit number, it directs me only to the changes I made recently, not to the actual files in the repo.

Thanks,
Golnaz

**Comment by dchiu911** [comment]
Hi Golnaz,

Do you see the clipboard icons on [this page](https://github.com/STAT545-UBC/golnaz_jahesh/commits/master)?

Yes, clicking on a commit number will show you the changes you made for that commit. To get to the changed file at that point in time, you can click **View**.

**Comment by gjahesh** [comment]
Hi Derek,

Yes, I did see the latest commits there, Thanks for your help.

Golnaz
