### ISSUE TITLE
Tip: Writing Beautiful and Readable R Code

### ISSUE THREAD

**Issue by ksamuk** [STAT545-UBC/Discussion#182]
Hey @STAT545-UBC/2015_students !

Now that you're all becoming more proficient in R, I just wanted to remind everyone about STYLE when coding. The primary reason to care about style is readability. Styling your code correctly can make it much easier to read and understand. And, because YOU are main person who will be reading your code later, you are doing yourself a big favour by styling your code in a readable fashion!

First, this is the generally accepted style guide for R:
http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml

Hadley Wickham made a nicer version here (with some extra jazz):
http://adv-r.had.co.nz/Style.html

The big one that many people are not doing is spacing around binary operators, e.g. `my_function(parameter=x+y)` vs. `my_function(parameter = x + y)`.

I want to also make another suggestion (and maybe @jennybc and @STAT545-UBC/2015_ta can weigh in on this as well): consider using line breaks / indents (with two spaces, not a tab) when using the pipe operator, when "stacking" ggplot elements, and when functions have big lists of parameters.

Consider the following two blocks of identical R code.

```R
gapminder%>%filter(continent=="Asia")%>%group_by(year)%>%summarise(mean_pop=mean(pop))%>%ggplot(aes(x=year,y=mean_pop))+geom_point()+geom_line()+theme_bw()
```

```R
gapminder %>%
   filter(continent == "Asia") %>%
   group_by(year) %>%
   summarise(mean_pop = mean(pop)) %>%
     ggplot(aes(x = year, y = mean_pop)) +
     geom_point() +
     geom_line() +
     theme_bw()
```

I think its pretty obvious that the latter is easier to read, edit, and will quickly understand (especially when coming back later). I am also a fan of breaking up the pipe by function (processing vs. plotting) using indents, but that is more of a personal preference. 

Anyway, many of you are doing this already, but I thought I'd just remind everyone of how much nicer it is to read properly styled code!

**Comment by siyunw** [comment]
This reminds me that it is also suggested one could check spelling in R studio before push to github,  I was wondering how I could do a spell check of my rmd file before knit to HTML, any recommendation on doing it through an option in r or there is a package?

**Comment by MagdaPrice** [comment]
In the R toolbar under "Edit" there is an option for "Check spelling", give it a try.

**Comment by min110** [comment]
Thanks for the information ! just wondering if there is a default setting or short cut for the spaces around the operator? slightly painful to type them all the way...

**Comment by ksamuk** [comment]
@min110, while I would recommend just getting in the habit (is it painful to type spaces between words when writing normal text?),  there is the package called [formatR](https://cran.r-project.org/web/packages/formatR/index.html) that automagically cleans up a .R file (including spacing around binary operators).

**Comment by jennybc** [comment]
RStudio should be doing most of this indenting, etc. for you! And whenever things get wonky, just use *Code > Reindent lines*. The keyboard shortcut for this is burned into my fingers.

**Comment by dchiu911** [comment]
Agreed, I use `Ctrl/Cmd + I` very often too

**Comment by mstrimas** [comment]
While we're on this topic, I have the "insert spaces for tabs" option checked with a tab width of 2, but RStudio always inserts 4 spaces. This has been persisting for many months, over several updates. Overall, not a huge deal, but I would rather my indentation be at 2 spaces than 4. Anyone else experience this?

**Comment by jennybc** [comment]
@mstrimas Agree with you that you want 2 spaces inserted for tabs. You need to be thorough and check global and project options. Sounds like you might have a project w/ an older setting "grandfathered in"? Look under *Tools* for both Project and Global options.

**Comment by mstrimas** [comment]
Yep, that fixed it, thanks!

**Comment by npjc** [comment]
People have great comments here, I thought I'd provide something I wish past me would make present me do *all the time*:

> Do the codes then read it and ask yourself, can I make this easier to read? can it be more english like? Could I understand this if I was sleep deprived and had an undisclosed number of fizzy pops?
