### ISSUE TITLE
Efficient solution to Yosemite update and github disappearing from R studio?

### ISSUE THREAD

**Issue by SarahUBC** [STAT545-UBC/Discussion#183]
Hi all. Last night I updated my mac to the new Yosemite OS. I opened one of my R studio projects this morning, and the tab for github was gone. I tried creating a new project, but there was no option for connecting to github in the process of creating the new project.

What's an efficient way to restore this connection to github? Should I simply go through everything from our class' GitHub config page again?
http://stat545-ubc.github.io/git00_index.html

Thanks,
Sarah

**Comment by jennybc** [comment]
I would look into two things:

  * Where is Git? Is that location on your PATH?
  * Did Xcode get updated and are you using system Git? So you may need to accept new terms. See #123.

**Comment by cathyxijuan** [comment]
Did you update the system to EI Captian? Git disappeared when I updated the system. I had to reinstall everything.

**Comment by SarahUBC** [comment]
Yeah, I updated to El Cap last night. 
I just updated XQuartz (which I think is connected to Xcode). Still no github in R Studio. 

I'll look into locating GIT and seeing if that location is on my PATH.

Then I may reinstall R studio and perhaps other git-related apps. 

~S

**Comment by SarahUBC** [comment]
I reinstalled R, reinstalled git, followed the instructions from the class website and I'm still having trouble. 

I can change a new readme file that I create on github's web interface via shell that I accessed through RStudio.  

When I create a new project in R Studio and try to use version control, it tells me git was not detected on the system path. I went to RStudio preferences, Git/SVN and the git executable is:
/usr/bin/git

and SVN executable is:
/usr/bin/svn

When I click browse, there is a git unix executable in this location. 

I have restarted RStudio and my computer a few times now. 

What am I missing?

It was working so well before this El Cap update :(

**Comment by ksamuk** [comment]
Can you try directly opening Xcode and see if it asks you to accept new terms? Just type 'Xcode' into spotlight.

**Comment by SarahUBC** [comment]
Here's my screen shot when I type Xcode in spotlight. 
![screen shot 2015-10-23 at 2 41 42 pm](https://cloud.githubusercontent.com/assets/14287586/10705644/4ad4639c-7994-11e5-8245-6392ad5d729d.png)

**Comment by SarahUBC** [comment]
Should I download and install this?
http://xcode-mac.en.softonic.com/mac

**Comment by cathyxijuan** [comment]
I think it doesn't have anything to do with the new terms. From what I know, the EI Cap moved the files around, and somehow the computer can no longer locate git.. But I installed git through Hebrew; I am not too sure if that makes a difference. 
I had to go to recovery mode to fix the problem. I found some online instruction that tells me how to do it: 
- Reboot into Recovery mode (Hold Cmd+R on boot) & access the Terminal.
- In that terminal run: csrutil disable
- Reboot back into OS X
- Open your Terminal application and execute:


  sudo mkdir /usr/local && sudo chflags norestricted /usr/local && sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local



- Reboot back into Recovery Mode & access the Terminal again.
- In that terminal execute: csrutil enable
- Reboot back into OS X & you'll be able to write to /usr/local & install Homebrew.｀

I copied and pasted these instructions into my evernote but now I can't find the original website with the instruction. I will try to look for it for you. 

After I fixed the thing with the recovery mode, I reinstalled Homebrew and the missing package.. And it worked..

**Comment by ksamuk** [comment]
OK, looks like Xcode is not installed (which it doesn't need to be anyway). So that is not your problem, at least :smile:

**Comment by cathyxijuan** [comment]
Ok here is the website that helped me.
http://digitizor.com/2015/10/01/fix-homebrew-permissions-osx-el-capitan/

**Comment by SarahUBC** [comment]
But what if I don't use homebrew?

~Sarah

**Comment by cathyxijuan** [comment]
Can you try this?

http://superuser.com/questions/980679/git-on-command-line-no-longer-works-on-el-capitan

**Comment by jennybc** [comment]
There's alot of noise here re: homebrew and Xcode, which it seems like @SarahUBC does not have.

In the shell, with working directory set to a git repo, such as your STAT 545 one, what happens when you do this:

```
git status
git config --global --list
```

**Comment by SarahUBC** [comment]
I've been modifying lots of files in prep for a committee meeting, which
you see in my

git status:

Sarahs-MacBook-Pro-2:wf_ce sarahklain$ git status

On branch master

Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:

  (use "git add/rm <file>..." to update what will be committed)

  (use "git checkout -- <file>..." to discard changes in working directory)


modified:   Value_st_exploration.Rmd

modified:   Value_st_exploration.html

modified:   Value_st_exploration.md

modified:   Value_st_exploration_files/figure-html/unnamed-chunk-6-1.png

modified:   Value_st_exploration_files/figure-html/unnamed-chunk-7-1.png

modified:   Value_st_exploration_files/figure-html/unnamed-chunk-8-1.png

modified:   Value_st_exploration_files/figure-html/unnamed-chunk-9-1.png

modified:   WF_data_exploration.Rmd

deleted:    fig_MT_mean_val_st_box.pdf

deleted:    fig_MT_mean_val_st_jit_vio.pdf

deleted:    fig_MT_val_st_box.pdf

deleted:    fig_age.pdf

deleted:    fig_all_val_st.pdf

deleted:    fig_all_val_st_box.pdf

deleted:    fig_all_val_st_dot.pdf

deleted:    fig_att_w_US.pdf

deleted:    fig_const_st.pdf

deleted:    fig_edu.pdf

deleted:    fig_employ.pdf

deleted:    fig_first_st.pdf

deleted:    fig_freq_rec.pdf

deleted:    fig_income.pdf

deleted:    fig_oper.pdf

deleted:    fig_pol.pdf

deleted:    fig_race.pdf

deleted:    fig_wf_rec.pdf

deleted:    gender.png

deleted:    income_fig.pdf


Untracked files:

  (use "git add <file>..." to include in what will be committed)


.pdf

CE2/

Mapping.Rmd

Value_st_exploration_files/figure-html/unnamed-chunk-10-1.png

Value_st_exploration_files/figure-html/unnamed-chunk-11-1.png

Value_st_exploration_files/figure-html/unnamed-chunk-12-1.png

Value_st_exploration_files/figure-html/unnamed-chunk-13-1.png

Value_st_exploration_files/figure-html/unnamed-chunk-14-1.png

Value_st_exploration_files/figure-html/unnamed-chunk-15-1.png

Value_st_exploration_files/figure-html/unnamed-chunk-18-1.png

figs/

figs_demographic/

figs_wf_att/

~$Coded_WF_10_13_2015v2.xlsx


no changes added to commit (use "git add" and/or "git commit -a")

Sarahs-MacBook-Pro-2:wf_ce sarahklain$


Sarahs-MacBook-Pro-2:wf_ce sarahklain$ git config --global --list

filter.media.required=true

filter.media.clean=git media clean %f

filter.media.smudge=git media smudge %f

user.name=SarahUBC

user.email=s.klain@gmail.com

credential.helper=osxkeychain

core.excludesfile=/Users/sarahklain/.gitignore_global

difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"

difftool.sourcetree.path=

mergetool.sourcetree.cmd=/Applications/SourceTree.app/Contents/Resources/opendiff-w.sh
"$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"

mergetool.sourcetree.trustexitcode=true

filter.lfs.clean=git-lfs clean %f

filter.lfs.smudge=git-lfs smudge %f

filter.lfs.required=true

Sarahs-MacBook-Pro-2:wf_ce sarahklain$

**Comment by ksamuk** [comment]
Just to confirm, what does typing `which git` in the shell (anywhere) produce?

**Comment by SarahUBC** [comment]
I installed XCode just to see if I needed this.

I don't develop software! I didn't know I was using it before.

But now git has been restored to my RStudio.

I assume I need this XCode b/c Jenny recommended the RSTudio version that
is for developers rather than standard users?

I hope this saves other people some work. I was hoping to have an analysis
done and a new model up and running in the time it took me to figure this
out!

Thanks for you tips and advice.

Best,
Sarah

**Comment by ksamuk** [comment]
Glad to hear that fixed it! I suspect it fixed it by reinstalling git and reconfiguring the path to correctly point to it. *You shouldn't need Xcode for this all to work*, but I guess that's a one-stop-shop solution!

**Comment by SarahUBC** [comment]
Hold on....
Git hub's working, but I noticed that it took a long time download the
entire XCode package. I restarted RStudio and my computer several times
before I downloaded XCode. Just now, I got notified that XCode completed
its installation process even though RStudio's git has been working for me
for over 30 min. I'm puzzled. Something changed soon after I initiated the
installation of XCode and my github worked within my RStudio again even
before the XCode was fully installed.

At least it all seems to work ok now even if I'm not sure what changed to
make it work.

~S

**Comment by ksamuk** [comment]
Hmm, well Xcode installs a whole suite of tools, so its possible that it finished installing git before everything else. Pretty mysterious though!

**Comment by SarahUBC** [comment]
So.....
When I installed RStudio from here:
https://www.rstudio.com/products/RStudio/#Desktop
Git works.

But I really like the cheatsheets so I download this newer version:
https://www.rstudio.com/products/rstudio/download/preview/

Git does not work with this version, even with the Xcode installed.

~S

**Comment by jennybc** [comment]
Xcode is not necessarily in order to use Git or to use RStudio Preview (which is not aimed at developers *per se*, it's just constantly improving and a little more cutting edge than the released version) or to use them together. Sounds like one of us should sit behind @SarahUBC's computer for a few minutes. RStudio's ability to find Git is very "sticky" and is tied to your PATH. So don't give up on a certain installation / configuration until you've been really careful to restart, log out / log in, etc. of everything that seems relevant. But it is always possible that their algorithm for finding Git is somehow more robust in the released version vs. Preview version.... There's always pain early on with a major OS upgrade 😥

**Comment by ksamuk** [comment]
@SarahUBC because I like fun, I just installed El Capitan. I first tried firing up Rstudio without changing anything else. Everything worked as expected, including the Git integration. Git was sitting in /usr/bin/git, was registered in the system path at that location, and was set to point to there in Rstudio. Makes sense so far.

I then installed the latest RStudio Preview. Sure enough, no Git! :scream: :scream: 

I'm *pretty* sure the cause of this is somehow the new 'rootless' feature of El Capitan. It attempts to prevent things from writing to /usr/bin in general, and also tries to move/alias anything that was previously installed there. 

Anyway, my fix:

1. Re-installed Git. 
2. Checked the path for git by typing 'which git'. It now says /usr/**local**/bin/git. Aha?
3. Changed the git path in Rstudio (preview) to /usr/local/bin/git.
4. Restart Rstudio.
5. :star: :rainbow: It works :rainbow: :star: 

What's not clear to me is why when I first looked, git was /usr/bin/git and functioned as intended. There also now appears to be a git executable in /usr/bin/ **and** /usr/local/bin, which seems odd. Anyway, let me know if this works for you!

**Comment by jennybc** [comment]
Above and beyond @ksamuk!

**Comment by SarahUBC** [comment]
Wow, Kieran, I owe you a beer or something! You're amazing.

Not only can I use El Cap's 100+ newly installed emojis in iMessage, but I
can also use the preview RStudio and Github!

My personal faves are
 🤓 smiling nerd face <-- me right now
and 🤗 aka hug face!

Thank-you.
~Sarah

**Comment by ksamuk** [comment]
@SarahUBC Great, I'm really glad it worked! OS updates can be harrowing :grimacing:
