### ISSUE TITLE
questions about cleaning up the repository

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#185]
I have three questions about cleaning up the repository. 

1) Should we keep the `Rmd` file or not? I am a bit confused about what this sentence for hw5 really meant: "Anything that’s Rmd but that could be md? Convert it." 

2) It says that we should delete the figure files but I thought Jenny said these files may be useful in the future? 

3) Are we not supposed to push all the files in our local computer folder to the github? Wouldn't it be confusing to have some files pushed and some not? At this moment, I have all the files in the folder pushed to github. So I have the `Stat_545_private_repo_for_Cathy_Zhang.Rproj` file pushed to the repository. Should I delete this in the cleanup ? But I guess if I can only delete that in the repository but not in my local computer folder.

**Comment by jennybc** [comment]
If you have a file that is `.Rmd` and yet it contains no R code? Convert it to `.md`. Sometimes I draft something expecting to put code in it, then I never do ... then you might as well make it `.md`. That's all I meant.

Delete figure files **and then re-render the `.Rmd`. Which will recreate the figures your code actually generates. But if you've been fiddling around for 6 weeks, esp. at the start when you weren't as expert, it's possible you've accumulated, commited, and pushed alot of orphan files. This is sort of like cleaning out your closet.

I think it's fine to commit and push `.Rproj`. I usualy do. In general, you can keep something locally but not track it by listing it in `.gitignore`.

**Comment by cathyxijuan** [comment]
Thanks Jenny !! You are very helpful!

**Comment by cathyxijuan** [comment]
closed #185

**Comment by cathyxijuan** [comment]
I have one last question! How about `.gitignore` file? Should I push it to repository?

**Comment by npjc** [comment]
@cathyxijuan People tend to check their .gitignore files into git yes. This is a bit meta but there are cases where it is useful to track the changes of what you (or your collaborators) are choosing to keep out of git.

**Comment by jennybc** [comment]
What @npjc said. Yes, it's more common to see `.gitignore` in the repo than not.

Note you can have a user-level `.gitignore_global` in your home directory and more specific `.gitignore`s within the subdirectories of a repo. The former would, presumably, not be shared with collaborators; the latter might? So, you see, there are lots of different possibilities.

**Comment by farnushfarhadi** [comment]
Hi,

I want to delete a repo 'final_HW2' and then when I navigate to the main page of it, I can not see any **setting** icon. This is how the main page of the repo looks like: 

![screen shot 2015-10-25 at 11 19 02 am](https://cloud.githubusercontent.com/assets/14318045/10717082/e57f7a7c-7b0a-11e5-9265-826f3d345844.png)


[This post](https://help.github.com/articles/deleting-a-repository/) says that there should be a **setting** on the right side of my repo. But as you can see in the photo, I can not see the setting. What should I do?

**Comment by ksamuk** [comment]
Correct me if I'm wrong, but it looks like 'final_hw2' is a folder inside your stat545 repo, and not a separate repo? If you want to delete it, you can delete the folder in your local repo and push the changes.

**Comment by farnushfarhadi** [comment]
You are right. So there is no way that I can delete a sub folder from GitHub?

**Comment by ksamuk** [comment]
Not using the web interface, that I am aware of.

**Comment by daattali** [comment]
I don't think it's possible to remove a directory straight from GitHub, you might have to do it locally and then push the changes.  [There's an open issue about this (unofficial, but it shows that many others have noticed this problem too)](https://github.com/isaacs/github/issues/225)

**Comment by farnushfarhadi** [comment]
@daattali @ksamuk 
Thank you

**Comment by jennybc** [comment]
Recall this is @farnushfarhadi's repo through STAT 545 organization, right? So she doesn't own it. I think that is why "Settings" is not where it usually is.

Let's be clear that the goal is to delete a *directory*, not delete the repo.

Here's how to delete a file on GitHub:

https://help.github.com/articles/deleting-files/

but remember Git is file-oriented. Even if you can delete individual files this way, GitHub (and I think Git itself) will never help you delete a directory. Notice that if you add a directory to a repo locally, it will never show up on GitHub until you have commited and pushed a file that lives within it.

**Comment by farnushfarhadi** [comment]
Thanks Jenny.
