### ISSUE TITLE
How to put graphs side by side ?

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#187]
How to put two graphs side by side like Jenny did in the "Be the boss of factor` page?

**Comment by jennybc** [comment]
I don't have time to link it for you but just go the repo that makes the website and look at the Rmd source.

**Comment by jennybc** [comment]
OK I am not on my phone now. Here's the source:

https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/block014_factors.rmd

And here's a typical chunk with two figures sitting side by side:


    `​``{r killer-chunk-name, fig.show = 'hold', out.width = '49%'}
    ggplot(gcoefs, aes(x = slope, y = country)) + geom_point()
    ggplot(gcoefs, aes(x = slope, y = reorder(country, slope))) +
       geom_point()
    ```

**Comment by cathyxijuan** [comment]
Thanks Jenny! Actually, I already found it. Sorry that I didn't reply you early. I had trouble finding how to read the raw code but later I saw the `Raw` button on the page.
