### ISSUE TITLE
stacked (but not to 100%) barplots?

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#189]
I have a dataset that includes 2 categorical variables S1B3_v16 and S1B3_v17 and want to represent both in the same barplot, as proportions and not counts: 
So far I've got :
q <- ggplot(nss66, aes(x=S1B3_v16, fill= S1B3_v17)) 
q + geom_bar(position ='fill')
But this stacks each bar to 100%. Is there any way to keep them stacked but not to 100%?

Thanks!

**Comment by npjc** [comment]
It's hard to help specifically without a reproducible example to go from BUT i suspect the examples from the `?geom_bar` may come to the rescue.

1. Go through these examples, and make sure you understand what's happening:
```r
# Bar charts are automatically stacked when multiple bars are placed
# at the same location
library(ggplot2)
g <- ggplot(mpg, aes(class))
g + geom_bar(aes(fill = drv)) # defaults to stacking
g + geom_bar(aes(fill = drv), position = "stack") 
g + geom_bar(aes(fill = drv), position = "dodge")
g + geom_bar(aes(fill = drv), position = "fill")
```

2. Compare the shape of your data to that of the data in the example

remember what jenny says:

> 'it is most likely a data shaping problem not a graphing problem'.

**Comment by Poush87** [comment]
Thanks! :)
