### ISSUE TITLE
Using mutate() to create new category variable?

### ISSUE THREAD

**Issue by alex-peterson** [STAT545-UBC/Discussion#190]
This seems like it should be very simple but I am confused.

So I wanted to make a graph that only shows countries in the Americas, and uses colors to distinguish whether these countries are in South, Central (& Caribbean), or North America. 

Since the dataframe doesn't already come with this information, I was going to make a variable called "region," and say "if country is in south america, region = south", the same with "north" and then otherwise call it central america. 

I feel like this is a really common thing to do, and I wanted to do it with %>% and mutate(), but I'm a little confused on the logic syntax for R. Here's what I have so far:

```{r american_lifeExp}
south <- c("Argentina", "Bolivia", "Brazil", "Chile", "Colombia", 
           "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname",
           "Uruguay", "Venezuela")
north <- c("Mexico", "United States", "Canada")

americas <- gapminder %>% 
  filter(continent == "Americas") %>% 
  select(., country, continent, year, lifeExp) %>% 
  mutate(region =  ???? )
```
I've found stuff online about using ifelse(), but it looks like that's only for 2 conditions. Also I guess you can use the "mosaic" package but I wanted to see how you would do it with the tools we already have.

**Comment by cathyxijuan** [comment]
This is a good example where you should use 'recode()'  function to create a new factor based on the old factor! Look up the function in the 'car'  package.  The hw also mentioned it. I used it for a similar situation. It was very easy to use!

**Comment by npjc** [comment]
Just for completeness:

for your use case you can indeed use `ifelse(country %in% north, "north", "south")`. The generalized version of `ifelse()` is achieved with `switch()` (see `?switch`). You usually want to use switch inside a function you use.

**Comment by jennybc** [comment]
`plyr::revalue()` and `plyr::mapvalues()` are also worth considering.

Or you could approach via a join:

http://stat545-ubc.github.io/bit001_dplyr-cheatsheet.html
