### ISSUE TITLE
Two distinct operations on the same data at the same place

### ISSUE THREAD

**Issue by hamid-omid** [STAT545-UBC/Discussion#191]
It might be an easy question, I'm not sure! Is there any way to act two different operations on the same data without recopying. Say I want to str() and ncol() a filtered data, how can I act both of them without recopying the filtering process neither putting the filtered data in a variable?

**Comment by npjc** [comment]
You could write a function!

for example:
```r
myfun < - function(x) {
  list(nrow(x), ncol(x))
}
```

note that `str()` specifically is interesting. What happens when you run this code:
```r
list(str(mtcars))
```

**Comment by hamid-omid** [comment]
That for sure works! I'm wondering if there is a built in way for arbitrary  number of operations?

**Comment by npjc** [comment]
writing a `function` is that general way of combining other functions in any way you please.

I suspect you may be looking for a pipe-idy solution now that I re-read (in the future post some minimal code so we can better help!)

Are you looking for something like this:
```r
library(dplyr)

mtcars %>% 
  filter(cyl == 4) %>% 
  list(ncol(.), nrow(.), colSums(.), rowSums(.), summary(.))

```

**Comment by hamid-omid** [comment]
We could use "with()", I just remembered!

**Comment by hamid-omid** [comment]
Thanks Nicholas, i just saw your comment that is exactly what I needed!

**Comment by jennybc** [comment]
You can also use the "tee" operator from `magrittr` to do two things, not an arbitrary number:

``` r
library(magrittr)

## from the magrittr README
## https://github.com/smbache/magrittr
rnorm(200) %>%
  matrix(ncol = 2) %T>%
  plot() %>% # plot usually does not return anything.
  colSums()
```

![](http://i.imgur.com/cGdS7EN.png)

    #> [1] 2.018382 3.026818

**Comment by min110** [comment]
Thanks, I had same question , but when I try to run :( DATA is my gapminder )
> DATA %>% list(y = nrow(.), z = ncol(.), x = str(.) ) 

the third element which is supposed to respond o str() shows NULL, but I got the whole gapminder data printed too. what happened under hood ? 

Then I tried
> DATA %>% list(y = nrow(.), z = ncol(.), x = str(.), funny = y +z ) # get str() printed, with an error " object 'y' not found".

I do remember for some of the functions , the variables created earlier (in this case like z, x, y) could be used for the computation for the later arguments... 

Thanks !

**Comment by min110** [comment]
@jennybc : for the example of Tee, I thought Tee returns the output on the left , like 
>  1+ 2  %T>% +9 

we get 3, instead of 12. but in the example , how can we get the plot on the right of Tee instead of the whole matrix which is on the left side of "Tee" ? 

Am I  wrong ?

**Comment by jennybc** [comment]
For your first example, modify like so:

``` r
library(gapminder)

gapminder %>%
  {
    list(y = nrow(.), z = ncol(.), x = capture.output(str(.)))
  }
#> $y
#> [1] 1704
#> 
#> $z
#> [1] 6
#> 
#> $x
#> [1] "'data.frame':\t1704 obs. of  6 variables:"                                           
#> [2] " $ country  : Factor w/ 142 levels \"Afghanistan\",..: 1 1 1 1 1 1 1 1 1 1 ..."      
#> [3] " $ continent: Factor w/ 5 levels \"Africa\",\"Americas\",..: 3 3 3 3 3 3 3 3 3 3 ..."
#> [4] " $ year     : num  1952 1957 1962 1967 1972 ..."                                     
#> [5] " $ lifeExp  : num  28.8 30.3 32 34 36.1 ..."                                         
#> [6] " $ pop      : num  8425333 9240934 10267083 11537966 13079460 ..."                   
#> [7] " $ gdpPercap: num  779 821 853 836 740 ..."
```

The curly brackets `{ ... }` are handy when [reusing the `.` placeholder in several places](https://github.com/smbache/magrittr#re-using-the-placeholder-for-attributes).

I surround `str()` with `capture.output()` because `str()` doesn't return anything. It is called for its side effect, which is to print to screen, so this is how to capture it.

**Comment by jennybc** [comment]
I don't follow the second question. The code example is about adding 1, 2, and 9 but the text talks about plotting and a matrix.

**Comment by min110** [comment]
Oh, sorry for the confusing @jennybc 
 my code example `1+ 2 %T>% +9` meant to say, `%T>%` gives us the output on its left instead of right.
But,  in the example 
> library(magrittr)
rnorm(200) %>%
  matrix(ncol = 2) %T>%
  plot() %>% # plot usually does not return anything.
  colSums()

we get sth on the right of %T>% which is a plot , instead of sth on the left which should be a matrix ... 
hope I make it clear now :)

**Comment by jennybc** [comment]
``` r
library(magrittr)
(1 + 2) %T>%
  print() %>% 
  `+`(9)
#> [1] 3
#> [1] 12
```

I've changed your example a bit to make it more illustrative of `%T>%` and to make it work 😃

**Comment by min110** [comment]
Great! I kept using it with a misunderstanding , now all is lear ^_^
Thanks!

**Comment by hamid-omid** [comment]
Thanks @jennybc, I learned a lot hear.
