### ISSUE TITLE
Access to gapminder via googlesheets

### ISSUE THREAD

**Issue by mstrimas** [STAT545-UBC/Discussion#194]
I'm running into an error when trying to read or download data from gapminder using the `googlesheets` packages:  

```
'1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA' %>% 
  gs_key(lookup=F) %>% 
  gs_read(ws=1)
#Authorization will not be used.
#Worksheets feed constructed with public visibility
#Accessing worksheet titled "Data"
#Error in gsheets_GET(this_ws$exportcsv, to_xml = FALSE, use_auth = !ss$is_public) : 
#  Not expecting content-type to be:
#text/html; charset=UTF-8
```

The registration works fine, but reading fails, as does a call to `gs_download()`.  Looking at the seet on GoogleSheets, the download tab says "Coming Soon".  

Is there some way around this? Or, do we have to resort to downloading the Excel file and working with that for the time being?

**Comment by mstrimas** [comment]
Seems I was able to sort of get around this by explicitly giving a range of rows and columns to read:  

```
hiv <- '1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA' %>% 
  gs_key(lookup=F) %>% 
  gs_read(ws=1, range='R1C1:R276C34')
```  

Not the most elegant solution though since it requires manually finding the size of the table.

**Comment by daattali** [comment]
I'm not too familiar with the `googlesheets` package, but to me this look like a bug.

For completeness, URL of web spreadsheet: https://docs.google.com/spreadsheets/d/1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA/pub?gid=0

@jennybc I was able to reproduce - `gs_read()` results in 

```
Error in gsheets_GET(this_ws$exportcsv, to_xml = FALSE, use_auth = !ss$is_public) : 
  Not expecting content-type to be:
text/html; charset=UTF-8
```

Is this a bug or are we both unaware of something?

**Comment by jennybc** [comment]
Yeah, I am puzzling over this right now. Looks like putting you all on this will force me to fix something in `googlesheets`! If you visit the Sheet in the browser first, I think you can drop the `lookup = FALSE` and then I suspect all might be  OK?

Recently I changed something around lookup and auth and it's clear I sort of broke something (or am discovering something that's been broken for a while).

**Comment by daattali** [comment]
A free QA team. 

Running `gs_key() %>% gs_read()` without the `lookup` argument still produces the same error. If you are puzzled as well, I suppose opening an issue on googlesheets would be the next step

**Comment by mstrimas** [comment]
Yes, I added `lookup=FALSE` to fix another problem. It seems that without that `gs_key()` only finds sheets on your Google Sheets home screen. Not sure if that's by design. Regardless, for these gapminder sheets, even visiting them in a browser doesn't put them on the home screen.

**Comment by mstrimas** [comment]
For the time being, this seems to little function is a workaround to avoid having to hard code the number of rows:  

```
gs_read_nocsv <- function(ss, ws=1, ...) {
  this_sheet <- googlesheets:::gs_ws(ss, ws=ws)
  row_extent <- this_sheet$row_extent
  gs_read(ss, ws=ws, range=cell_rows(1:row_extent), ...)
}
hiv <- '1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA' %>% 
  gs_key(lookup=F) %>% 
  gs_read_nocsv(ws='Data')
```

**Comment by jennybc** [comment]
I'm still wondering if the Sheet is set up optimally w/r/t sharing. I don't control that but can ask Dave to change it, once I know specifically what would be best.

The fact that you can only lookup things you've visited in the browser is a Google Docs thing, not something I can workaround. I definitely didn't design that aspect myself!

**Comment by jennybc** [comment]
Wow I misread this at first and thought we were talking about the candy survey!

It sounds like Gapminder has possibly disabled downloading?

Have you tried copying the Sheet to your Drive via `gs_copy()`? Then try reading normally from your copy.

You could also grab the Excel spreadsheet and have some practice with `readxl` which is a good package to know about.

**Comment by daattali** [comment]
@jennybc 

Any reason why `gs_key() %>% gs_read()` fails but `gs_key() %>% gs_read(range = 'R1C1:R276C34')` works? I don't know enough about the code to claim this, but my guess would be that this is a bug that googlesheets can fix since it *can* read the dataset when a range is specified

**Comment by jennybc** [comment]
@daattali Yes I understand the difference in the above. No range specified --> we read via the "exportcsv" link, which perhaps they have disabled? Range specified --> we read via the "cell feed", which is slower but, in this case, appears to be enabled. But I just need to make sure this is still somehow not *my fault*.

**Comment by mstrimas** [comment]
@jennybc 

Copy also appears to be disabled, I get this error:  
```
Error in gdrive_POST(the_url, body = the_body) : 
  client error: (404) Not Found
```

Thanks for the explanation re exportcsv vs cellfeed. Knowing that this issue is easy avoided with:  

```
hiv <- '1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA' %>% 
  gs_key(lookup=F) %>% 
  gs_read_cellfeed %>% 
  gs_reshape_cellfeed
```
