### ISSUE TITLE
when should I break a pipeline? 

### ISSUE THREAD

**Issue by min110** [STAT545-UBC/Discussion#195]
this is a question I had when I play around( DATA is my gapminder) : I cant pass the character vector to filter ()
> DATA %>% 
head(100) %>% 
select(country) %>% 
distinct() %>% 
unlist %>% 
as.character %>% 
filter(.data = DATA, country %in% .)

but when I create a new variable holding the vector (I know this could be done easily by levels()), and pass it to filter(.data = DATA, country %in% variable ), then it works . 

Here , my first question is why I failed without creating a new variable ?
second question is deduced by the first one  : how long should a pipe line be ?  is it okey if I keep adding functions till I get what I want? when should I break a pipeline? 

Thanks!

**Comment by daattali** [comment]
Your pipeline will work if you surround the last statement (the `filter` line) with curly braces

```
DATA %>% 
   head(100) %>% 
   select(country) %>% 
   distinct() %>%  
   unlist %>% 
   as.character %>% 
   {filter(.data = DATA, country %in% .)}
```

The reason why is a bit complex and I won't explain right now, hopefully someone else will chime in and expand.  

In regards to your second question: that's really a matter of personal taste. There are no hard rules, just whatever seems to make sense for your case. It is certainly ok to keep adding functions, that's the entire point of the pipe :) Without the pipe, the above code would look hideous and unreadable, with many many brackets, so with the pipe you can make a whole pipeline that is easy to understand. If your pipeline is getting to be 100 lines long then you could certainly break it up into a few variables along the way where it makes the most sense to have an intermediate variable, but you don't have to.

**Comment by jennybc** [comment]
The curly braces are needed when you don't want to send the `.` placeholder in as the first argument and also when [reusing the `.` placeholder in several places](https://github.com/smbache/magrittr#re-using-the-placeholder-for-attributes).

I don't think really long pipes are a good idea. I usually wrap it up within ?~4? operations?

I know your example was more to pose a pipe question. But I'll also ahead and show I would do similar a bit differently.

``` r
library(gapminder)
library(dplyr)

(my_countries <- gapminder %>% 
  head(100) %>% 
  .$country %>%
  as.character() %>% 
  unique())
#> [1] "Afghanistan" "Albania"     "Algeria"     "Angola"      "Argentina"  
#> [6] "Australia"   "Austria"     "Bahrain"     "Bangladesh"
gapminder %>% 
  filter(country %in% my_countries) %>% 
  as.tbl()
#> Source: local data frame [108 x 6]
#> 
#>        country continent  year lifeExp      pop gdpPercap
#>         (fctr)    (fctr) (dbl)   (dbl)    (dbl)     (dbl)
#> 1  Afghanistan      Asia  1952  28.801  8425333  779.4453
#> 2  Afghanistan      Asia  1957  30.332  9240934  820.8530
#> 3  Afghanistan      Asia  1962  31.997 10267083  853.1007
#> 4  Afghanistan      Asia  1967  34.020 11537966  836.1971
#> 5  Afghanistan      Asia  1972  36.088 13079460  739.9811
#> 6  Afghanistan      Asia  1977  38.438 14880372  786.1134
#> 7  Afghanistan      Asia  1982  39.854 12881816  978.0114
#> 8  Afghanistan      Asia  1987  40.822 13867957  852.3959
#> 9  Afghanistan      Asia  1992  41.674 16317921  649.3414
#> 10 Afghanistan      Asia  1997  41.763 22227415  635.3414
#> ..         ...       ...   ...     ...      ...       ...
```
