### ISSUE TITLE
Add table of content in README

### ISSUE THREAD

**Issue by MaryHe** [STAT545-UBC/Discussion#196]
Hi

I'm not sure if we covered this or not (maybe I forgot). It seems that I do not know how to include a table of contents in my README.md file. Can somebody help me?

Thanks
Mary

**Comment by cathyxijuan** [comment]
If you go to the cheatsheet for Rmarkdown, it has the syntax for making a table. Basically, you need to draw those vertical and horizontal lines.

**Comment by daattali** [comment]
There is no way to automatically create a table of contents in a markdown.  You would have to do it manually.  

Related: If you're using `rmarkdown` to produce an HTML document, then you can set the options to automatically add a table of contents. But if the output from the rmarkdown is a markdown, it will not be able to automatically add it.

Recap:
- .md has no automatic table of contents
- .Rmd -> .HTML can do table of contents
- Rmd -> .md cannot do table of contents

**Comment by MaryHe** [comment]
Oh, ok. Thank you!

**Comment by daattali** [comment]
If that answers your question, you can "close" the issue unless you want it to remain open
