### ISSUE TITLE
How to apply function with the whole data set, if this function has a plot as return value?

### ISSUE THREAD

**Issue by LinaQiu** [STAT545-UBC/Discussion#198]
Hi all,

If I write a function like below(my_plot), and I want to apply this function to the whole data set, what function should I call? I checked this function, d_ply(.data, .variables, .fun, ..., .progress = "none"), as my input would be a data frame, but what I wanted to get as output will be several plots, but still could not make it work... anyone has any suggestions? Thanks.

my_plot <- function(DATA,x="year",y="pop")
{

  fit <- lm(DATA[[y]]~DATA[[x]],DATA)
  a=coef(fit)[2];
  b=coef(fit)[1];
  predictDATA <-  data.frame(x=DATA[[x]],predicted_y=a*DATA[[x]]+b)

  ggplot(DATA)+
  aes_string(x=x,y=y) +
  geom_abline(intercept =b,slope = a,color = "red",alpha=1) +
  geom_point(data=predictDATA, aes(x=x,y=predicted_y), color="red", size=3, shape=1) +
  geom_line() +
  geom_point(size=3) +
  geom_line(alpha=0.6) + 
  scale_x_continuous(breaks = DATA[[x]]) 
}

**Comment by jennybc** [comment]
It seems like you should just call `my_plot(gapminder)` to apply your function to the entire dataset.

I don't understand how you are expecting to get several plots as output from the above function, which returns exactly one plot, by applying the function to the `gapminder` data.frame.

**Comment by LinaQiu** [comment]
Hi Jenny,

Sorry for not expressing it clearly. 

What I am trying to do is to see whether the population in each country grows linearly over years. For example, whether the population of China increases linearly during the period from 1952 to 2007. So I got the data piece for China first (ChinaData–> gapminder %>% filter(country == "China")%>% select(year,pop)), then I called my function my_plot(), which provided a plot to compare the actual population in China with the predicted population we got from our linear model. But now, I am trying to find if there is any function I can use so that I can apply my function, my_plot() to all such pieces of data in gapminder, and get the relevant plots for each country. Is it clear now? Thanks.

**Comment by jennybc** [comment]
That sounds exactly like what we've been doing with `dplyr::group_by() + do()`. We group by country then apply a function within each group.

http://stat545-ubc.github.io/block023_dplyr-do.html

**Comment by LinaQiu** [comment]
Thanks Jenny for the link. Yeah, right. However, I already tried dplyr::group_by+do() before I opened this issue, but it did not work, and the error was: Results are not data frames at positions: 1,2,3. 

So I checked your slides about dplyr::group_by()+do() again, it seems like all the functions we use inside do() get a data frame as their return value. Then I am wondering whether the return value of my function my_plot() is a plot, but not a data frame would be the reason why "gapminder %>% group_by(country) %>% do(my_plot(.))" did not work here? Thanks.

**Comment by jennybc** [comment]
Can you show me your `dplyr::do()` call then? If you don't return data.frame, then you must use a named argument inside.

Here's an example of animation, but I bet you could pull some key ideas from here:

https://gist.github.com/jeroenooms/fa60515cd84dd1ce6e61

**Comment by farnushfarhadi** [comment]
@LinaQiu @jennybc 
Hi 

I think I had the same problem which I asked [here](https://github.com/STAT545-UBC/Discussion/issues/176) in discussion couple of weeks ago. 

In brief, I wrote a function which fitted different models to data based on the user defined dependent and explanatory variables in `gapminder` dataset and plot models on data. Then I wanted to run this function to the `gapminder` which was grouped by `continents` to have different plots as output. But it did not work!

After asking Jenny and reviewing codes from previous sessions of STAT545, I came to conclusion that `do()` is used to apply a **function** iteratively to a dataset only when the **function** returns *data frame*. That's why we could not have our code work properly.

**Comment by farnushfarhadi** [comment]
@LinaQiu did this link Jenny gave you worked for you?

**Comment by jennybc** [comment]
@farnushfarhadi 

No, that's not true. `do()` can be used even when the function you are applying iteratively to each group returns something other than a data frame. But then you have to name it and it will require a bit more effort to handle downstream.

**Comment by farnushfarhadi** [comment]
@jennybc Thank you for correcting me! Now I can try to fix my problem again.

**Comment by LinaQiu** [comment]
Hi @farnushfarhadi , sorry I was super busy the whole last week, got assignment due and quizzes everyday, so I did not have time to check the link @jennybc provided me yet. Thus I can't tell you whether this link fix my problem or not, but I think it probably would be able to fix our problem, as Jenny has said. And I probably will check this link in these two days, let's keep in touch and see if any of us can use that link to solve our problem. 

Besides, thanks @jennybc , for that link you provided me. 
Cheers,
Lina

**Comment by LinaQiu** [comment]
@jennybc 
And here is how I used `group_by`+`do()`:
`gapminder %>% group_by(country) %>% do(my_plot(.))`

I will check your link later, sorry for not able to check it earlier. Still have a due tomorrow. But I just want to make a double check that I am using `dplyr::do()` in a right way first.

Thanks.
Lina

**Comment by farnushfarhadi** [comment]
Hi Lina, 

I am also busy to check the link. I will let you know when I have chance to look for it. 
I think your code is correct. (I just figured it out that you already fixed your x and y arguments in your function which is different from my code) 

Thanks,
Farnush
