### ISSUE TITLE
plyr interference with dplyr 

### ISSUE THREAD

**Issue by hamid-omid** [STAT545-UBC/Discussion#199]
I was trying to run this code

```{r}
gapminder_tbl %>% 
  select(gdpPercap,continent) %>% 
  group_by(continent) %>% 
  summarize(mean_gdpPercap=mean(gdpPercap),standard_deviation=sd(gdpPercap)) %>% 
ggplot(aes(x=continent,y=standard_deviation/mean_gdpPercap))+
  geom_histogram(stat="identity",fill="bisque4")+
  xlab("Continent")+
  ylab("Coefficient of Variation for GDP per Cap")
```
and was receiving this error:
```{r}
Error in eval(expr, envir, enclos) : object 'continent' not found
```
I figured out that plyr is interfering with dplyr and I  should detach plyr before running the code and load it again afterwards. Is there any better way to deal with this issue?

**Comment by jennybc** [comment]
If you load both, always load `plyr` first, then `dplyr`. I imagine you would have gotten a big warning message about that? It fixes the problem (I ran it both ways -- replicated your error and then ran in cleanly).

**Comment by daattali** [comment]
@hamid-omid 

To expand on what Jenny said - try loading up a new R session. Do `library(dplyr)` followed by `library(plyr)`.  You should see this message

```
-------------------------------------------------------------------------------------
You have loaded plyr after dplyr - this is likely to cause problems.
If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
library(plyr); library(dplyr)
-------------------------------------------------------------------------------------
```

Loading packages often results in a lot of text being output to the console and it's very natural to just ignore it, but sometimes these messages are actually informative, like in this case.

**Comment by hamid-omid** [comment]
@jennybc, @daattali   I was supposed to get the warning but I had turned the warnings off! Thanks, it solve the problem. Now I'm facing problem in using "ddply" and I need to recall "plyr" again. I'm trying to use "do()" instead though.

Thanks for the help!
