### ISSUE TITLE
Using y-axis limits with geom_bar

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#200]
I have the following code working for a barplot: 
flev %>% filter(levels=="cases") %>% ggplot(aes(x=dataset, y=observations)) + geom_bar(stat="identity") 

When I add y-axis limits to the plot, I end up with a blank plot with no bars. Any way to get around/explain this? 

Thanks a lot! :)

**Comment by eacton** [comment]
Hi @Poush87,
It depends on how you are adding y-axis limits to your plot -- check out the differences between these 4 ways to change ylim of a bar plot - my guess is you are doing the second...
https://groups.google.com/forum/?fromgroups#!topic/ggplot2-dev/JGal_9nRzsg

**Comment by oganm** [comment]
An important note if you are using any kind of limit setting: 
If you set axis limits with
```r
scale_x_continuous(limits = c(-1, 1))
````
or
```r
xlim(-1,1)
```

this will cause any points outside the ranges to be completely disregarded. This is most noticable if you are drawing boxplots, violin plots or doing anything with summary statistics.

Using
```r
coord_cartesian(xlim = c(-1,1)) 
```
on the other hand will only set the window size, for all other purposes the points outside the window range will still be there
