### ISSUE TITLE
error when trying to open figure

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#201]
Hello,

I was trying to open a plot that I had previously saved to a file in R,

This is my code, 

```{r}
pimp_my_plot <- ggplot(gapminder, aes(x = reorder(continent, lifeExp), y = lifeExp)) + geom_boxplot(aes(color = continent)) + geom_jitter( aes(color = continent), position = position_jitter(width=0.02), alpha = 0.2) + xlab('Continent') + ylab('Life Expectancy') + ggtitle('Life Expectancy of every continent')

#pimp_my_plot
ggsave('lifeExp_boxplot_pimped.png', pimp_my_plot)
```

 but I get this error when I try to knit:

pandoc.exe: Could not fetch file:///C:/Users/Brenda/Desktop/R/stat_class/brenda_dacunha/lifeExp_boxplot_pimped.png
InvalidUrlException "file:///C:/Users/Brenda/Desktop/R/stat_class/brenda_dacunha/lifeExp_boxplot_pimped.png" "Invalid scheme"
Error: pandoc document conversion failed with error 67
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS hw05.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output hw05.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\Brenda\GOOGLE~1\DOCUME~1\R\WIN-LI~1\3.2\RMARKD~1\rmd\h\DEFAUL~1.HTM" --variable "theme:bootstrap" --include-in-header "C:\Users\Brenda\AppData\Local\Temp\RtmpMXfpdT\rmarkdown-str383044714e3f.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=C:\Users\Brenda\GOOGLE~1\DOCUME~1\R\WIN-LI~1\3.2\RMARKD~1\rmd\h\HIGHLI~1"' had status 67 
Execution halted

What can I do to fix this?

**Comment by eacton** [comment]
@bdacunha 
When you are bringing an image into markdown, you use can use this to get at a local file -- it just has to be outside of a chunk.
 ![lifeExp](lifeExp_boxplot_pimped.png)

**Comment by bdacunha** [comment]
Thanks! I figured it out :)
