### ISSUE TITLE
using reorder for tables gives me an error

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#202]
I know that reorder is not suppose to do anything to a table, but when I try to use it I get an error:

```{r}
max_res <- gapminder %>% group_by(country, reorder(desc(max_residual))) %>% do(le_max_resid(.))
max_res_tbl <- tbl_df(max_res)
max_table <- max_res_tbl %>% 
do(head(., n=10))
knitr::kable(max_table, align = 'c', format = 'markdown')
```

I tried to put the reorder all over, in different places of my code, but it won't work. Maybe it's because of the function I'm using?

**Comment by jennybc** [comment]
Are you trying to reorder a factor or arrange rows of a data.frame? These are different operations.

For the former, use `reorder()`. For the latter, use `dplyr::arrange()`.

`dplyr::group_by()` expects to operate on a factor or something can smells like a factor. Such as `country`.  Get that `reorder(desc(max_residual))` bit out of `group_by()`. And, I suspect, put it in an `arrange()` statement elsewhere.

**Comment by bdacunha** [comment]
I'm also using arrange, but I wanted to compare between the two of them for the homework... is it possible? or should I just leave it as an error?

**Comment by jennybc** [comment]
It's hard for me to help w/o seeing an actual bit of code and exact error message.

But ... `reorder()` only reorders the levels of a factor. You would use it inside, say, `mutate()` to create a new factor variable from an old one or to overwrite an existing factor variable with a near-copy that has different factor level order. `reorder()` cannot appear as a top-level function in your pipeline. It does not operate on a data.frame.

**Comment by bdacunha** [comment]
This is the code for the reorder part:

```{r}
max_res <- gapminder %>% group_by(country) %>% do(le_max_resid(.))
max_res_tbl <- tbl_df(max_res)
max_table <- max_res_tbl %>% 
do(head(., n=10)) %>% 
reorder(desc(max_residual))
knitr::kable(max_table, align = 'c', format = 'markdown')
```

this is the error that I get:
Error in desc(max_residual) : object 'max_residual' not found

The code for the function is:
```{r}
le_max_resid <- function(dat, offset = 1952) {
  if (!is.data.frame(dat))
  stop('I am sorry, but this function only works for data.frame input. \n', 'You have to provide an object of class: ', data.frame(dat))
    the_fit1 <- lm(gdpPercap ~ I(year - offset), dat)
    x <- max(abs(resid(the_fit1)))
    y <- setNames(data.frame(t(x)), c("max_residual"))
    y
}
```

**Comment by jennybc** [comment]
OK. `reorder() does not operator on a data.frame. It operates on a factor. So it can't sit as a top-level call in your pipeline. Here's some code that I think will help get you unstuck.

``` r
library(gapminder)
library(dplyr)
library(broom)

gapminder %>%
  group_by(country) %>%
  do(augment(lm(gdpPercap ~ I(year - 1952), .))) %>% 
  summarize(max_resid = max(abs(.resid))) %>% 
  mutate(country = reorder(country, max_resid)) %>% 
  arrange(desc(country))
#> Source: local data frame [142 x 2]
#> 
#>              country max_resid
#>               (fctr)     (dbl)
#> 1             Kuwait 32135.280
#> 2       Saudi Arabia 14528.192
#> 3              Gabon 10640.821
#> 4              Libya 10116.212
#> 5            Ireland  8846.872
#> 6          Singapore  7903.289
#> 7               Iraq  6827.686
#> 8             Serbia  5911.089
#> 9  Equatorial Guinea  5596.154
#> 10  Hong Kong, China  5424.534
#> ..               ...       ...
```

**Comment by bdacunha** [comment]
thanks Jenny! I'll try this way
