### ISSUE TITLE
Trouble pushing hwk5?

### ISSUE THREAD

**Issue by vedangvyas** [STAT545-UBC/Discussion#203]
Hi all,

For some odd reason, I am having trouble pushing my hwk 5 into my repo. This is the error I get:
To https://github.com/STAT545-UBC/vedang_vyas.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/STAT545-UBC/vedang_vyas.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Is there any way this can be fixed?

**Comment by mstrimas** [comment]
Did you try what it suggests, i.e. pull changes from GitHub, then push

You can pull with the blue down arrow in RStudio

**Comment by jennybc** [comment]
What @mstrimas said.

Pull.

Push.

**Comment by vedangvyas** [comment]
Solved it. Initially I did try to "pull" and then "push". Turns out there was some sort of problem in the files I was pushing; one of them was (I want to say) a duplicate (?!). I ended up just deleting the file, then pulling and pushing and it seems to work. Some of this is still sorcery to me. Thank you for your help!

**Comment by jennybc** [comment]
Git is frustrating. It's true.
