### ISSUE TITLE
Mark homework 5 of jill-guerra

### ISSUE THREAD

**Issue by jillguerra** [STAT545-UBC/Discussion#204]
Hi @jennybc, my homework 5 is now ready!

Link: https://github.com/STAT545-UBC/jill_guerra/blob/master/homework/Homework5.md
Latest commit: 2344c59a219c25fd414d517919d62851651e63d4

**Comment by hamid-omid** [comment]
@jillguerra 
The issue is crested in the wrong directory, I think.
