### ISSUE TITLE
homework 6

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#205]
Unfortunately I had to miss class this morning. Wondering if there was an announcement regarding when the next homework is due, and what it would entail?

I've been through the regex lecture material and the only reference to homework was from last years class. Presumably this year will be slightly different?

**Comment by jennybc** [comment]
There will be no homework 6. Last year it was an optional, unmarked "clean up your repo" activity. I simply merged that into homework 5 this year. So STAT 545 homework is DONE.

**Comment by sho-87** [comment]
Sorry, I should have been clearer. When I say homework 6, I guess I'm actually referring to homework 1 of STAT547

**Comment by jennybc** [comment]
We're working on drafting that. It will cover the topics in the first two weeks, then there will be one per week for 4 self-contained topics. So you have a little breathing room here at the STAT 547 start.

Preview: The first homework of STAT 547 will be "clean up a dataset", where the default is to clean one of the Gapminder spreadsheets from their website. We'll want to see you practice with string wrangling, data tidying, factor management and file I/O.
