### ISSUE TITLE
questions about regular expression 

### ISSUE THREAD

**Issue by min110** [STAT545-UBC/Discussion#206]
1. I am just wondering that if I can abstract `a{3} ` from `aaaaaaaaa`, without starting from the first character in the line but from any position I want? for example aa`aaa`a`aaa`a?
2. can I keep the character used in sep argument ? say when I set sep = ",", I want to keep the` ,`

I tried google but cant get what I want, probably because I dont know how to describe my problem properly :( any help is appreciated . Thanks!

**Comment by oganm** [comment]
Which aaa's are you trying to extract? what are the other strings in the set? why do you want to keep the `,` if it is not actually in the string?

**Comment by ksamuk** [comment]
1. Is pretty tricky, as far as I know. One approach might be "mask" the indexes you want to ignore with a dummy character, e.g. :

```{r}
> string <- "aaaaaaaaaa"
> substr(string, 1, 1) <-"@"
> string
[1] "@aaaaaaaaa"
```
Here's a function that does arbitrary masking:
```{r}
mask_string <- function(string, indexes, mask = "@"){
	indexes <- lapply(indexes, rep, each = 2)
	
	for (i in 1:length(indexes)){
		substr(string, start = indexes[[i]][1], stop = indexes[[i]][2]) <- mask
	}
	string
}
```
You could then go in an extract the matches using `gregexpr()`
```{r}
> string <- "aaaaaaaaaa"
> pattern <- "a{3}"
> string_masked <- mask_string (string, c(1:2, 6, 10))
> string_masked
[1] "@@aaa@aaa@"
> gregexpr(pattern, string_masked)
[[1]]
[1] 3 7
attr(,"match.length")
[1] 3 3
attr(,"useBytes")
[1] TRUE

```

`gregexpr` returns a list: [[1]] contains the indexes (in the string) of the start of the match, and [[2]] contains the length (in characters) of the match.

**Comment by ksamuk** [comment]
2. Sorry, is this referring to `strsplit`? In which case you mean `split = ","`, not `sep = ","`? If so you can just `paste0()` it back in.

```{r}
> string <- "ab, cd, ef, gh"
> split_string <- strsplit(string, split = ",") %>% unlist
> paste0(split_string, ",")
[1] "ab,"  " cd," " ef," " gh,"
```

**Comment by min110** [comment]
Thanks for the solution for Q1, it is creative ! 
For Q2, Yes, I meant `split = ","`,  sorry for the confusing :(  
It is really exciting to know so many new handy packages each of the class , it is just sometimes I feel like they "stewed " together as some of them have very similar arguments and functions. I guess I just need more practice. 
@oganm you r right, `,` does not make any sense in this case , I am just curious as someday I may need to split "happyhalloween!" into "happy", "halloween","!"
Thank you both for the help !
