### ISSUE TITLE
error when trying to open figure - part 2

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#207]
I know this is probably too late for hw05, but I still want to know what is the problem:

I have tried several times to embed the figure I saved as a png with ggsave and I get this problems:
1) It won't knit because it says that the file can not be fetched by pandoc
2) It will knit but I get a blank box instead of the picture
3) It will knit but I get a link to the rmd file instead of the picture.

I tried google and they say it's a common problem, and that it can be usually fixed by adding
self contained: FALSE just below output and html_document, but this takes me to error 3.

I also tried changing my working directory to where my rmd file lives, but this will lead me to error 1. If I change the directory to the main page of my repo this will either give me error 1 or sometimes 2.

It seems super simple, but I really don't know what's the problem with this...

This is the code I used for the figure and for saving the plot. This is error 3.

```{r}
p <- ggplot(gapminder, aes(x = reorder(continent, lifeExp), y = lifeExp)) + geom_boxplot(aes(color = continent)) + geom_jitter( aes(color = continent), position = position_jitter(width=0.02), alpha = 0.2) + xlab('Continent') + ylab('Life Expectancy') + ggtitle('Life Expectancy of every continent')

ggsave('lifeExp_boxplot_nicer.png', plot = p)
```

Brenda

**Comment by jennybc** [comment]
Here's a little `.Rmd` file you can knit for yourself and see the different ways to get a plot directly from R code and from a PNG.

``` bash
    ---
    title: "Untitled"
    output: html_document
    ---

    ```{r pressure, echo=FALSE}
    library(ggplot2)
    p <- ggplot(pressure, aes(x = temperature, y = pressure)) + geom_point()
    p        # this causes p to be printed "to screen"
    print(p) # even more explicit! will give a second copy
    ggsave("pressure.png", p)
    ```

    This causes a PNG to be embedded.

    ![](pressure.png)
```

**Comment by bdacunha** [comment]
Thanks Jenny,

I thought you were supposed to add the whole file path to the figure, and not just the name for it... maybe that is why I was getting that error when I was trying to call my figure.

**Comment by jennybc** [comment]
It can be relative to where the `.Rmd` file lives. And, in general, I think it's better to do that than to use a full path. It definitely needs to be a path that will work with whatever working directory is at the time of render, which is almost always where the `.Rmd` lives.
