### ISSUE TITLE
Creating and using homemade colour vector

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#209]
Hello!
Sorry, I have a problem with creating and using my own colour vector. I even re-created my problem by using the `gapminder` data! I don't know what's going on, but my points on the graph stay black!!!!!

I create a named vector with colour information for each factor level (plus Australia, as I will ned htat for Jenny's example down below)

```{r}
> new_colours <- structure(c("blue", "firebrick3", "springgreen", "yellow"), 
+                            .Names =c("Germany", "France", "Italy", "Australia"))

> str(new_colours)
 Named chr [1:4] "blue" "firebrick3" "springgreen" "yellow"
 - attr(*, "names")= chr [1:4] "Germany" "France" "Italy" "Australia"

> head(new_colours)
      Germany        France         Italy     Australia 
       "blue"  "firebrick3" "springgreen"      "yellow" 
>```
Now I first make a smaller subset of `gapminder` and store it in `country3` as it contains information of three countries

```{r}
> country_3 <- gapminder %>% filter(country == c("Germany", "France", "Italy"))

> str(country_3)
'data.frame':	12 obs. of  6 variables:
 $ country  : Factor w/ 142 levels "Afghanistan",..: 45 45 45 45 48 48 48 48 65 65 ...
 $ continent: Factor w/ 5 levels "Africa","Americas",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ year     : num  1957 1972 1987 2002 1952 ...
 $ lifeExp  : num  68.9 72.4 76.3 79.6 67.5 ...
 $ pop      : num  44310863 51732000 55630100 59925035 69145952 ...
 $ gdpPercap: num  8663 16107 22066 28926 7144 ...

> head(country_3)
  country continent year lifeExp      pop gdpPercap
1  France    Europe 1957   68.93 44310863  8662.835
2  France    Europe 1972   72.38 51732000 16107.192
3  France    Europe 1987   76.34 55630100 22066.442
4  France    Europe 2002   79.59 59925035 28926.032
5 Germany    Europe 1952   67.50 69145952  7144.114
6 Germany    Europe 1967   70.80 76368453 14745.626
```
and now let's plot gdpPercap  vs. lifeExp  with colours mapped to different countries using my colour map
(PS I did copy and paste Jenny's code and used my own colour-scheme and it worked. I just can't find the difference now... I just can't
```{r}
p <- ggplot(country_3, aes( x=lifeExp, y= gdpPercap ))
p + geom_point() +
     aes(fill = country) + scale_fill_manual(values = new_colours)
```
arrrrg, points are still black!
Then I thought, maybe, the aes needs to be within the `geom_point()` command:
 
```{r}
> p <- ggplot(country_3, aes( x=lifeExp, y= gdpPercap ))
> p <- p+ geom_point(aes(fill = country) + scale_fill_manual(values = new_colours))

Error in aes(fill = country) + scale_fill_manual(values = new_colours) : 
  non-numeric argument to binary operator

> p
Error: No layers in plot
> 
```
I assume, it just needs to be written somewhere else, or I am missing a comma somewhere? But I tried random substitutions and whatnot and can;t find the error.

Any help appreciated

Cheers
Anna

PS: here is Jenny's example from class. I just changed two things:

* I filtered to ONLY oceanica
* I use my new_colours colour vector

```{r}
jdat <- gapminder %>% 
  filter(continent == "Oceania") %>% 
  droplevels() %>% 
  mutate(country = reorder(country, -1 * pop)) %>% 
  arrange(year, country)  

j_year <- 2007
q <-
  jdat %>% 
  filter(year == j_year) %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  scale_x_log10(limits = c(230, 63000))

(r <- q +
  geom_point(aes(size = pop), pch = 21, show.legend = TRUE) +
  scale_size_continuous(range=c(1,40)))

r + aes(fill = country) + scale_fill_manual(values = new_colours)
```

and tataaaaa, Australia is now yellow as set by my colour scheme..... WHY does it not work on my own example?????

**Comment by ksamuk** [comment]
try 'color' instead of 'fill'

```{r}
new_colours <- structure(c("blue", "firebrick3", "springgreen", "yellow"), .Names =c("Germany", "France", "Italy", "Australia"))
country_3 <- gapminder %>% filter(country == c("Germany", "France", "Italy"))

p <- ggplot(country_3, aes( x=lifeExp, y= gdpPercap ))
p <- p + geom_point(aes(color = country)) + scale_color_manual(values = new_colours)
```
![image](https://cloud.githubusercontent.com/assets/8412607/10859061/fe2ffc30-7f16-11e5-9008-7c54f4ea5762.png)

**Comment by ksamuk** [comment]
I could be wrong, but I think the aes `fill` only works in jenny's example because she is also using `scale_size_continuous()`, which makes the points into polygons.`

**Comment by daattali** [comment]
A few things:

1. Where you're defining `country_3`, you should be using `%in%` rather than `==`.  Inspect your `country_3` object right now; it only has 12 observations. There should be 36 (12 obs per country).

2. @ksamuk is right, you need to use `colour` and not `fill`.  It has nothing to do with the `scale` though. Some shapes, such as the default shape, are just a solid colour, and in that case `fill` doesn't do anything. Here are the shapes ![R shapes](http://www.sthda.com/sthda/RDoc/figure/graphs/r-plot-pch-symbols-points-in-r.png)

    As you can see see, some shapes have a border. Jenny's example uses shape #21 so that's why she can use both a `colour` and a `fill` with it

3. It's a bit weird in my opinion to define the names of the vector by manually adding the `.Names` attribute. Is this how Jenny showed you how to do it?  You can also define it like this `c("Germany" = 'blue', "France" = "firebrick3", "Italy" = "springgreen", "Australia" = "yellow")` or you could use the `setNames()` function, or you could first define the vector of colours and in the next line use the `names()` function to add the names. Any of these 3 approaches I'd say are better.

**Comment by ahippman** [comment]
THANK YOU THANK YOU THANK YOU!!!!!!! Both you!!!!

and @daattali no, it didn;t show how Jenny did it. This was the way I found it on a webpage.. Your way is way more intuitive! Thanks

**Comment by jennybc** [comment]
One more thing. This:

``` r
filter(country == c("Germany", "France", "Italy"))
```

should be this

``` r
filter(country %in% c("Germany", "France", "Italy"))
```

You're not getting an error now, but I bet you're not getting correct results/plot either.
