### ISSUE TITLE
When will the Homework 5 be graded and when will the grades for STAT545 be out?

### ISSUE THREAD

**Issue by yksugi** [STAT545-UBC/Discussion#210]

**Comment by jennybc** [comment]
I'm about to launch marking of hw04 and hw05. I'll try to do this in parallel, i.e. put different TAs on the two assignments. But ... it will be measured in weeks. Maybe we can put STAT 545 to bed in two weeks? That would be a new record for me, but believe me I'd also like to get it done.

**Comment by cathyxijuan** [comment]
Hi Jenny,
Did you email out the mark for homework 3 yet? Did I miss the email?

**Comment by jennybc** [comment]
Working on it right now.
