### ISSUE TITLE
dplyr::do() versus for()

### ISSUE THREAD

**Issue by samhinshaw** [STAT545-UBC/Discussion#211]
I was having quite a bit of trouble trying to tabulate the number of occurrences of "Joy" vs. "Despair" in the data from the candy survey.  I feel like I should be able to do this with `dplyr::do()` or `dplyr::count()`, but I just can't figure out how.  

What I'm trying to do is count the number of times "JOY" and "DESPAIR" occur per candy.  This can be roughly compared to counting the number of times specific `Sepal.Length`s occur per species.  Note that I am comparing this to the candy data, because I `gather()`ed the data adding columns "CandyType" and "JoyOrDespair" (in this analogy, "Species" and "Sepal.Length").  You can see this  applied to the candy dataset [here](https://github.com/STAT545-UBC/samuel_hinshaw/tree/master/experiments/103015).  
```
total <- iris %>% 
  group_by(Species) %>%
  count(Sepal.Length)
glimpse(total) %>%
  head()
```
This gives me the total number of observations for each Sepal.Length.  However, it does not separate by Species. I can get the numbers for a specific species with `filter()` though:
```
setosa <- iris %>% 
  filter(Species == "setosa") %>% 
  count(Sepal.Length)
```
I couldn't figure out how to use `do()`, `summarize()`,  `mutate()`, or any other `dplyr` function to get the total number of observations per candy.  

SO, I turned to `for()` loops, since I knew they would allow me to cycle through the candy types.  First we'll pretend we're looking for Sepal.Length of 5.0 instead of "JOY":
```
FiveTotal <- data.frame(1) %>% 
  tbl_df()
for(i in levels(iris$Species)){
  FiveTotal[i] <- iris %>% 
    filter(Species == paste(i), Sepal.Length == 5.0) %>% 
    nrow()
}
FiveTotal[1] <- NULL
names(FiveTotal) %>% 
  head()
FiveTotal <- gather(FiveTotal, "Species", "FiveNum", 1:3)
glimpse(FiveTotal) %>% 
  head()
```

And then for Sepal.Length of 5.1 instead of "DESPAIR":
```
FivepOneTotal <- data.frame(1)
FivepOneTotal <- tbl_df(FivepOneTotal)
for(i in levels(iris$Species)){
  FivepOneTotal[i] <- iris %>% 
    filter(Species == paste(i), Sepal.Length == 5.1) %>% 
    nrow()
}
FivepOneTotal[1] <- NULL
FivepOneTotal <- gather(FivepOneTotal, "Species", "FivepOneNum", 1:3)
glimpse(FivepOneTotal) %>% 
  head()
```

And now to join them:
```
FiveOrNot <- inner_join(FiveTotal, FivepOneTotal)
glimpse(FiveOrNot) %>% 
  head()
```
This finally gave me the result I wanted, but I feel like I've taken a step backwards, and should've been able to do this just with dplyr.  My questions are:
* How could I have done this with dplyr?
* The way I've reached my result seems overly complex & inefficient, as R has much better tools (such as dplyr) for handling problems that would otherwise need `for()` loops.  Is this assumption correct, or do you think there is still a place for them?

**Comment by daattali** [comment]
I tried running your code that "worked" but to me it just returned an empty dataframe.  Anyway, are you looking for the `tally` function?

```
iris %>% 
  group_by(Species, Sepal.Length) %>%
  tally
```

Is this what you were trying to get at?  If you look at the documentation for `count`, you'll actually learn about `tally` right in that same help file :)

FYI you can also achieve a similar thing without dplyr using `table`: 

```
table(iris$Species, iris$Sepal.Length)
```

although this doesn't return a data.frame, you'd have to convert it to one

**Comment by jennybc** [comment]
I'm glad @daattali actually ran this code and provided some answers. So I can provide a few more superficial observations:

  * `Sepal.Length` is a continuous variable, so I'm not sure if it's a great testbed for figuring this stuff out. Although I understand only a finite number of values actually occur.
  * Yes look at `tally()`. I got some great answers to a twitter question about cross-tabulation earlier this year. You might find some good ideas there:
    - https://gist.github.com/jennybc/04b71bfaaf0f88d9d2eb

**Comment by samhinshaw** [comment]
Yes!  Tally was exactly what I was looking for, thank you.  I did see the documentation for tally (as it's actually what comes up when querying `?count`, as you said @daattali ), but I must not have used it properly. When I run `tally`, it returns the same result as my `for()` loops, but long, not wide.  It also has the benefit of being only being ~1/10th of the code.  
```
TallyJD <- gathered_candy %>% 
  group_by(CandyType, JoyOrDespair) %>%
  tally()
```

Thank you @jennybc for the link, that's almost exactly what I was trying to do and it is so interesting to see all the different ways the same question can be executed!
