### ISSUE TITLE
Is the peer review of HW05 distributed yet? 

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#212]
Hello!

Just wanted to double check if the peer review of __HW05__ has started yet?
If not -> great, no rush
If yes -> my name doesn't seem to be in the hat for this round? I haven't received anybody to peer review (yet?)

Cheers
Anna

**Comment by LinaQiu** [comment]
I don't get the email for peer review either. So I don't think peer review for HW05 has started yet. Let's just wait for it, and give Jenny more time. Lol

**Comment by jennybc** [comment]
Assigning them tonight!

**Comment by ahippman** [comment]
Thank you!
