### ISSUE TITLE
Computer switch

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#214]
Hello everyone,

For the course I've been using my old computer that runs on windows. However, since it's slowly dying (almost dead actually), I bought a new computer, but this time, it's a mac. I was just wondering if there's an easy way in which I can transfer all my R things from one computer to the other... the only way I can think off is using a usb or something like that to copy all the files and paste them in the new laptop, but i think this would screw up my github configuration right?

Any suggestions?

Thanks!

Brenda

**Comment by cheny19** [comment]
You can use RStudio to pull the git repo to your local machine.

**Comment by bdacunha** [comment]
And everything that i pull will be saved in the order I want? If I want to push new homeworks this won't be an issue?

**Comment by cheny19** [comment]
Yes, it will be the same structure as the github repos.

It's always a good habit that you pull first and then push to make sure you don't have conflicts.

**Comment by bdacunha** [comment]
Great, it worked! Thank you!!!

**Comment by jennybc** [comment]
Switching computers is actually much easier when you keep everything in Git and host remotely, such as on GitHub!

But you should also learn about AirDrop, although I suspect it's only among Apple Devices. But it's super useful.
