### ISSUE TITLE
not knitting even though running the code within the chunk without problem...

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#216]
I have an .rmd file that I am working on in RStudio. The code runs smoothly, all necessary `libraries` are loaded, all files and objects are created in chunks  before they are used in following chunks.

I executed each chunk by itself, one by one to make sure they work
All objects are right there in my `Environment`

Then I want to `knit` and I get the following error message:
```{r}
Quitting from lines 243-295 (Comparing_TO1005_and_TO1003.Rmd) 
Error in eval(expr, envir, enclos) : object 'TO05_ALL_ORF_all' not found
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> %>% -> eval -> eval
Execution halted
```
I double an triple checked the spelling of the object, copy and pasted the right spelling, again ran the `chunk` in question line-by-line to make sure that it finds the **object 'TO05_ALL_ORF_all'** 

I also restarted RStudio a couple times in between, and then restarted my laptop.... All to no avail.

Any idea?

Just in case that it has to do with something else, here is the `chunk` in question:

```{r Summaries Per Treatment, eval=TRUE}
#TO 1005

#TO05 lowCu
TO05_lowCu <- TO05_ALL_ORF_all %>% 
  filter(Ratio.type == "lowCu")

Summ_lowCu_TO05 <-TO05_lowCu %>% 
  group_by(Protein_Subset) %>% 
  summarise_each_(funs(length, min(.,na.rm=TRUE), max(.,na.rm=TRUE), mean (.,na.rm=TRUE), median(.,na.rm=TRUE)), "Average") 

Summ_lowCu_TO05 <- Summ_lowCu_TO05 %>% 
  mutate(Strain = "1005") %>% 
  mutate(Data = "lowCu")

#TO05 lowFe
TO05_lowFe <- TO05_ALL_ORF_all %>% 
  filter(Ratio.type == "lowFe ") %>% 
  mutate(Ratio.type = "lowFe")

Summ_lowFe_TO05 <-TO05_lowFe  %>% 
  group_by(Protein_Subset) %>% 
  summarise_each_(funs(length, min(.,na.rm=TRUE), max(.,na.rm=TRUE), mean (.,na.rm=TRUE), median(.,na.rm=TRUE)), "Average") 

Summ_lowFe_TO05 <- Summ_lowFe_TO05 %>% 
  mutate(Strain = "1005") %>% 
  mutate(Data = "lowFe")

#TO05 lowFeCu..CuRun
TO05_lowFeCu..CuRun <- TO05_ALL_ORF_all %>% 
  filter(Ratio.type == "lowFeCu..CuRun")

Summ_lowFeCu..CuRun_TO05 <-TO05_lowFeCu..CuRun  %>% 
  group_by(Protein_Subset) %>% 
  summarise_each_(funs(length, min(.,na.rm=TRUE), max(.,na.rm=TRUE), mean (.,na.rm=TRUE), median(.,na.rm=TRUE)), "Average") 

Summ_lowFeCu..CuRun_TO05 <- Summ_lowFeCu..CuRun_TO05 %>% 
  mutate(Strain = "1005") %>% 
  mutate(Data = "lowFeCu..CuRun")

#TO05 lowFeCu..FeRun
TO05_lowFeCu..FeRun <- TO05_ALL_ORF_all %>% 
  filter(Ratio.type == "lowFeCu..FeRun")

Summ_lowFeCu..FeRun_TO05 <-TO05_lowFeCu..FeRun  %>% 
  group_by(Protein_Subset) %>% 
  summarise_each_(funs(length, min(.,na.rm=TRUE), max(.,na.rm=TRUE), mean (.,na.rm=TRUE), median(.,na.rm=TRUE)), "Average") 

Summ_lowFeCu..FeRun_TO05 <- Summ_lowFeCu..FeRun_TO05 %>% 
  mutate(Strain = "1005") %>% 
  mutate(Data = "lowFeCu..FeRun")


```

Thanks for any help
Cheers
Anna

**Comment by jennybc** [comment]
Where does `TO05_ALL_ORF_all` get created? Because it's not in the above code.

My spidey sense says this will ultimately prove to be a working directory issue. Is `TO05_ALL_ORF_all` created from something read from file? And when you're developing this `.Rmd` working directory is set to one place, but that place is different from where this `.Rmd` file lives?

**Comment by ahippman** [comment]
It's brought in from a sub-directory

```{r}
TO05_ALL_ORF_all <- read.delim( file="Input_Data/TO05_ALL_ORF_ProtSubsets.txt",  sep = "\t", header=TRUE, stringsAsFactors = TRUE)

# then I do this
TO05_ALL_ORF_all <- tbl_df(TO05_ALL_ORF_all)

# and that
TO05_ALL_ORF_all$Strain <- as.factor(TO05_ALL_ORF_all$Strain)
TO05_ALL_ORF_all$Annotation_Combined <- as.character(TO05_ALL_ORF_all$Annotation_Combined)
TO05_ALL_ORF_all$KO <- as.character(TO05_ALL_ORF_all$KO)
TO05_ALL_ORF_all$GO_terms <- as.character(TO05_ALL_ORF_all$GO_terms)

glimpse(TO05_ALL_ORF_all) #all good!
```
I use it also in chunks earlier than this one that gives me trouble. There (where it doesn't detect that it can't find it), it's used this way:
```{r}
(head(TO05_ALL_ORF_all %>% Summry_per_Trtmnt()))
```

**Comment by jennybc** [comment]
Then I'd stick a couple  `ls()`'es in along the way to track which objects exist. At what point does this object go from existing to not existing in the workspace? What's going on around there?

**Comment by ahippman** [comment]
This is now within the chunk that gives the error message that it cannot find object 'TO05_ALL_ORF_all'
... I know it;s crammed full of objects (sorry!) ... but the thing is, object 'TO05_ALL_ORF_all' is one of them (position [23])...

```{r}
> ls()
 [1] "p"                          "Summ_lowCu_TO05"            "Summ_lowFe_TO05"            "Summ_lowFeCu..CuRun_TO05"  
 [5] "Summ_lowFeCu..FeRun_TO05"   "Summ_lowFeCu.vs.lowCu_TO05" "Summ_lowFeCu.vs.lowFe_TO05" "Summ_overview_03"          
 [9] "Summ_overview_05"           "Summ_overview_both"         "Summ_perTreatmt_TO05"       "Summ_perTreatmt_TO05_gr1"  
[13] "Summ_perTreatmt_TO05_gr2"   "Summ_perTreatmt_TO05_gr3"   "Summ_TO03_DOWN_all"         "Summ_TO03_UP_all"          
[17] "Summ_TO05_DOWN_all"         "Summ_TO05_UP_all"           "Summry_per_Trtmnt"          "TO03_ALL_ORF_all"          
[21] "TO03_DOWN_ORF_all"          "TO03_UP_ORF_all"            "TO05_ALL_ORF_all"           "TO05_DOWN_ORF_all"         
[25] "TO05_lowCu"                 "TO05_lowFe"                 "TO05_lowFeCu..CuRun"        "TO05_lowFeCu..FeRun"       
[29] "TO05_lowFeCu.vs.lowCu"      "TO05_lowFeCu.vs.lowFe"      "TO05_UP_ORF_all"           
> 
```
If it's something really small that I have overlooked and which I am not showing, I can also stop by the office hour tomorrow to look at the whole thing together with somebody

**Comment by jennybc** [comment]
Is it a matter of `TO05...` vs `T005...` vs `TOO5...` in your code? It would really easy to goof up an uppercase O and a zero 0.

Otherwise ... ¯\_(ツ)_/¯

**Comment by ahippman** [comment]
No, unfortunately (or thank goodness?) it;s not that. I checked for that and am pretty confident (well I wouldn't bet my first born on it, but still) that it is not related to a typo...
the last thing that I will try before tomorrow is deleting the chunk and see if it is `knitting` and then `pasting` the old chunk into new rmarkdown and see if it is behaving better there... will post my tales here...

**Comment by ahippman** [comment]
Spoiler alert -> tried 4 different things, puzzle still not solved

1) Copied all in new .rmd 
-> didn't knit

2) Copied all in new .rmd
 + deleted all but those chunks that needed to access the supposedly missing object
 -> it knitted (_which still doesn't help me a whole lot.. besides that it probably really just can't find the object_)

3) made a new chunk with new chunk name and entered the same code as in faulty one (I know that;s desperate), deleted the old chunk
-> didn;t knit (_silver lining: I guess I can rule out that there is something funny with the chunk itself_)

4) Copied original .txt that was used to create the object from subfolder into `wd` and `read.delim` loaded the file now from the `wd`
-> still didn;t knit

Ah well, the joys.... OK, maybe meanwhile, I will just execute the chunk and write the resulting object into a file and then reload that new file so I can do some plots with that one

**Comment by daattali** [comment]
@ahippman if you don't figure it out by morning, come to me tomorrow (during class if there's time, or to the office hours after)

**Comment by ahippman** [comment]
Thanks, I will

Anna Hippmann, PhD Student

Department of Earth, Ocean and Atmospheric Sciences
The University of British Columbia
Room 2041, Earth Sciences Building
2207 Main Mall
Vancouver, British Columbia
Canada, V6T 1Z4

ahippman@eos.ubc.ca
office +1-604-827-5459
cell +1-604-771-8346



Anna Hippmann, PhD Student

Department of Earth, Ocean and Atmospheric Sciences
The University of British Columbia
Room 2041, Earth Sciences Building
2207 Main Mall
Vancouver, British Columbia
Canada, V6T 1Z4

ahippman@eos.ubc.ca
office +1-604-827-5459
cell +1-604-771-8346

**Comment by ahippman** [comment]
@jennybc the problem was (as @daattali found - Thanks again!):
the chunks in which I brought the data in had their chunk options set to `eval=FALSE`, so they were never executed! I will never do THAT again! :)
