### ISSUE TITLE
Possible GitHub Session?

### ISSUE THREAD

**Issue by gjahesh** [STAT545-UBC/Discussion#218]
Hi everyone,

I was wondering if any one is interested in learning more about `Github` so as Jenny once mentioned in the class last week, we could have a lecture/tutorial session before `STAT547` ends?
I found this [Good Resources for learning Git and Github](https://help.github.com/articles/good-resources-for-learning-git-and-github) quite useful so far.

Thanks,
Golnaz

**Comment by JoeyBernhardt** [comment]
yes, I'd be interested!

**Comment by wmhall** [comment]
I would be interested!

**Comment by min110** [comment]
That would be greatly helpful , at least for me .

**Comment by zhamel** [comment]
I would be interested.

**Comment by jennybc** [comment]
I'm definitely still up for this. If we are a small-ish group, maybe we can figure out a way to convene somewhere ... informal? Does anyone know if one of the establishments in the new fancy student/alumni center has an ?alcove? where we could be regular paying customers, but have out laptops & a projector? 😬

**Comment by hamid-omid** [comment]
I'd be interested. My department has rooms with projector that I could book for free.

**Comment by BattaLiu** [comment]
I’d be interested.

Jiayi Liu

**Comment by gjahesh** [comment]
I could also arrange a room with a projector :)

**Comment by gjahesh** [comment]
Hi every one,

I'm just posting this as a follow up to see if every one is still up for this? I was going to ask Jenny on Thursday  ,but then I thought the last day of the class might get quite busy for her...
So,I'm not sure how is her and every one else's schedule like but maybe we could have a session some time next week or the one after? 

Also, I could arrange a room and a projector( nothing fancy though!) unless any of you have a better option.

Thanks,
Golnaz

**Comment by jennybc** [comment]
I'm still game. Someone needs to present me with a pretty specific proposal. I'm out of town the first half of the next two weeks. But Thurs/Fri Dec 10/11 and 17/18 might work. Or I could do it in January. It's not going to be officially part of STAT 545/547 anyway. In which case, we could also team up with the R Study Group? @minisciencegirl

**Comment by minisciencegirl** [comment]
That sounds great! Let me check with @BillMills and other Git Masters in the study group. We could definitely run a session. January might work better for us.

**Comment by jennybc** [comment]
If @BillMills and I co-taught, that would be fun. Then we could demonstrate various collaborative workflows in real-time.

**Comment by minisciencegirl** [comment]
Awesome! Saw people play a game of tic-tac-toe as a way to learn various git commands. Let's get this on the schedule!

**Comment by BillMills** [comment]
Hey sorry for the slow reply - yes, this sounds awesome! I would definitely be available for this - the 17th or January both work for me.

**Comment by BillMills** [comment]
*actually we could do the 18th too, and all pack up and head to the [Study Group Holiday Party](https://github.com/minisciencegirl/studyGroup/issues/73) at the end of the day - everyone is invited!

**Comment by jennybc** [comment]
I can't really bear the thought of doing this before the holidays. Can I plead for January?

**Comment by BillMills** [comment]
Sure, I'll be around in January. btw @jennybc I like your idea of doing something pretty informal; I'm thinking we walk people through a real fork-branch-pull workflow, and stop to talk about details as they arise in context, which works better in more conversational settings.

**Comment by gjahesh** [comment]
Sorry to jump in the middle , just a follow up on this to see if we could finally have a session please... Thanks :)

**Comment by jennybc** [comment]
No it has not been scheduled yet. I think the Study Group is the right venue for this now that the course is over....

**Comment by gjahesh** [comment]
Thanks @minisciencegirl and @jennybc .

I have created a [doodle](http://doodle.com/poll/pvd5fdqvpigrxc6v#table) .Is it possible for the people who showed interest on this issue to select the days in February that would most likely work for them to attend this session, please?

 It's a wide range and I have excluded the stat holiday Feb15 and the day after that Feb16.
I think you could pick days that are less busy for you during the week.

There's also [Issue#96](https://github.com/minisciencegirl/studyGroup/issues/96) on RstudyGroup repo that you could follow up.

Thanks :)

**Comment by JoeyBernhardt** [comment]
Hi @gjahesh, the doodle poll doesn't include times...is there a time of day that you're thinking of?
Thanks!

**Comment by gjahesh** [comment]
@JoeyBernhardt ,it's actually the [RstudyGroup](https://github.com/minisciencegirl/studyGroup), who's organizing the session.SoI just put days for now for them to be more flexible about the timing.
I guess you could pick days that's less busy for you during the week.Later on I guess the final timing will be asked again.
