### ISSUE TITLE
Is homework07 already distributed?

### ISSUE THREAD

**Issue by LinaQiu** [STAT545-UBC/Discussion#219]
Hi @jennybc,

I am wondering whether homework07 has been distributed or not? Cause the one I found on website seems like is from last year.

Thanks.

**Comment by daattali** [comment]
@LinaQiu HW07 has not been assigned yet, it is still being worked on

**Comment by jennybc** [comment]
Will post soon. But it is described here in yesterday's class meeting page:

http://stat545-ubc.github.io/cm103_data-cleaning.html

**Comment by LinaQiu** [comment]
@jennybc @daattali  Thanks!
