### ISSUE TITLE
How can I apply for Educational Pack of Github?

### ISSUE THREAD

**Issue by BattaLiu** [STAT545-UBC/Discussion#221]
It seems to be a very old topic. But after million times of applying, I still get refused ( almost every time get refuse letter seconds later). 

Do you guys have any idea to solve this problem? I admit that I didn't create my account using educational email, but then I changed my primary email address back to educational one after several failure. 

I also tried sending a picture of my ID (two side together), again failure.

**Comment by oganm** [comment]
Are you talking about the student dev pack? All you had to do was to supply an institutional email address. If all fails you can always contact a real person through https://github.com/contact

**Comment by jennybc** [comment]
I'm afraid I don't have any new, great ideas.

**Comment by daattali** [comment]
@BattaLiu I was rejected several times as well for no apparent reason. I just kept emailing them every time and was a major pain in their butts until eventually they actually read/replied to my email and told me if it was mistake and I'm now approved.

If you really really care to get it, then you can be as persistent (aka annoying) as me and just keep bugging them. But look through the pack and see if there's stuff there that seems really worth it for you to spend your time on. For me it was worth it

**Comment by BattaLiu** [comment]
Thank you for your advice @oganm ! I have sent them an email again hoping this time works. 
And I want to get the student dev pack mainly because of the five private repositories, or I will choose to use Bitbucket @daattali .
