### ISSUE TITLE
Timestamp in candy survey

### ISSUE THREAD

**Issue by gjahesh** [STAT545-UBC/Discussion#222]
Hi there,

Just wondering if any one has encountered this problem. I did went through the [col_types](https://cran.r-project.org/web/packages/readr/vignettes/column-types.html) and to change the Timestamp I have the following:

```{r}
raw <- read_csv("CANDY-HIERARCHY-2015 SURVEY-Responses.csv",
                col_types = list(Timestamp = col_datetime()))
```
but what I get is like this:

##
#Warning: 5658 parsing failures.
row       col   expected             actual
  1 Timestamp date like  10/23/2015 8:46:20
  2 Timestamp date like  10/23/2015 8:46:52
  3 Timestamp date like  10/23/2015 8:47:34
  4 Timestamp date like  10/23/2015 8:47:59
  5 Timestamp date like  10/23/2015 8:48:12
... ......... .......... ..................
.See problems(...) for more details.
> raw
Source: local data frame [5,658 x 124]

   Timestamp How old are you? Are you going actually going trick or treating yourself?
      (time)            (chr)                                                    (chr)
1       <NA>               35                                                       No
2       <NA>               41                                                       No
3       <NA>               33                                                       No
4       <NA>               31                                                       No
5       <NA>               30                                                       No
6       <NA>               38                                                       No
7       <NA>               48                                                       No
8       <NA>               39                                                       No
9       <NA>            9E+22                                                      Yes
10      <NA>               54                                                       No
..       ...              ...    

When I do `problems(raw)` I get this:

 problems(raw)
Source: local data frame [5,658 x 4]

     row       col   expected             actual
   (int)     (chr)      (chr)              (chr)
1      1 Timestamp date like  10/23/2015 8:46:20
2      2 Timestamp date like  10/23/2015 8:46:52
3      3 Timestamp date like  10/23/2015 8:47:34
4      4 Timestamp date like  10/23/2015 8:47:59
5      5 Timestamp date like  10/23/2015 8:48:12
6      6 Timestamp date like  10/23/2015 8:49:07
7      7 Timestamp date like  10/23/2015 8:50:09
8      8 Timestamp date like  10/23/2015 8:52:14
9      9 Timestamp date like  10/23/2015 8:52:22
10    10 Timestamp date like  10/23/2015 8:53:31
..   ...       ...        ...                ...

So why does Timestamp is replaced with `NA` and `problems` tells me what R expects to see for Timestamp is `(chr)`?!?

**Comment by jennybc** [comment]
Have you looked at [how I brought `Timestamp` in](https://github.com/jennybc/candy/blob/ae24ea46037a83d5bf777b7df7af1b263f2d6a25/data-raw/00_explore-raw.R#L15)? If the format is non-standard, which this is, you must specify.

``` r
raw <- read_csv("CANDY-HIERARCHY-2015 SURVEY-Responses.csv",
                col_types = cols(
                  Timestamp = col_datetime("%m/%d/%Y %H:%M:%S")
                ))
```

**Comment by gjahesh** [comment]
Thanks :)
