### ISSUE TITLE
droplevel () doesn't drop my levels

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#223]
Hello! 

Somehow the `droplevel()` function doesn;t work for me. I even re-enacted it with the gapminder data! :)

I am loading the data, then I `filter` for three countries (Germany, France, Italy), then `select` the variable `country` and want to keep only the `unique` values. 
 
```{r}
library(gapminder)
gapminder <- gapminder

> country <- gapminder %>%
+ filter(country=="Germany" | country == "France" | country == "Italy") %>%
+ select (country) %>%
+ unique()
> str(country)
'data.frame':	3 obs. of  1 variable:
 $ country: Factor w/ 142 levels "Afghanistan",..: 45 48 65
```
#Here it is, I have a data.frame with 3 observations of 1 variable but my variable is a factor with 142 levels!!! 
So I thought : Right! You have got to drop the levels! 

```{r}
> droplevels(country)
   country
1   France
13 Germany
25   Italy
> str(country)
'data.frame':	3 obs. of  1 variable:
 $ country: Factor w/ 142 levels "Afghanistan",..: 45 48 65
```
but it didn't drop them. I tried `droplevel()`, `droplevel.factor()`, `droplevel.data.frame()` and none worked.
I have a feeling this was addressed but couldn't find it. I searched the issues via "level in:title", "drop in:title" to no avail.

How do I really drop the levels?
Cheers
Anna

**Comment by jennybc** [comment]
In your second piece of code? You just execute `droplevels(country)` but you don't make an assignment. So you have not, in fact, dropped any levels.

Also:

  * I don't think you want `unique()` in that first pipeline.
  * Try `filter(country %in% c("Germany", "France", "Italy"))`

I like your examples! Makes it easy to answer your questions.

**Comment by ahippman** [comment]
Yes, that was it! 
```{r}
> country <- gapminder %>% 
+   filter(country=="Germany" | country == "France" | country == "Italy") %>% 
+    select (country) %>% 
+    unique() %>% 
+   droplevels()
> str(country)
'data.frame':	3 obs. of  1 variable:
 $ country: Factor w/ 3 levels "France","Germany",..: 1 2 3
>
```
Thanks!!!
