### ISSUE TITLE
embedding figure in hw5

### ISSUE THREAD

**Issue by molliejmcdowell** [STAT545-UBC/Discussion#225]
Hi,

When I knitted homework 5, my figures embedded in the file without a problem. I thought I checked the md file on github before submitting the homework to make sure everything looked fine. Both of my reviewers, however, said that the figures did not embed. I just checked the links, and they lead to 404 pages. Can anyone help me solve this? Or point me to an issue where it is solved? Here is the code:

![Life expectancy versus time](/Users/molliejmcdowell/Desktop/UBC/courses/stat545/mollie_mcdowell_github_repo/Homework/Homework5/LifeExpVsTime_Homework5.png)
![Life expectanccy versus time, scaled at 0.8](/Users/molliejmcdowell/Desktop/UBC/courses/stat545/mollie_mcdowell_github_repo/Homework/Homework5/LifeExpVsTime_Homework5_Scale.png)

thanks,
mollie

**Comment by daattali** [comment]
Looking at the source code of [your hw05 .Rmd file](https://github.com/STAT545-UBC/mollie_mcdowell/blob/master/Homework/Homework5/Homework5.Rmd), I can see that you manually added the file path of those two images.  This is the file path that you have:

```
![Life expectancy versus time](/Users/molliejmcdowell/Desktop/UBC/courses/stat545/mollie_mcdowell_github_repo/Homework/Homework5/LifeExpVsTime_Homework5.png)
![Life expectanccy versus time, scaled at 0.8](/Users/molliejmcdowell/Desktop/UBC/courses/stat545/mollie_mcdowell_github_repo/Homework/Homework5/LifeExpVsTime_Homework5_Scale.png)
```

You're telling the markdown file to include an image from your desktop.  That won't work. The markdown file on your computer knows how to find `/Users/molliejmcdowell/Desktop/UBC/`, but the markdown file on the web doesn't have access to your computer and when it sees that path it can't find the file.  You need to add those two images to your repository, and change the paths to reflect that. So as a simple solution, just copy the two images into your Homework5 directory, and change the paths of the images to just the name of the image itself.  To be a bit more organized, you could put the images inside a different folder, and change the path in the Rmd accordingly.

Does this make sense?

**Comment by molliejmcdowell** [comment]
yes, it works now, thanks Dean
