### ISSUE TITLE
dataframe will only show ID with 4 digits and not the others

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#229]
Hello, 

I was trying to run the code that jenny just pushed, but with some additions:

candy_keep <- c("Snickers", "Healthy Fruit", "Twix", "Vicodin", 'Pencils', 'Nerds', 'Skittles', 'Chiclets', 'Fuzzy Peaches', 'Kale smoothie')
id_keep <- c(178, 2254, 4817, 5522, 2389, 23, 89, 2, 3000, 29) %>%
  sprintf("ID%04d", .)

candy_mini <- candy_dat %>%
  filter(candy %in% candy_keep, id %in% id_keep)

write_csv(candy_mini, "candy-joy-mini.csv")

id_mini <- id_dat %>%
  filter(id %in% id_keep)

write_csv(id_mini, "candy-id-mini.cv")

but when i see the final data.frame id_mini i only get the data for the ids that have 4 digits, and not all that I selected. 

I tried changing the sprintf part because I think that is where the problem is, but I have no idea how to fix the problem.

Brenda

**Comment by npjc** [comment]
can you provide a minimal reproducible example (what is `id_dat` in your example?).

Also, if you wrap blocks of code with 3 back ticks before and after (```) it will format nicely in the github issues!

**Comment by bdacunha** [comment]
```
raw <- read_csv("CANDY-HIERARCHY-2015 SURVEY-Responses.csv",
                col_types = cols(
                  Timestamp = col_datetime("%m/%d/%Y %H:%M:%S")
                ))

raw_with_id <- raw %>% mutate(id = sprintf('ID%04d', row_number())) %>% 
  mutate(id = sprintf('ID%4d', row_number())) %>% 
  select(starts_with('Age'), everything())


age_nchar <- raw_with_id$Age %>% 
  str_length()

ggplot((data_frame(age_nchar)) %>% 
  filter(age_nchar < 5), aes(age_nchar)) + geom_histogram()
```

## Now I want to clean the Age variable

```
tmp <- raw_with_id %>%
  mutate(age_nchar = str_length(Age))

ggplot(tmp %>% filter(age_nchar < 8), aes(age_nchar)) + geom_bar()

raw_with_id <- raw_with_id %>%
  mutate(age_nchar = str_length(Age)) %>%
  filter(age_nchar <= 2) %>%
  select(-age_nchar) %>%
  mutate(Age = as.integer(Age)) %>%
  filter(!is.na(Age))
nrow(raw_with_id)
```
## this is to remove any weirdness of the names:

```
tmp_names <-
  data_frame(orig_name = names(raw_with_id)) %>%
  mutate(is_candy = str_detect(orig_name,"^\\["),
         new_name = str_replace_all(orig_name, "(^\\[)(.*)(\\]$)", "\\2"),
         new_name = str_replace_all(new_name, '["’]', "'"),
         is_changed = orig_name != new_name)
sum(tmp_names$is_candy)
table(tmp_names$is_candy, tmp_names$is_changed)

names(raw_with_id) <- tmp_names$new_name
```
## now this will be saved in a diff file

```
candy_names <- tmp_names %>%
  filter(is_candy) %>%
  .$new_name
length(candy_names)

candy_dat_untidy <- raw_with_id %>%
  select(one_of(c("id", candy_names)))

write_csv(candy_dat_untidy, "candy-joy-untidy.csv")
```
## here we select everything that is not candy to make a diff frame

```
id_dat <- raw_with_id %>%
  select(-one_of(candy_names))
id_dat
names(id_dat)
```

## and now we change names again to this variables with weird names

```
df <- data_frame(
  orig_name = c(
    "id",
    "Age",
    "Timestamp",
    "Are you going actually going trick or treating yourself?",
    "Guess the number of mints in my hand.",
    "'That dress* that went viral early this year - when I first saw it, it was ________'",
    "What is your favourite font?"),
  new_name = c(
    "id",
    "Age",
    "timestamp",
    "trick_or_treat",
    "n_mints",
    "dress",
    "font")
)
```

##THIS MAKES A NICE DATA FRAME WITH THE CHANGES AND WITHOUT THE CANDIES OR DEGREES OF SEP

```
id_dat <- id_dat %>%
  select(one_of(df$orig_name))
id_dat
names(id_dat) <- df$new_name[match(df$orig_name, names(id_dat))]
id_dat

id_dat %>%
  mutate(n_mints = str_sub(n_mints, 1, 53))

write_csv(id_dat, "candy-id.cv")
```

##tidying the candy data

##we need to open tidyr for this and also this makes a data frame with one candy and if it brings joy or despair

```
candy_dat <- candy_dat_untidy %>%
  gather(candy, joy, -id) %>%
  mutate(joy = joy == "JOY")
write_csv(candy_dat, "candy-joy.csv")
```

##now i will create some small candy data to work with

```
candy_keep <- c("Snickers", "Healthy Fruit", "Twix", "Vicodin", 'Pencils', 'Nerds', 'Skittles', 'Chiclets', 'Fuzzy Peaches', 'Kale smoothie')
id_keep <- c(178, 2254, 4817, 5522, 2389, 23, 89, 2, 3000, 29) %>%
  sprintf("ID%04d", .)

candy_mini <- candy_dat %>%
  filter(candy %in% candy_keep, id %in% id_keep)

write_csv(candy_mini, "candy-joy-mini.csv")

id_mini <- id_dat %>%
  filter(id %in% id_keep)

write_csv(id_mini, "candy-id-mini.cv")
```

This is everything I got so far...

**Comment by jennybc** [comment]
Can you shave this down so it's the minimum code needed to show your problem? Right now, it looks like the entire script I posted.

I just reran it and it does still work for me. I also compiled to markdown, so you can look at my output as I go and try to see where your thing goes off the rails?

https://github.com/jennybc/candy/blob/master/data-raw/00_explore-raw.md
