### ISSUE TITLE
Candy names to factor level

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#231]
I'm trying to turn the candy name columns into factor levels as was suggested in class the other day. Ultimately I want a dataframe with 3 columns: id, candy, response, where a single respondent will span multiple rows.

I have managed to build this dataframe using the following:

```
#Get raw candy names from columns


columnNames <- colnames(raw)
rawCandyNames <- grep("^\\[", columnNames, value = TRUE)
rawCandyIndex <- grep("^\\[", columnNames, value = FALSE)



#create dataframe for candy information. preallocate the candy dataframe

numCandy <- 95
totalRows <- numCandy*nrow(raw)
candyInfo <- data.frame(id = numeric(totalRows), candy = character(totalRows), stringsAsFactors = TRUE, response = logical(totalRows))

candyInfo["id"] <- rep(1:nrow(raw), each=numCandy)
candyInfo["candy"] <- rep(rawCandyNames)


#For each respondent, check their response for each candy, and add this to the candy data. A single respondent will span multiple rows in the new dataframe

responseVector <- vector()
for (i in 1:nrow(raw)) {
    for (j in rawCandyIndex) {
        responseVector <- c(responseVector, raw[[i,j]])
    }
}

candyInfo["response"] <- responseVector
```

This all works fine, but 2 questions/problems:

1. Is there a faster way to do this than what I did above? Using dplyr or reshaping maybe? Creating responseVector takes a very long time, and would like to do this quicker if its possible.
2. The resulting dataframe is massive (over half a million rows, which I believe is expected). Trying to do any type of grouping, filtering, plotting just chokes my computer. Could this be related to the way I created the dataframe above? How should I proceed with exploring the data given such a large dataframe?

**Comment by jennybc** [comment]
The code I pushed reshapes the data just as you wish, I think.

https://github.com/jennybc/candy/blob/e898ee263b03148298ddc0e5964c3e3c8c833c21/data-raw/00_explore-raw.R#L118-L124

``` r
#' Tidy the candy data. This makes a rather large file and I won't be committing
#' and pushing it.

candy_dat <- candy_dat_untidy %>%
  gather(candy, joy, -id) %>%
  mutate(joy = joy == "JOY")
write_csv(candy_dat, "candy-joy.csv")
```

Yes it has over half a million rows. That should be fine, although you might not want to put this in your class git repo -- consider gitignoring it. Yes I think you are creating it in an inefficient way. Try the above approach.

You might want to work with a smaller number of candies. And only scale up once you've got some analyses and figures, etc. that are completely dialed in.
