### ISSUE TITLE
postpone candy homework due date until Friday November 13?

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#234]
Hi all.

If it is the will of the class, I am willing to postpone the "candy dataset" homework until this Friday, November 13.

Why? I lost every computer I own in a robbery this weekend and have not been able to post the assignment. Luckily @ksamuk has put something together. I have not reviewed it yet but I assume it is basically as described on Tuesday and Thursday of last week.

However I realize it's not official until we post it.

Can a few people can weigh in here with an expression of whether you'd prefer to get this done sooner (Wed Nov 11) or later (Fri Nov 13).

In class, we will be moving on to building R packages, regardless!

**Comment by LinaQiu** [comment]
Nov 13 sounds great!

**Comment by sho-87** [comment]
I'd be OK with either day.

My concern is that I've already submitted the assignment thinking the outline was posted last week: https://stat545-ubc.github.io/cm104_data-cleaning.html

Will the actual assignment be different from what was posted?

**Comment by zhamel** [comment]
Either is fine with me.

**Comment by jennybc** [comment]
@sho-87 

No, nothing has changed. It just felt odd to post the formal assignment so late.

You could of course continue to work on it. Or not. I understand wanting something to be DONE.

**Comment by ahippman** [comment]
Holy smokes! So sorry to hear! That's a bummer (OK, that's probably quite the understatement) What a headache to get everything set up again! Hope no keepsakes got away... In the end of the day (as one of my supervisors once said) "Stuff can be replaced - family not" 
Hope, that happened while you and your family were gone. 
But still... what a freaking headache

**Comment by gjahesh** [comment]
Such an odd terrible experience! So sorry to hear about it! 
I guess Friday gives more time to ppl completing their work.

**Comment by Haycen** [comment]
Friday 13th would be great

On Tue, Nov 10, 2015 at 8:12 AM, Golnaz Jahesh <notifications@github.com>
wrote:

> Such an odd terrible experience! So sorry to hear about it!
> I guess Friday gives more time to ppl completing their work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAT545-UBC/Discussion/issues/234#issuecomment-155467877>
> .
>



-- 
Hassen Allegue

**Comment by jennybc** [comment]
It's official. The "candy dataset" homework due this Friday, November 13.
