### ISSUE TITLE
Timezone Troubles

### ISSUE THREAD

**Issue by mstrimas** [STAT545-UBC/Discussion#235]
When importing the timestamp field of the candy dataset with:  
```
read_csv(col_types = cols(Timestamp = col_datetime("%m/%d/%Y %H:%M:%S")))
```
The resulting POSIXct variable is given the default timezone of UTC. Do we know the actual time zone for this field? I image it's Vancouver time since the survey was created by someone at UBC.

Assuming, it is Vancouver time, I converted the timestamp field to the correct time zone (PDT/PST since there was a time change in there) using `lubridate::force_tx(timestamp, 'America/Vancouver').  

Finally, I've tried to plot a histogram of responses per hour with:  
```
questions %>% 
  mutate(hms = as.POSIXct(format(timestamp, "2015/01/01 %H:%M:%S"))) %>% 
  ggplot(aes(x = hms)) +
    geom_histogram(binwidth = 60*60) +
    scale_x_datetime(date_breaks = '3 hours', date_labels = '%H%M')
```
The variable `hms` is used to group times together across days (if there's a more direct way of doing this, I'm all ears). Finally, **my main issue** is that ggplot decides to shift the times back to UTC for plotting so that everything is offset. It seems from reading help files that ggplot is *supposed* to shift timezones to always use your local timezone, but my computers timezone is correctly set to local Vancouver time and this isn't happening for me. Is there a simple way to tell ggplot to not mess with the times or force it to plot in a given time zone? Anyone out there good at working with dates want to chime in?  

Here's a reproducible example:  
```
structure(c(1445730513, 1446127062, 1446125752, 1445653711, 1446070072, 
1446098841, 1446065691, 1446068301, 1446131775, 1445809457, 1446139230, 
1446065777, 1446085553, 1446093400, 1445809372, 1446092407, 1445700436, 
1446089994, 1445783652, 1446070240), class = c("POSIXct", "POSIXt"
), tzone = "America/Vancouver") %>% 
  data.frame(timestamp = .) %>% 
  mutate(hms = as.POSIXct(format(timestamp, "2015-01-01 %H:%M:%S"), 
                          tz = 'America/Vancouver')) %>% 
  ggplot(aes(x = hms)) +
    geom_histogram(binwidth = 60*60) +
    scale_x_datetime(date_breaks = '3 hours', date_labels = '%H%M%Z')
```

**Comment by jennybc** [comment]
You have truly arrived once you have time zone problems!

I haven't read all of the above yet. I am also not expert at date-times. But in general `lubridate` is a very helpful package.

**Comment by aammd** [comment]
Can I chime in here? I love date agony almost as much as file-separator-agony

First off, as far as I can tell the code below (slightly simplified from yours, @mstrimas ) works on my machine with `ggplot 1.0.1`. Is this a version issue?
```
structure(c(1445730513, 1446127062, 1446125752, 1445653711, 1446070072, 
            1446098841, 1446065691, 1446068301, 1446131775, 1445809457, 1446139230, 
            1446065777, 1446085553, 1446093400, 1445809372, 1446092407, 1445700436, 
            1446089994, 1445783652, 1446070240), class = c("POSIXct", "POSIXt"
            ), tzone = "America/Vancouver") %>% 
  data.frame(timestamp = .) %>% 
  mutate(hms = as.POSIXct(format(timestamp, "2015-01-01 %H:%M:%S"), 
                          tz = 'America/Vancouver')) %>% 
  ggplot(aes(x = hms)) +
  geom_histogram(binwidth = 60*60) +
  scale_x_datetime()
```

When I say "works" I mean that the counts of observations in 1 hr periods seems to be accurate and not shifted into incorrect timezones. Unless I am missing something !

@jennybc mentioned lubridate, which I love. Here is how I would approach this:

```
structure(c(1445730513, 1446127062, 1446125752, 1445653711, 1446070072, 
            1446098841, 1446065691, 1446068301, 1446131775, 1445809457, 1446139230, 
            1446065777, 1446085553, 1446093400, 1445809372, 1446092407, 1445700436, 
            1446089994, 1445783652, 1446070240), class = c("POSIXct", "POSIXt"
            ), tzone = "America/Vancouver") %>% 
  data.frame(timestamp = .) %>% 
  mutate(hms = ymd_hms(timestamp)) %>% 
  mutate(hrs = hour(hms)) %>%
  group_by(hrs) %>% 
  tally %>% 
  ggplot(aes(x = hrs, y = n)) +
  geom_bar(stat = "identity")
```
Note the simpler lubridate function for parsing dates: `ymd_hms()`. Also the handy `hour` function for extracting just the hour component of a datetime object.

Rolled my own "histogram" because I have not your patience for manipulating breakpoints.

**Comment by aammd** [comment]
![mattdates](https://cloud.githubusercontent.com/assets/1198242/11072682/c3aef182-879b-11e5-8665-d5109d42d00a.png)

**Comment by mstrimas** [comment]
Thanks @aammd for chiming in! Our ggplot versions are the same, the difference seems to be that you've removed all the arguments to `scale_x_datetime()`. With no arguments, the function makes a scale based on the correct time zone, but adding any arguments makes the whole thing default to UTC. Weird!

Original:  

```
structure(c(1445730513, 1446127062, 1446125752, 1445653711, 1446070072, 
            1446098841, 1446065691, 1446068301, 1446131775, 1445809457, 1446139230, 
            1446065777, 1446085553, 1446093400, 1445809372, 1446092407, 1445700436, 
            1446089994, 1445783652, 1446070240), class = c("POSIXct", "POSIXt"
            ), tzone = "America/Vancouver") %>% 
  data.frame(timestamp = .) %>% 
  mutate(hms = as.POSIXct(format(timestamp, "2015-01-01 %H:%M:%S"), 
                          tz = 'America/Vancouver')) %>% 
  ggplot(aes(x = hms)) +
  geom_histogram(binwidth = 60*60) +
  scale_x_datetime(date_labels = '%H%M%Z')
```

![scale_bad](https://cloud.githubusercontent.com/assets/7296482/11076227/87a5ec00-87ae-11e5-845d-ea3703b54436.png)

With `date_labels = '%H%M%Z'` removed:  

```
structure(c(1445730513, 1446127062, 1446125752, 1445653711, 1446070072, 
            1446098841, 1446065691, 1446068301, 1446131775, 1445809457, 1446139230, 
            1446065777, 1446085553, 1446093400, 1445809372, 1446092407, 1445700436, 
            1446089994, 1445783652, 1446070240), class = c("POSIXct", "POSIXt"
            ), tzone = "America/Vancouver") %>% 
  data.frame(timestamp = .) %>% 
  mutate(hms = as.POSIXct(format(timestamp, "2015-01-01 %H:%M:%S"), 
                          tz = 'America/Vancouver')) %>% 
  ggplot(aes(x = hms)) +
  geom_histogram(binwidth = 60*60) +
  scale_x_datetime()
```

![good_scale](https://cloud.githubusercontent.com/assets/7296482/11076231/8c566176-87ae-11e5-8101-ef6cc350a05c.png)

Note the difference in the x-axis. While ggplot makes a nice x axis with this sample data, that's not the case with the full dataset. So I need to use these parameters to clean things up:  

![crappy_labels](https://cloud.githubusercontent.com/assets/7296482/11076364/2f989b60-87af-11e5-874d-aae64d823291.png)

Check out that unnecessary addition of the month and day! 

Anyhow, your pre-processing solution clearly works like a charm, I'm just being obsessive about trying to get a pure ggplot solution.

**Comment by mstrimas** [comment]
And, for those following along, here's a `ggplot` solution I figured out. It requires defining a function that takes break points (i.e. dates) and returns a nice label:  

```
time_van_tz <- function(x) {
  format(x, format = '%H%M', tz = 'America/Vancouver')
}

questions %>% 
  mutate(hms = as.POSIXct(format(timestamp, "2015/01/01 %H:%M:%S"))) %>% 
  ggplot(aes(x = hms)) +
    geom_histogram(aes(y = ..count.. / sum(..count..)), binwidth = 60*60) +
    scale_x_datetime(date_breaks = '3 hours', labels = time_van_tz) +
    scale_y_continuous(labels = percent) +
    labs(x = 'Response Time (Vancouver)', y = '% Responses')
```

![finally](https://cloud.githubusercontent.com/assets/7296482/11076535/193f7112-87b0-11e5-8923-c121f4a04d43.png)

**Comment by aammd** [comment]
@mstrimas neat solution! how did you know that the `labels = ` argument could be a function -- and how did you know what such a function could write/return?
Also, i want to learn more about this `..count..` notation in ggplot, which i've seen before and which always makes me go cross-eyed.
In short, if there are links to any resources/help pages/vignettes that you used in this process would you mind dropping them in here?

**Comment by mstrimas** [comment]
For the `labels` argument, I stumbled across [this StackOverflow post](http://stackoverflow.com/questions/10339618/what-is-the-appropriate-timezone-argument-syntax-for-scale-datetime-in-ggplot), which gives a nice example. Also, in the documentation for `scale_x_datetime()`, under the `labels` argument, it states that, among other things, it can take "a function that takes the breaks as input and returns labels as output". However, there's no way I'd have ever uncovered this on my own.   

As for the `..count..` business, I'm still struggling to understand this, but as far as I know each `stat_` function in `ggplot` creates new variables of the form `..name..`, which can then be mapped to aesthetics. The RStudio `ggplot` [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/04/ggplot2-cheatsheet.pdf?version=0.99.761&mode=desktop) lists the new variables that each stat creates. So, within an `aes()` you can assign these new variables to whatever aesthetic you choose. The further layer of confusion for me was that many geoms call stats, and vice verse. So, `geom_histogram()` uses `stat_bin()` and therefore you can use these new variables that `stat_bin()` creates within `geom_histogram()`. In fact, the cheatsheet notes that `stat_bin(geom="bar")` is equivalent to `geom_histogram(stat="bin")`.  

I've only been using `ggplot` since September and am still pretty confused by the syntax at times. I don't find the built in documentation all that helpful, but I love that RStudio cheatsheet.
