### ISSUE TITLE
cant reopen the project built on todays class

### ISSUE THREAD

**Issue by min110** [STAT545-UBC/Discussion#236]
Any help is appreciated : 
I did get git tab in my new project in R studio by following the demo in today's class, `create`--->`use_git`--->reload R studio--> everything seems fine. but when I restart my mac after lunch, I got [this one] instead of git tab (https://cloud.githubusercontent.com/assets/10407001/11076565/406a04c8-87b0-11e5-9db7-af28f969c802.png)
<img width="476" alt="screen shot 2015-11-10 at 1 22 29 pm" src="https://cloud.githubusercontent.com/assets/10407001/11076565/406a04c8-87b0-11e5-9db7-af28f969c802.png">

**Comment by samhinshaw** [comment]
I see your project is named `tmp`, did you `create` your package in the `~/tmp` directory as @jennybc did?  If so, some of your files may have been cleared after reboot, [though it's hard to say](http://superuser.com/questions/187071/in-mac-os-x-how-often-is-tmp-deleted).

**Comment by jennybc** [comment]
Is the Project and package perhaps in a *subdirectory* of `tmp` instead of `tmp` itself? That would be a more typical choice.

**Comment by min110** [comment]
Thank you both! Yes, I did put it under tmp,here are the [files](https://cloud.githubusercontent.com/assets/10407001/11077337/85472928-87b4-11e5-8212-8bff7e7a0ff5.png)
<img width="197" alt="screen shot 2015-11-10 at 2 07 20 pm" src="https://cloud.githubusercontent.com/assets/10407001/11077337/85472928-87b4-11e5-8212-8bff7e7a0ff5.png">
, but git disappeared . SO do other projects(I mean I lost git lab in all the projects I created before). ....

**Comment by jennybc** [comment]
RStudio hides most dot files, including the `.git` directory all of your git repos will have. It only reveals the ones it thinks you might want to edit. Try `dir(all.files = TRUE)` in R to see a listing of current working directory, including dot files.

However it is always possible that somehow the Git-repository-ness of your `tmp` project has been lost. Or was never there? You can call `use_git()` again. It won't hurt anything either way.
