### ISSUE TITLE
Stretching out a scatterplot

### ISSUE THREAD

**Issue by molliejmcdowell** [STAT545-UBC/Discussion#237]
Hi all,

This is a subject I feel like I should have mastered at this point, but is there a way to stretch out the axes on a scatterplot (for instance, the y axis when it's full of candy names all overlapping each other) without using ggsave?

thanks!
mollie

**Comment by bdacunha** [comment]
yes! I have the same issue with this... is there any way in which we can make the plot larger? This candy survey has so many candy names that they all squeeze and it's hard to read

**Comment by sho-87** [comment]
if youre using r markdown you can use something like `{r fig.width=10, fig.height=15}` at the start of the block to adjust the figure size

**Comment by bdacunha** [comment]
woohooo! thanks!! it works :) I had no idea about that!!!

**Comment by molliejmcdowell** [comment]
YAY THANKS SIMON!

**Comment by samhinshaw** [comment]
I was having this issue as well. @sho-87's solution worked for me in the HTML rendering created by knitr, but GitHub would not honor the figure size when it rendered the HTML from the `.md` file.  What I [ended up doing](https://github.com/samhinshaw/randomstuff/blob/master/candy_data/homework7.md)), was to use `ggsave(dir/filename.png, scale = 1.7)`, and then calling that file with `![alt text](dir/filename.png)`.  This workaround does not seem ideal, however. 

Did this work for you once you've pushed to github, @molliejmcdowell?

**Comment by molliejmcdowell** [comment]
yes it did work for me @samhinshaw ([md](https://github.com/STAT545-UBC/mollie_mcdowell/blob/master/Homework/Homework7/Homework7.md))... I have no idea why it wouldn't work for you so I'll tag @sho-87

**Comment by samhinshaw** [comment]
Thank you for the link--it does seem to be working now, so odd that it wasn't before. 
Fortunately with the magic of version control I can go back in time & see exactly what I tried versus what you've suggested now.  Embarrassingly, it seems like I just wasn't setting the `fig.width` & `fig.height` values high enough. Thank you for the tips! 

Semi-related, github has some very cool tools for examining the difference between two figures in a commit.
