### ISSUE TITLE
Statistics question - Normalizing a symmetrical matrix so the diagonal is 1

### ISSUE THREAD

**Issue by hui-tony-zk** [STAT545-UBC/Discussion#238]
I made a [heatmap](https://github.com/STAT545-UBC/tony_hui/tree/master/Homeworks/Homework_7#plot-the-result), where the colors represent the number of times two candies are liked by the same person. 
![unnamed-chunk-22-1](https://cloud.githubusercontent.com/assets/8253336/11110121/02c9c740-88ad-11e5-9656-a25ffeae8126.png)

The matrix (symmetrical) looks like this:

|                                                                       | Butterfinger| a100_Grand_Bar| Anonymous_brown_globs_that_come_in_black_and_orange_wrappers| Any_full_sized_candy_bar|
|:----------------------------------------------------------------------|------------:|--------------:|------------------------------------------------------------:|------------------------:|
|Butterfinger                                                           |         3735|           2569|                                                          399|                     3481|
|a100_Grand_Bar                                                         |         2569|           3141|                                                          344|                     2966|
|Anonymous_brown_globs_that_come_in_black_and_orange_wrappers           |          399|            344|                                                          501|                      461|
|Any_full_sized_candy_bar                                               |         3481|           2966|                                                          461|                     4501|
|Black_Jacks                                                            |          251|            235|                                                           75|                      283|
|Bonkers                                                                |          379|            369|                                                           75|                      468|
|Bottle_Caps                                                            |         1442|           1239|                                                          214|                     1744|
|Box_o__Raisins                                                         |          353|            325|                                                           86|                      481|
|Brach_products__not_including_candy_corn_                              |          794|            745|                                                          178|                      965|
|Bubble_Gum                                                             |          904|            770|                                                          143|                     1178|
|Cadbury_Creme_Eggs                                                     |         2200|           1851|                                                          298|                     2645|
|Candy_Corn                                                             |         1470|           1203|                                                          265|                     1722|
|Vials_of_pure_high_fructose_corn_syrup                                 |          545|            444|                                                           94|                      688|

However, the problem is that the colors represent "number of times both candies were liked", but obviously this number will be higher if one candy is liked more than another candy (e.g. the diagonal isn't constant).

Is there a way to normalize this so that the diagonal is 1? What's the best strategy to go about doing this?

Here's a minimum reproducible code (copy+pasting should just work):

```
require(dplyr)
require(readr)
require(ggplot2)
require(tidyr)

candy_raw <- read_csv("http://hui-tony-zk.github.io/CANDY-HIERARCHY-2015%20SURVEY-Responses.csv", col_types = cols(Timestamp = col_datetime("%m/%d/%Y %H:%M:%S")))

candy_clean <- candy_raw %>%
  mutate(age = as.integer(`How old are you?`),
         trickortreat = ifelse(`Are you going actually going trick or treating yourself?` == "Yes", TRUE, FALSE)) %>%
  select(-`How old are you?`, -`Are you going actually going trick or treating yourself?`) %>% 
  select(trickortreat, age, one_of(grep("^\\[", colnames(candy_raw), value = T))) %>% filter(age >= 10, age <= 80)

colnames(candy_clean) <- gsub(pattern = "\\[|\\]", replacement = "", x = colnames(candy_clean))
colnames(candy_clean) <- gsub(",.*", "", colnames(candy_clean)) # replace everything after an instance of a comma
colnames(candy_clean) <- gsub("^([0-9])(.*)", "a\\1\\2", colnames(candy_clean)) # add leading a's
colnames(candy_clean) <- gsub("[^[:alnum:]]", "_", colnames(candy_clean)) # replace everything that's not alphanumeric 

candy_clean$id <- 1:nrow(candy_clean)

candy_clean[candy_clean == "JOY"] <- 1
candy_clean[candy_clean == "DESPAIR"] <- -1

candy_clean <- candy_clean[is.na(candy_clean[,c(-1,-2)]) %>% rowSums() <= 45, ]

just_candies <- candy_clean[,c(-1, -2)] %>% select(-id)

co_liked_candies <- function(df, candy) {
  candy_of_interest <- df %>% filter_(paste(candy, "== 1"))
  candy_of_interest[is.na(candy_of_interest)] <- 0
  candy_of_interest[candy_of_interest == -1] <- 0
  candy_of_interest[candy_of_interest == 1] <- 1
  candy_of_interest_sums <- candy_of_interest %>% data.matrix() %>% colSums()
  candy_of_interest_sums_df <- data.frame(likes = candy_of_interest_sums
  ) %>% setNames(candy)
  rownames(candy_of_interest_sums_df) <- names(candy_of_interest_sums)
  return(candy_of_interest_sums_df)
}

all_candy_counts = list()
for (candy in colnames(just_candies)) {
  all_candy_counts[[candy]] <- co_liked_candies(df = just_candies, candy = candy)
}

all_candy_counts <- bind_cols(all_candy_counts) %>% data.matrix()

rownames(all_candy_counts) <- colnames(just_candies)

png(filename = "test.png", width = 8, height = 8, units = "in", res = 72)
heatmap(x = all_candy_counts, scale = "none")
dev.off()
```

**Comment by jennybc** [comment]
It seems like you might want to compute something like the Jaccard Index:

https://en.wikipedia.org/wiki/Jaccard_index

It will live in [0, 1] and it will be 1 on the diagonal. In general, the type of heat map you're making is akin to a correlation heat map, so you want to look at reasonable measures of (dis)similarity for vectors of zeroes and ones, i.e. binary data.

It looks like the [ade4 package](https://cran.r-project.org/web/packages/ade4/index.html) has a [`dist.binary()`](http://pbil.univ-lyon1.fr/ade4/ade4-html/dist.binary.html) function that might be useful.
