### ISSUE TITLE
Having problems with creating the "Makefile" or ".Renviron" file?

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#242]
When creating these files, notice that they do not have an extension. The files are not called "Makefile.R" or ".Renviron.R".

If you create a file from RStudio using the "File" --> "New File" --> "R Script" menu, then RStudio will automatically add ".R" to the end of your filename. If you are trying to create a Makefile or .Renviron, you DO NOT want to have ".R" added to the filename! So instead, you can create a new file using the menu "File" --> "New File" --> "Text File".

I saw 6 students today who had problems getting things to work because they created a file using the "R Script" menu.  Just something to keep in mind.

@jennybc maybe it should be mentioned somewhere in the course content, not sure where/when

**Comment by jennybc** [comment]
I've put that into the lesson now.
