### ISSUE TITLE
How to check 2 variables which one has the higher value and take the higher value to put in a new variable

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#243]
Hello,

I have question which  might have a really fast and easy answer, but I cannot find help on the internet and I didn;t really get the hang of 'for-loops' and can't find a 'Hadley' / 'dplyr' solution either.

What I want to do is: When I have two variables with different values, I want to create a third variable which contains the higher value of both of them. E.g.
```{r}
var1 <- as.data.frame(c(1, 10, 100))
var2 <- as.data.frame(c(5, 20, 80))


df <- bind_cols(var1, var2)

**Comment by ksamuk** [comment]
Not sure I fully understand, but how about `var3 <- c(max(var1), max(var2))`?

**Comment by ahippman** [comment]
it should give me 
`var3` as a list of 5, 20, 100 , as 5 is larger than 1, 20 larger than 10 and 100 larger than 80

**Comment by mstrimas** [comment]
They may be a prettier way, but these should work:  
`aaply(cbind(var1, var2), 1, max)`  
`plyr::aaply(cbind(var1, var2), 1, max)`

**Comment by ksamuk** [comment]
Ah, `rowwise()` is what you seek:

```{r}
library(dplyr)

var1 <- c(1, 10, 100)
var2 <- c(5, 20, 80)

df <- data.frame(var1, var2)

df %>%
  rowwise() %>%
  mutate(var3 = max(var1, var2))

```

**Comment by ksamuk** [comment]
Matt's solution also works!

**Comment by ahippman** [comment]
@mstrimas, so this gives me a nice matrix which shows the right values in the diagonal, but how do I get those values into a nice variable?
```{r}
> plyr::aaply(cbind(var1, var2), 1, max)
             c(5, 20, 80)
c(1, 10, 100)  5 20  80
          1    5 NA  NA
          10  NA 20  NA
          100 NA NA 100
```

@ksamuk , this gives me `var3 = c(100, 100, 100)`, so filled wiht the one max value of both variables
```{r}
  c(1, 10, 100) c(5, 20, 80)  var3
          (dbl)        (dbl) (dbl)
1             1            5   100
2            10           20   100
3           100           80   100
```

**Comment by ksamuk** [comment]
Did you run the code block as I have it there? Your original code doesn't keep the dplyr columns named 'var1' and 'var2'.

**Comment by ahippman** [comment]
Awesome!!!! I don't know exactly why it didn't do it before (I was pretty sure I copied and pasted it then, as well) but now it gives the exact right values!!!!! YEAY!!!

THANK you guys!!!!!

**Comment by jennybc** [comment]
There's also `pmax()` and `pmin()`. Throw that inside `mutate()` to create the new variable you want.

**Comment by ahippman** [comment]
Ahhhhh, that's what it means by `element wise` in the `dplyr` cheat sheet! Thanks
```{r}
> df %>% 
+   mutate(var3 = pmax(var1, var2))
  var1 var2 var3
1    1    5    5
2   10   20   20
3  100   80  100
```
