### ISSUE TITLE
Using the GitHub API

### ISSUE THREAD

**Issue by samhinshaw** [STAT545-UBC/Discussion#244]
Are there any git clients aside from the official GitHub client that use the GitHub API? I haven't been able to find any on linux. I'm trying to create a GitHub repository without having to go to github.com, and @jennybc's `devtools::use_github()` seems to fail if your R Project is not a package (unless I am missing something).  
This can be done via command line using [github's API](https://developer.github.com/v3/repos/#create):
`curl -u '<username>:<Token>' https://api.github.com/user/repos -d '{"name":"<repo name>"}'`
(Replace <username> with your GitHub username, <token> with a Personal Access Token and <repo> with your repository name.)

Then `cd` to your repo's directory and add remote tracking with SSH:
`git remote add origin git@github.com:<username>/<repo name>.git`
or with https:
`git remote add origin https://github.com/<username>/<repo name>.git`

And then push
`git push origin master`

Of course the stackoverflow community [has plenty of suggestions](http://stackoverflow.com/questions/2423777/is-it-possible-to-create-a-remote-repo-on-github-from-the-cli-without-ssh), including some ways to turn the above code into a script. 

I guess I'm just surprised that nobody has baked this into R/RStudio or created another GUI for it.  Could this be turned into a function or package using `base::system()`?

**Comment by jennybc** [comment]
Here's how to create (and delete) a repo on GitHub via API through R. It requires installing a GitHub-only package `gh`. I will add info on the remote tracking business in a second comment.

``` r
#devtools::install_github("gaborcsardi/gh")

# make sure you have GitHub PAT stored in GITHUB_TOKEN environment variable
# Sys.getenv("GITHUB_TOKEN")
# if you plan to delete repos, you'll need to add the delete_repo scope, which is
# NOT selected by default

library(gh)

## https://developer.github.com/v3/repos/#create
res <- gh("POST /user/repos", name = "testrepo")

## did it work?
attributes(res)$response$status
#> [1] "201 Created"

## note you could also pass other parameters such as:
## description
## private TRUE/FALSE
## auto_init TRUE/FALSE whether to initialize w/ a README
## etc etc

## now get rid of it
res <- gh("DELETE /repos/:owner/:repo", owner = "jennybc", repo = "testrepo")

## did it work?
attributes(res)$response$status
#> [1] "204 No Content"
```

**Comment by samhinshaw** [comment]
This is very helpful, thank you! I think it is actually helpful to have separate auth tokens (`GITHUB_TOKEN` versus `GITHUB_PAT`) to reduce the chances of accidentally deleting a repository.  
Perhaps...
```
create_repos <- function(x) {
	stopifnot(is.character(x))
	res <- gh("POST /user/repos", name = paste(x))
	return(attributes(res)$response$status)
}
create_repos("willynilly")
```
And thank you for the wise words of caution, Dean. That hadn't crossed my mind...

**Comment by jennybc** [comment]
I still plan to post about creating and tracking a remote. While I was developing that bit ... I hit my personal limit on private remotes then got sidetracked with other stuff!

**Comment by jennybc** [comment]
@samhinshaw Good idea about the separate tokens! In my example I'm using the same token -- mine has all the necessary scopes already. Here's how to create the remote and the branches set up for pushing/pulling from GitHub. I do plan to put this in a package with some other git and github helpers, once this teaching calms down! Because right now, it's probably easier to just do this from the shell.

``` r
# devtools::install_github("gaborcsardi/gh")
# install.packages("git2r")

library(gh)
library(git2r)

# make sure you have GitHub PAT stored in GITHUB_TOKEN environment variable
# Sys.getenv("GITHUB_TOKEN")
# if you plan to delete repos, you'll need to add the delete_repo scope, which is
# NOT selected by default

## https://developer.github.com/v3/repos/#create
res <- gh("POST /user/repos", name = "borat", private = TRUE,
          description = "Wisdom from Big Data Borat")

## did it work?
attributes(res)$response$status
#> [1] "201 Created"

# init local git repo (if not already done?)
r <- git2r::init(getwd())
writeLines("Does this storage enclosure make my data look big?", "README.md")
add(r, "README.md")
commit(r, "First commit message")

# pick a protocol
protocol <- "https"
#protocol <- "ssh"
origin_url <- switch(protocol, https = res$clone_url, ssh = res$ssh_url)

# add the remote
git2r::remote_add(r, "origin", origin_url)

# push the initial commit
if (protocol == "ssh") {
  ## assume ssh keys live in the normal place and that ssh-agent is serving the passphrase
  git2r::push(r, "origin", "refs/heads/master")
}

if (protocol == "https") {
  cred <- git2r::cred_user_pass("EMAIL", Sys.getenv("GITHUB_TOKEN"))
  git2r::push(r, "origin", "refs/heads/master", credentials = cred)
}

## set upstream tracking branch
git2r::branch_set_upstream(git2r::head(r), "origin/master")

## now get rid of it of the test repo if you wish
#res <- gh("DELETE /repos/:owner/:repo", owner = "jennybc", repo = "borat")

## did it work?
#attributes(res)$response$status
```
