### ISSUE TITLE
GITHUB_PAT

### ISSUE THREAD

**Issue by wang114** [STAT545-UBC/Discussion#245]
I saved my `GITHUB_PAT=<token>` in a  `.Renviron` file, but when I use `check()` or `build&reload`, I got the following error message.

Error in eval(expr, envir, enclos) (from Users:apple.R#1) : 
  object 'af42edd0cfdbe.......2b2bb2d57f66ba3' not found

`Sys.getenv("GITHUB_PAT")` works fine.

**Comment by jennybc** [comment]
You should delete this PAT now that it's out on the internet!

It sounds like something's still not quite right with your .Renviron file.

It should have this form:

https://github.com/jennybc/system-setup/blob/master/dotfiles/.Renviron_INDICATIVE

You don't want the `<` and `>` signs in the `.Renviron`. Is that maybe where we are miscommunicating?

**Comment by wang114** [comment]
My `.Renviron` files contains the following 3 lines

GITHUB_TOKEN=af42edd0cfdbeafb09f951eb12b2bb2d57f66ba3
GITHUB_PAT=af42edd0cfdbeafb09f951eb12b2bb2d57f66ba3
NOT_CRAN=true

(Just as an example, I will use another PAT). I tried to save this file in the R folder containing my package and saved it under whatever `normalizePath("~/")`shows. Neither worked.

**Comment by jennybc** [comment]
How does this involve `check()` or Build and Reload? Neither of them should be doing anything with GitHub.

**Comment by wang114** [comment]
I now have this error message so `Build&Reload`, `Document`both failed.

**Comment by jennybc** [comment]
> I now have this error message so Build&Reload, Documentboth failed.

I don't know what this means. What error message?

**Comment by wang114** [comment]
when I use `Load All` or `Build&Reload`, it showed up an error message as:

Error in eval(expr, envir, enclos) (from Users:apple.R#1) : 
object 'af42edd0cfdbe.......2b2bb2d57f66ba3' not found


I found that was because I put the `.Renviron` file under the wrong folder. Now it's fixed.  Thank you.
