### ISSUE TITLE
Homework 8 questions

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#246]
A few questions about this weeks homework:

1. What is meant by "Document all exported functions."? There is reference to a document() function. I assume this is different from just documenting how a function works in a readme file?

2. Did we cover vignettes in class? What purpose do they have beyond what a readme file brings to the table?

**Comment by jennybc** [comment]
> Document all exported functions.

I want to be able to use `?foo` to read official R help in the normal way on any function `foo()` in your package. So you need to write that roxygen comment and then use `devtools::document()` to convert it to the proper files that ... eventually give rise to R help.

> Did we cover vignettes in class?

Um sort of? We've looked at vignettes for package we use, such as `dplyr`. And part 2 shows how to create one.

> What purpose do vignettes have beyond a README?

Vignettes are an official type of package-level documentation. If you submitted a package to CRAN with a vignette, it would ship with the package and be available to users through various mechanisms:

https://stat.ethz.ch/R-manual/R-devel/library/utils/html/vignette.html

http://r-pkgs.had.co.nz/vignettes.html

OTOH a README is really more of a GitHub thing. There is no guarantee that anyone other than keeners would see this. In our setting, I'm happy for the content to be the same. In the real world, they are quite different.
