### ISSUE TITLE
Error while connecting to Github : homework 08 

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#248]
In the foofactors package, when creating a companion repo on Github, I get a PAT, stow it in .Renviron but get the following error with use_github: 
Using github PAT from envvar GITHUB_PAT

* Creating GitHub repository
* Adding GitHub remote
Error in validObject(.Object) : 
  invalid class "git_repository" object: Invalid repository

Github shows a repo named foofactors, but the push/pull option in my R project is greyed out. I do have git files in my project so it's using git locally. 

Any ideas as to what's going wrong? 

Thanks!

**Comment by jennybc** [comment]
It's really hard to say. It might be worth undoing then redoing the `use_git()` and `use_github()` steps. Let me know if you don't know where to start.

**Comment by jennybc** [comment]
But it smells a bit like a protocol problem? Be really careful that you specify "https" vs "ssh" in `use_github()` according to how you usually authenticate and what is already set up.

**Comment by Poush87** [comment]
I use ssh to authenticate and left the protocol field blank in use_github. 
Would be great if you could tell me how to 'undo' use_git() and use_github()! 

Thanks Jenny!

**Comment by jennybc** [comment]
Are your ssh keys associated with a passphrase? Is ssh-agent already configured to provide it?

More in a bit about resetting wrt all things got....

**Comment by Poush87** [comment]
The ssh key doesn't have a passphrase - I can push/pull from stat545 repo, that should mean that the ssh-agent is configured to provide it, right?

**Comment by jennybc** [comment]
Re: undoing `use_git()`, you just need to delete the `.git` directory. RStudio will not reveal that to you. So, if your OS shows you dotfiles, do it any way you normally delete files. I would use Emacs or do it in the shell. In the shell, with working directory set to the Project, `rm -rf .git` should do the trick.

Re: undoing `use_github()` you need to delete the GitHub repo that got created.

These two steps mean your work is no longer under version and is not backed up on GitHub, so you should probably make a local copy of the Project before you start messing around.

Then maybe try again before we do further troubleshooting.

What OS are you on?

**Comment by jennybc** [comment]
Are you definitely running `use_git()` and `use_github()` with working directory set to the top-level directory of your package, which is also an RStudio Project, which is also a Git repository? I am wondering if this is a working directory problem now.

**Comment by Poush87** [comment]
I was running use_git() and use_github() in the top-level foofactors directory, but I had a local git repo initialised in the home directory, which is what was creating an issue I think. I've deleted the local git directory and re-initialised everything. Seems to work fine now! 
Thanks a lot :)
