### ISSUE TITLE
Error when running make: "there is no package called ..." + solution

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#250]
If you are trying to run your Makefile and are trying to load a package that results in the above error, it means you need to tell `make` where to find the package.

For example, if you you a line like this in your Makefile

```
Rscript -e "library(ggplot2); ggplot() + geom_point()"
```

You might get an error

```
Error in library(ggplot2) : there is no package called ‘ggplot2’
```

That error may seem strange because you know that you definitely have ggplot2 installed. The likely problem is that it is installed a different directory than the one `make` is looking in. One possible fix to this is the following.

In RStudio, run `.libPaths()` -- this will print out a vector of the locations where R looks for packages. You might see output like this

```
[2] "C:/Users/Dean/Documents/R/library" "C:/Program Files/R/R-3.2.2/library"
```

So you want to tell `make` to also look in those same directories.  You do this by giving those directories as a input to the `.libPaths()` function in the Makefile command.  That means you take the output from above, make it into a vector by surrounding it in `c()` and adding a comma in the middle, and give that as an argument `.libPaths()` before calling `library(ggplot2)`.  So the line in the Makefile that tries to load ggplot2 now becomes

```
Rscript -e ".libPaths(c("C:/Users/Dean/Documents/R/library", "C:/Program Files/R/R-3.2.2/library")); library(ggplot2); ggplot() + geom_point()"
```

Talk to us if you're having this problem and don't understand the solution.

@AdrianLJones feel free to share your specific error and your specific solution

**Comment by daattali** [comment]
Alternatively, you could put the R code inside an R script and call the script instead of running ggplot2 straight from the Makefile

**Comment by Haycen** [comment]
Hi,

I'm having the same error but all my R code is in a R file.

Here what my Makefile looks like:

```
all: lifeVSyear_country.tsv

clean:
	rm -rf *.tsv

gapminder.tsv:
	curl -O https://raw.githubusercontent.com/jennybc/gapminder/master/inst/gapminder.tsv

gapminder_ordered.tsv: 01_exploratory_analyses.R gapminder.tsv
	Rscript $<

lifeVSyear_country.tsv: 02_statistical_analyses.R gapminder_ordered.tsv
	Rscript $<
```

And the error is: 

```
Rscript 01_exploratory_analyses.R
Error in library(dplyr) : there is no package called 'dplyr'
Execution halted
make: *** [gapminder_ordered.tsv] Error 1
```

**Comment by AdrianLJones** [comment]
@daattali Sorry I didn't notice this in the volume, I have one thing to add, that hopefully will fix @Haycen 's problem. 

For some reason that isn't clear to me, even if I call the Rscript that works fine (ie I'm NOT running the lines in the shell but rather doing `Rscript $<` to call a .R file) the installed package will NOT be found.  

My solution has been to include the .libPaths command at the top of the Rscript I write so that when it is run from make it then knows where to go looking.  This feels kludgy, but it gets the job done.

For example at the top of every .R file I'm using in the make stream I have:

> .libPaths(c( "C:/Users/Adrian/Documents/R/win-library/3.2", "C:/Program Files/R/R-3.2.2/library"))

Where the c(*) was copy and pasted from the output of `.libPaths()` when run inside RStudio where all my packages load happily.  

Hope that helps

Adrian

**Comment by Haycen** [comment]
Haha Yes @AdrianLJones, I agree it's not ideal but it's working for me. Thanks

**Comment by Haycen** [comment]
For this issue, I think I understood what is happening but I couldn't find a way to properly fix it.

Usually, your package are installed in two directory. The original one that contains all the packages that come by default with R ("C:/Program Files/R/R-3.2.2/library"), and a second directory somewhere else on your computer where you install additional packages ("C:/Users/Haycen/Documents/R/win-library/3.2"). That way when you update your R version you don't have to copy paste or reinstall all your new packages. 

If you have this kind of structure, 'make' will check only in the first directory  ("C:/Program Files/R/R-3.2.2/library") and of course won't be able to find the packages. So we have to find a way to tell make to check in both repositories the same way R works.

On my other computer I just have one repository that contains all my packages. So, I don't have any problem.

Haycen

**Comment by ksamuk** [comment]
Have a look at the **second** solution here:

http://stackoverflow.com/questions/15170399/changing-r-default-library-path-using-libpaths-in-rprofile-site-fails-to-work

**Comment by Haycen** [comment]
Thanks @ksamuk
