### ISSUE TITLE
Error when running make: "Rscript command not found"

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#252]
When trying to run their Makefile from RStudio, some students reported getting an error that said something along the lines of "Rscript not found" (exact wording might be off).

If this happens to you, it's probably because `make` doesn't know where to find the `Rscript` tool. There are two things you can.

1. You can just reinstall R and usually it will fix this problem.

2. You can find out where it is and tell `make` about it. To find out where it is, run `R.home("bin")`. This is where R is installed, and Rscript should be at that location as well. After finding out where Rscript is, you will need to add it to your PATH. The way to edit your PATH is different for every single OS and OS version, so you'll have to Google for "how to edit PATH variable <insert your OS name>". In our case, we would want to add `/usr/lib/R/bin` to the PATH.

**Comment by jennybc** [comment]
I suspect the people affected by this have upgraded from Yosemite to El Capitan.

Read this:

https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16469

Or just make note of the bottom line: if you upgrade, you'll need to reinstall R.

> Upgrading to El Capitan will move /usr/bin/{R,Rscript} to under /Library/SystemMigration, so CRAN binary installations should be re-installed.
