### ISSUE TITLE
Force dependency install

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#253]
I'm trying to install my own package from github but it keeps complaining about how certain packages are missing:

`Error in library(curl) : there is no package called ‘curl’`

This is despite having added the package to `Imports` in the description file

Is there another way to force the download of a dependency? Everything works when I manually install the other packages but that seems like a lot of work for users

**Comment by jennybc** [comment]
Substitute your account and package name into this:

`install_github("jennybc/foofactors", dependencies = TRUE)`

**Comment by sho-87** [comment]
That results in the same error:

This is my description file: https://github.com/sho-87/Romdb/blob/master/DESCRIPTION

I've tried adding the required dependencies to Depends, Imports, and Suggests, and it still complains that the required packages are missing after trying to install with `dependencies = TRUE`

**Comment by daattali** [comment]
I just looked at the DESCRIPTION file you linked to.  It doesn't look like you added `curl` to it.  You need to put it under Imports, Depends, or Suggests

**Comment by sho-87** [comment]
They were there before but I removed them

I'll add them back now, but previously I had curl (and others) in those locations but they still werent installing

**Comment by daattali** [comment]
I just tried installing your package and running functions from it and it was all fine

```
devtools::install_github("sho-87/Romdb")
library(Romdb)
Romdb::get_movie("Shrek")
```

no problems

**Comment by sho-87** [comment]
cool. does it work if you manually remove curl first though? Not sure if it will install dependencies automatically

**Comment by daattali** [comment]
If it's inside "Imports" it should. If it's inside "Suggests" it won't.  That's in theory what should happen. I don't want to deal with installation and uninstalling packages right now. If you want to test it out on fresh R installation you can try to find a website that lets you run R code and try from there. I don't recall any such websites but I did see a couple recently so they exist
