### ISSUE TITLE
Error in DESCRIPTION file

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#254]
On running check() on both my package and the packahge forked from github STAT-545 repo, I get the following error:
checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... ERROR

the check.log file says:
checking DESCRIPTION meta-information ... ERROR

Here's my DESCRIPTION file:
Package: foofactors
Title: Manipulate factors as you will
Version: 0.0.0.9000
Authors@R: person("Poushali", "Maji", email = "poushali.maji@gmail.com", role = c("aut", "cre"))
Description: This package performs functions on factors, like binds 2 factors
    into one. Factors have driven people to extreme measures, like ordering custom
    conference ribbons and laptop stickers to express how HELLNO we feel about
    stringsAsFactors. And yet, sometimes you need them. Can they be made less
    maddening? Let's find out.
Depends:
    R (>= 3.2.2)
License: MIT + file LICENSE
LazyData: true
RoxygenNote: 5.0.1
Suggests:
    testthat,
    knitr,
    rmarkdown
Imports:
    dplyr
URL: https://github.com/Poush87/foofactors
BugReports: https://github.com/Poush87/foofactors/issues
VignetteBuilder: knitr

Seems to me an exact copy of what we did in class/Jenny's DESCRIPTION file. 
Ideas as to where I'm going wrong?

The LICENSE file looks like this:
YEAR: 2015
COPYRIGHT HOLDER: Poushali Maji

Thanks!

**Comment by jennybc** [comment]
Indent the Description field. It has to be EXACTLY like the one I posted.

**Comment by jennybc** [comment]
In fact you may have other indentation problems as well. How did you lose all of that?

**Comment by Poush87** [comment]
Package: foofactors
Title: Manipulate factors as you will
Version: 0.0.0.9000
Authors@R: person("Poushali", "Maji", email = "poushali.maji@gmail.com", role = c("aut", "cre"))
Description: This package performs functions on factors, like binds 2 factors
    into one. Factors have driven people to extreme measures, like ordering custom
    conference ribbons and laptop stickers to express how HELLNO we feel about
    stringsAsFactors. And yet, sometimes you need them. Can they be made less
    maddening? Let's find out.
Depends:
    R (>= 3.2.2)
License: MIT + file LICENSE
LazyData: true
RoxygenNote: 5.0.1
Suggests:
    testthat,
    knitr,
    rmarkdown
Imports:
    dplyr
URL: https://github.com/Poush87/foofactors
BugReports: https://github.com/Poush87/foofactors/issues
VignetteBuilder: knitr


Ah sorry, the indentation went missing when I pasted the text here! 
That's what my file looks like.

**Comment by Poush87** [comment]
Oh well - pasting messes things up! I checked the indentation and it looks exactly like your file.

**Comment by jennybc** [comment]
Format code and code link things as fenced code blocks:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by jennybc** [comment]
It just says `ERROR` and that's all? No actual error message given? Does that happen when you `check()` a fresh fork of the `foofactors` package I've made available, i.e. before you have edited anything?

**Comment by Poush87** [comment]
Yep it happens with a fresh fork of the foofactors package. 
Here's the full error message:
checking DESCRIPTION meta-information ... ERROR
Status: 1 ERROR

Error: Command failed (1)
Execution halted

Exited with status 1.
