### ISSUE TITLE
Error while using use_github()

### ISSUE THREAD

**Issue by arunmarria** [STAT545-UBC/Discussion#255]
I tried doing this **use_github()**. But I got following error. How can it be corrected?

Using github PAT from envvar GITHUB_PAT
* Creating GitHub repository
Error: Validation Failed (422)
*  name already exists on this account

As a result I am unable to push and pull

**Comment by jennybc** [comment]
This means that you already have a repo on GitHub with the same name as the one `use_github()` is trying to create. Perhaps from an earlier attempt at doing same? Delete the same-named repo on GitHub and it should work.

**Comment by arunmarria** [comment]
I tried doing that but this time I am getting this error
Using github PAT from envvar GITHUB_PAT
* Creating GitHub repository
* Adding GitHub remote
Error in validObject(.Object) : 
  invalid class “git_repository” object: Invalid repository

**Comment by jennybc** [comment]
Now I suspect you have one or both of these problems:

  * working directory at the time you do `use_git()` and/or `use_github()` is not set to the top-level directory of your Project which is your package which is a Git repo
  * your Project which is your package which is your Git repo is sitting inside (directly or indirectly) another Git repo

**Comment by arunmarria** [comment]
My working directory is set to the top level. So what I think is it's the second problem.

**Comment by arunmarria** [comment]
I tried doing again after restarting everything and confirming my working directory. This time I got following message in console but repo was not created
 use_github(protocol = "https")
Using github PAT from envvar GITHUB_PAT

**Comment by jennybc** [comment]
I think you need to completely reset the Git and GitHub status of this package and start over. I am taking note of all this and will propose some changes in `devtools::use_git()` and `devtools::use_github()`. So it's really helpful to see how they can be hard to use.

I explain how to "power cycle" the Git/GitHub status of your Project and package here: https://github.com/STAT545-UBC/Discussion/issues/248#issuecomment-158269696

But you will not be able to initiate a Git repo in your Project = package if it is sitting inside another Git repo. You need to make that not be the case.

**Comment by arunmarria** [comment]
I tried following the steps you told by undoing use_git(). But again I get
Using github PAT from envvar GITHUB_PAT
But no repo is created; before that Repo was created but I was unable to push/pull.
I have created a new package for homework and kinda used same strategy as for foofactors but was successful in doing that and I am able to push and pull into that.
