### ISSUE TITLE
How to do unit testing if the function is used to draw a table or a figure?

### ISSUE THREAD

**Issue by LinaQiu** [STAT545-UBC/Discussion#257]
Hi @jennybc ,

While I was working on this week's homework, originally I planned to create a R package for the three functions, namely [my_lmfit(), my_plot() and my_table()](https://github.com/STAT545-UBC/lina_qiu/blob/master/STAT545/Homework04/Homework04.md), I wrote for Homework4. But then, I came up with several problems. I have no idea about how to do unit testing for these three functions. Probably I would stop here and try to start with something simpler, like `foofactors` you have written at class, as it would be a best way for a R novice to learn how to write a R package. However, I still want to figure out if the R package contains several functions which are used for making a table or plotting a figure, how should we do the unit testing in this situation? 

Thanks.
Lina

**Comment by jennybc** [comment]
I haven't looked specifically at your package or functions. But yeah you have wandered into area that's definitely beyond the scope of this class.

If the output is a *table*, that seems like a fairly straightforward testing situation to me. Can you explain the difficulties you are having here? Also have a look at `testthat::expect_equal_to_reference()` which can be handy when you want to generate some complicated object as a reference, then test that you keep getting same in the future.

Testing a figure is a different matter and I've never done it. It is legitimately hard but I know people in the vis and webby side of R have some approaches. I would have to do some research or consultation to give you leads there.

**Comment by LinaQiu** [comment]
Hi Jenny,

Thanks for your reply. Actually, I have not yet go to the step to write the unit test for the function `my_table()` I mentioned above. I am still working at the first one, `my_lmfit()`. But while I am thinking about how to do unit  test for my first function, I suddenly realize that I am short of ideas on what should I test at unit testing part. Thus, my problem probably would be when the output of a function is a table, what should I test for... Should I just test whether the output of my function is a table or not? Or should I compare all values in the output table I get after calling `my_table()` function with a predefined correct table?

Thanks,
Lina

**Comment by jennybc** [comment]
Both of your ideas are sound: test that you get the right sort of object back and, in the simplest situation possible, test that you get some very exact object back. Then I suggest you add a test for an error or warning when the function is given obviously bad input.

**Comment by LinaQiu** [comment]
I see. So that means I have two different choice for unit test: one is to test whether my function can provide me with correct results, another one might be whether my function would output correct error or warning message while it was given a bad input, right?

Thanks,
Lina

**Comment by jennybc** [comment]
Yes. If you look at the various `expect_*` functions in `testthat`, you'll see there are options for many situations: exact equality, object has a certain class, call produces an error, etc. Literally type `testthat::expect_` into RStudio and just look at the auto-completions. Then go read the help and examples on a few that look relevant.

**Comment by LinaQiu** [comment]
Okkk. I think I know how to deal with "test" now! Thank you so much. 

Lina
