### ISSUE TITLE
What should I do if I want to use gapminder dataset in my R package? 

### ISSUE THREAD

**Issue by LinaQiu** [STAT545-UBC/Discussion#259]
Hi @jennybc ,

I came across with some problem when I am doing homework8. I am trying to re-write my function in [Homework4](https://github.com/STAT545-UBC/lina_qiu/blob/master/STAT545/Homework04/Homework04.md), and then to make a R package for this function. Below is my function:
```{r}
#' @title Model pop/lifeExp/gdpPercap VS year for countries in gapminder dataset.
#'
#' @description gapminder_lmfit is used to fit linear models to pop/lifeExp/gdpPercap and year for a specific country in gapminder dataset.
#' It can be used to carry out regression between pop/lifeExp/gdpPercap and year, then it will return the coefficients, residuals
#' and fitError(=sum of residuals^2) of fitted linear model back at the same time.
#'
#' @param countryName character this should be the name of country that you want to explore in gapminder dataset.
#' @param x character this should be variable "year" here.
#' @param y character this could be one of the three variables(pop/lifeExp/gdpPercap) in gapminder dataset. Default value of y is "pop".
#' @param offset this can be used to specify an a priori known component to be included in the linear predictor
#' during fitting. In this function, the default value of offset is 1952, because we think it makes more sense for
#' the intercept to correspond to pop/lifeExp/gdpPercap in 1952, the earliest date in gapminder dataset.
#'
#' @return list
#' @export
#' @examples
#' library(gapminder)
#' gapminder_lmfit("Canada")
#' gapminder_lmfit("Canada","year","lifeExp")
#' @importFrom dplyr %>%
#' @importFrom dplyr arrange
#' @importFrom dplyr mutate
#' @import gapminder

gapminder_lmfit <- function(countryName,x="year",y="pop",offset=1952)
{
  if(countryName == ""){
    return("Please provide a country name that you would like to explore.")
  }

  ##Get names for all countries in gapminder dataset, which are pre-stored at a file named "countryNames"
  countryNames <- (gapminder %>% arrange(year) %>% head(142))$country    ##because we know there are 142 countries in gapminder dataset in total

  if(!(countryName %in% countryNames)){
    return("The country name you provided not found in gapminder. Please try an existing country name.")
  }

  if(!(y %in% c("pop","lifeExp","gdpPercap"))){
    return("Invalid parameter y. You can leave y equal to its default value 'pop' or set it as pop/lifeExp/gdpPercap.")
  }
  countryData <- gapminder %>% filter(gapminder$country==countryName)
  results <- vector("list",4)
  lmfit <- lm(countryData[[y]]~I(countryData[[x]]-offset),countryData)
  intersect <- setNames(coef(lmfit)[1],"intercept")
  slope <- setNames(coef(lmfit)[2],"slope")
  res <- lmfit$residuals
  fitError <- setNames(sum(res^2),"fitError(sumOFres^2)")
  res <- setNames(res,c("residuals",c(2:length(res))))

  results[[1]] <- intersect
  results[[2]] <- slope
  results[[3]] <- fitError
  results[[4]] <- res

  return(results)
}
```
I can do `test()`, `document()` successfully, and of course I can use `load_all()` to build and install my package, in order to use my function. But when I am trying to use `check()` to check the whole stuff, it kept returning errors, like below.
```{r}
....
* checking examples ... ERROR
Running examples in ‘GapminderPackage-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: gapminder_lmfit
> ### Title: Model pop/lifeExp/gdpPercap VS year for countries in gapminder
> ###   dataset.
> ### Aliases: gapminder_lmfit
> 
> ### ** Examples
> 
> library(gapminder)
> gapminder_lmfit("Canada")
Error in countryData[[y]] : subscript out of bounds
Calls: gapminder_lmfit ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  8: stats::model.frame(formula = countryData[[y]] ~ I(countryData[[x]] - offset), data = countryData, 
         drop.unused.levels = TRUE)
  9: model.frame.default(formula = countryData[[y]] ~ I(countryData[[x]] - offset), data = countryData, 
         drop.unused.levels = TRUE)
  10: eval(predvars, data, env)
  11: eval(expr, envir, enclos)
  
  testthat results ================================================================
  OK: 4 SKIPPED: 0 FAILED: 1
  1. Error: gapminder_lmfit() returns a list 
  
  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE

Status: 2 ERRORs, 1 NOTE
```

I have no idea what's out of bounds here. Cause this function works well when I use it in R console directly. And I can also do `test()` successfully. Thus, I am wondering is it because the way how I introduce `gapminder` into my package is wrong? Any suggestion would be really appreciated!

Thanks,
Lina

**Comment by samhinshaw** [comment]
I think the main thing you want to look at is `1. Error: gapminder_lmfit() returns a list`.  Do you have a line in your tests that expects a certain output?  When I run your code I get a list of 4:
```
List of 4
 $ : Named num 15412220
  ..- attr(*, "names")= chr "intercept"
 $ : Named num 329118
  ..- attr(*, "names")= chr "slope"
 $ : Named num 9.84e+11
  ..- attr(*, "names")= chr "fitError(sumOFres^2)"
 $ : Named num [1:12] -626636 -47656 282448 470776 289918 ...
  ..- attr(*, "names")= chr [1:12] "residuals" "2" "3" "4" ...
```

**Comment by LinaQiu** [comment]
yes, I do have a test that expects a `list` as output, because the output of this function should be a `list`. Thus, I check the class of output to check whether my function works well or not. And below is my tests:
```{r}
context("Model Population VS Year for countries in gapminder dataset.")

test_that("gapminder_lmfit() returns a list",{
  library(gapminder)
  test_country <- gapminder_lmfit("Canada")
  expect_is(test_country,"list")
})

test_that("Country not found results in error",{
  library(gapminder)
  test_country <- gapminder_lmfit("Lol")
  expect_identical(test_country,"The country name you provided not found in gapminder. Please try an existing country name.")
})

test_that("Empty country name provide results in error",{
  test_country <- gapminder_lmfit("")
  expect_identical(test_country,"Please provide a country name that you would like to explore.")
})

test_that("No parameter passed",{
  expect_error( gapminder_lmfit())
})

test_that("Whether parameter y has a valid value",{
  library(gapminder)
  test_country <- gapminder_lmfit("Canada","year","continent")
  expect_identical(test_country,"Invalid parameter y. You can leave y equal to its default value 'pop' or set it as pop/lifeExp/gdpPercap.")
})
```
Any suggestions are welcome! Thanks!

**Comment by jennybc** [comment]
How are declaring your dependency on the `gapminder` package and the `gapminder` data frame specifically? Write an incredibly simple function that just returns the first row of `gapminder`. You may be correct that the `gapminder` data frame is not being found and hence this error:

```
Error in countryData[[y]] : subscript out of bounds
Calls: gapminder_lmfit ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
Execution halted
```

**Comment by jennybc** [comment]
The `dplyr` package uses the `nycflights13` data package, so you may want to look at how an external data package is used there. Specifically this:

https://github.com/hadley/dplyr/blob/dd10ccd543a2bea99573e6622b46d50f657b0c1f/R/data-nycflights13.r#L36

I must admit, I haven't depended on `gapminder` in another package myself! But you'll probably need to do something like `utils::data(package = "gapminder")` and then possibly specify the `gapminder` data frame by name, since it makes multiple data frames available.

**Comment by LinaQiu** [comment]
At first, I ran `use_package("gapminder")` in R console, and then I added a line `#' @import gapminder` before my function. Then I also added a command `library(gapminder)` in all tests part. That is all I have done, but I am not sure it is right or not. Cause I am not sure should I take `gapminder` as a package or a dataset. I searched some materials online, and it seems like the way to introduce a package and a dataset into our own package is different... do I understand it right? 

Thanks,
Lina

**Comment by LinaQiu** [comment]
Besides, while I am running `check()`, there are some notes appear too. I have pasted these notes below:
```{r}
* checking R code for possible problems ... NOTE
gapminder_lmfit: no visible binding for global variable ‘gapminder’
gapminder_lmfit: no visible binding for global variable ‘year’
```
But I checked online, and it seems like lots of people have the same problem. And most of them suggested just leave them, as it won't cause any essential issues... Could you please confirm is it right or not? Thank you so much.

**Comment by LinaQiu** [comment]
Hey @jennybc ,

Could you please explain more on what does specify the `gapminder` data frame by name means? I tried  `utils::data(package = "gapminder")`, and what I get is a `packageIQR`. How can I extract a specific data frame `gapminder` out from a `packageIQR`? Any suggestions? 

Thanks.
Lina

**Comment by jennybc** [comment]
Is your package on GitHub already? It would be great if you could point me to the thing itself.

**Comment by LinaQiu** [comment]
Yes. I just pushed it to my Github repository. But it still lacks of README file and Vignettes file. You can find them [here](https://github.com/LinaQiu/GapminderPackage). But there is a strange thing  happened today, I used the same function and tests to do `test()` again. It no longer passes again, although I do can pass `test()` yesterday... But the problem would be the same, the package cannot find where `gapminder` is. I'd appreciate for any help! Thanks @jennybc !

Lina

**Comment by oganm** [comment]
If you use the Depends field it will just work. Since the gapminder package doesn't have functions of its own it is much less likely to cause problems with other packages. But as long as you only put it to imports field, you have to call it as `gapminder::gapminder`

**Comment by jennybc** [comment]
@oganm's idea is good and quick. It may also be the most correct solution in this case. I suspect so.

**Comment by LinaQiu** [comment]
Hi @jennybc and @oganm ,

I have tried what @oganm said, to use `gapminder::gapminder`, but it still does not work... Thus I want to try to put it in the Depends field, but I am not sure I know how to do that... is it the same way as we put it in imports field? Thanks.

Lina

**Comment by jennybc** [comment]
Oh, yeah, when I endorsed @oganm's suggestion it was to use Depends.

**Comment by jennybc** [comment]
`devtools::use_package()` has a type argument that default to "Imports" but accepts "Depends".

**Comment by oganm** [comment]
Is there a reason for using the namespace to fail? When I try your package by adding `gapminder = gapminder::gapminder` to the beginning of your function your tests fail because of a faulty use of filter at https://github.com/LinaQiu/GapminderPackage/blob/master/R/gapminder_lmfit.R#L43

It happens because you are (just like you do to gapminder) importing dplyr package instead of depending on it (based on CRAN standards this is the right way to do things), this means that when calling any dplyr functions you have to refer to it as `dplyr::filter`. The `filter` you have been trying to use was the one that is loaded by default.

**Comment by LinaQiu** [comment]
Thank you soooooo much @oganm  and @jennybc !!! Yes, I solve my problem now. I need to depend on these two packages(`gapminder` and `dplyr`), not just import them. It works well now. Thanks so much. Honestly, I have been bothered by this issue for a couple of days. And I even tried to store the gapminder dataset in a `data` file in my package, as what suggested [here](http://kbroman.org/pkg_primer/pages/data.html). But it still did not work. I really appreciate for all of your help, otherwise I must gave it up in the end. Thanks soooo much @jennybc  and @oganm !

Lina

**Comment by jennybc** [comment]
@LinaQiu Glad it worked out! You shouldn't need to Depend on (vs Import) `dplyr`. But I'm just glad it's working. On the issue where you submit, maybe ask your TA or peer reviewers to help you convert the `dplyr` treatment over to Import.

**Comment by LinaQiu** [comment]
Yes, sure. I will ask for TAs' and peer reviewers' suggestions on it. Thanks again @jennybc .

Lina
