### ISSUE TITLE
How to test a function that outputs files (delimited, txt,etc)?

### ISSUE THREAD

**Issue by gjahesh** [STAT545-UBC/Discussion#260]
Hi there,

I have a function that compares `write.table()` and `saveRDS()` on a piece of data,
the output of the function is two files `.txt` and `.RDS`, plus a mini data frame that shows how the order of the one of the factors in the output data files is comparable to the original  data when writing files using these two methods, just wondering what could I possibly test for this function?

Thanks,
Golnaz

**Comment by jennybc** [comment]
You should write a test that uses the function ... presumably leaving two files behind somewhere, i.e. in working directory or some where you specify (such as a temp directory). Then you should read the stuff you need back in -- it sounds like that data frame is the true output? -- and test that it is equal to what it should be. So you control the inputs and can say exactly what the final output should be.

But, yes, you actually need to let / help all of that happen. Make sure to clean up after. If those files go in working directory, delete them. If you put them in session temp dir, you don't really have to worry about it.

**Comment by oganm** [comment]
A potential alternative for the lazy: if the output is constant and unlikely to change at all, you can use `md5sum` to make sure the file is identical to what you expect. This might cause false positives if you change something about the ouptut without breaking your specification though.

**Comment by jennybc** [comment]
@oganm Even in that situation I think a better alternative is `testthat::expect_equal_to_reference()`. But yes, in scripts where I'm not necessarily using a formal testing framework, I have been known to test for equality of two files with suspiciously similar names via `md5sum`. It is a good thing to know about.

But I think @gjahesh's situation is well within the limits of the normal, explicit solutions.

**Comment by gjahesh** [comment]
Thank you @jennybc and @oganm for the inputs.

@jennybc So I did get rid of the files in the working directory, and yes the ultimate output is a data frame.
So I used `read.delim()` and `readRDS()` to read back the files in the function. So can I use it like this:
```{r}
test_that("checking the output",{
  expect_equal_to_reference(test_df,"test_df.rds")
}
```
I'm getting error at this moment, however I'm not sure if I used it correctly...
The Error message is saying that it can't find the `test_df` object. However, it's the output of the function!

**Comment by mstrimas** [comment]
From the `test_that()` help it says:
> Tests are evaluated in their own environments, and should not affect global state.

I think what this means is that it can't see objects you've defined elsewhere. In particular, I think you need to define `test_df` within the curly brackets.

**Comment by jennybc** [comment]
I don't see a function call at all. What creates the `test_df.rd` file?

I would normally expect to see the code that runs your function and, presumably, create `test_df.rds` inside the body of this `test_that()` call. Then one or more `expect_*()` calls near or at the end.

**Comment by gjahesh** [comment]
oh my sorry , forgot to do a function call. 
Just to see if I understood clearly then, in `expect_equal_to_reference()` we could test the function out put ( which is a data frame in my case) to see if its identical to the original input (again a data frame in this case) but in the.RDS format?

```{r}

test_that("checking the output",{

test_df <- my_function(input_df)
  expect_equal_to_reference(test_df,"input_df.rds")
}
```
Sorry if doesn't make any sense...

**Comment by mstrimas** [comment]
I think what you want may be something like:  
```
test_that("checking the output", {
  test_df <- freq_out(gapminder::gapminder$continent)
  expect_equal_to_reference(test_df, "input_df.rds")
})
```

**Comment by gjahesh** [comment]
Thanks Matt.
