### ISSUE TITLE
Is homework 9 (i.e. automation) released yet?

### ISSUE THREAD

**Issue by csiu** [STAT545-UBC/Discussion#261]

**Comment by jennybc** [comment]
No but it's same as last year. I just need to re-render (and will give it a once over for polish and simplicity -- no change in content).

http://stat545-ubc.github.io/hw12_data-from-web.html

**Comment by jennybc** [comment]
Refreshed (and renumbered):

http://stat545-ubc.github.io/hw09_automation.html

**Comment by csiu** [comment]
Thanks jenny!
