### ISSUE TITLE
Shell directory / New project?

### ISSUE THREAD

**Issue by zhamel** [STAT545-UBC/Discussion#264]
For homework 9, should we create a new project?

I created my makefile in a folder in my stat454 project. The first part of the pipeline (downloading) seems to be working when i use clean and build in R. However, when I use the Shell it doesn't work because it is set to the main directory in my project and not the folder in which I have my `Makefile`. Is there a way to change the directory for the Shell... because I can't figure it out!! 

Thanks!

**Comment by jennybc** [comment]
I don't think you *need* a new project for this. So I prefer that you host within your existing repo. But I care don't that much, I suppose.

When you go to the shell, you are able to set working directory to whatever you like. Use `cd` to do that. Yes it will initially open in the top-level Project directory, but then you can go one level down into a directory for this homework.

Or are you referring to RStudio running the Makefile for you via Build? That might be hard-wired for Makefiles at the top-level .... not sure. I find the rule access so limited that it's not terribly useful. You'll have to be checking and running things from the shell a lot anyway.

**Comment by zhamel** [comment]
Thanks Jenny, I just needed to use `cd`. Now the shell is reading my `Makefile`.

But I am running into on more problem. When I use the shell to `make all`, it tells me that there is no package called `downloader`. (It works when I use R). 

Here is my Makefile script:

```{r}
all: gapminder.tsv

clean: 
	rm -f gapminder.tsv

gapminder.tsv: download.R
	Rscript download.R
```

and my download.R script:
```{r}
library(downloader)
downloader::download("https://raw.githubusercontent.com/jennybc/gapminder/master/inst/gapminder.tsv", destfile = "gapminder.tsv")
```

I installed it, and check that it lives in the correct library (which is what google told me to do!). I tried to add the `install.packacges("downloader)` in my script but it still gives me this error... Any suggestions of things I can try to make it work?

Thank you!

**Comment by jennybc** [comment]
Run this to see what libraries are available once the shell / Make takes over

``` r
Rscript -e '.libPaths()'
```

Then look at result of `.libPaths()` in R via RStudio. I'm guessing we will see a difference.

**Comment by zhamel** [comment]
Yes they are different: 

In R I get two libraries.

```{r}
 .libPaths()
[1] "C:/Users/zoe.hamel/Documents/R/win-library/3.2"
[2] "C:/Program Files/R/R-3.2.2/library"      
```

And in the shell I only get the second one, and my package lives in the first one. Now I tried to set up the shell library to the first entry by using the following code:

```{r}
Rscript -e '.libPaths("C:/Users/zoe.hamel/Documents/R/win-library/3.2")'
```

But it doesn't change anything! When I do `Rscript -e '.libPaths()'` afterwards, I still get the same 'wrong' library! I also tried to run it in a make file, just in case, but it still doesn't work (as expected!)...

**Comment by AdrianLJones** [comment]
See issue #250 I posted a kludge solution to the same problem.  Basically do everything in an Rscript.

**Comment by BernhardKonrad** [comment]
Every time you call `Rscript` from the shell you open a new R session. Hence
`Rscript -e '.libPaths("C:/Users/zoe.hamel/Documents/R/win-library/3.2")'`
`Rscript -e '.libPaths()'`
won't show the added path, but
`Rscript -e '.libPaths("C:/Users/zoe.hamel/Documents/R/win-library/3.2"); .libPaths()'`
will.

**Comment by zhamel** [comment]
YEAHHHH it's working!

Thanks everyone.

**Comment by jennybc** [comment]
It's not clear to me why the shell invocations of Rscript aren't seeing her library but R within RStudio is. Does Rscript ignore some usual start up stuff? I could figure this out for myself but am hoping someone else has already looked into it. Or wants to. That is the root case of this and #250.

**Comment by BernhardKonrad** [comment]
I'm sure the solution is somewhere here: https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html

Could have something to do with http://stackoverflow.com/questions/16049259/rstudio-different-library-path-to-command-line-r-r-libs-user:
The shell reads `.bash_rc`, which RStudio does not. RStudio reads `$R_HOME/etc/Renviron`, which the shell does not. Maybe?
FWIT I'm using Linux and my `$R_HOME/etc/Renviron` sets `R_LIBS_USER=${R_LIBS_USER-'~/R/x86_64-pc-linux-gnu-library/3.2'}` but I get the same results for `.libPaths()` from the shell and RStudio.

**Comment by jennybc** [comment]
What new Windows-inflicted evil is this? 😞

Mac OS here and yes I get same result from `.libPaths()` in both contexts.

Yes I think the solution in that SO thread is the one our students should implement. I'm not keen on these solutions that change `.libPaths()` on the fly. It's better to fix the problem more fundamentally.
