### ISSUE TITLE
Connecting Rstudio project to Github

### ISSUE THREAD

**Issue by gjahesh** [STAT545-UBC/Discussion#265]
Hello,

I have a question about connecting my local Rstudio project to Github.
I did create an empty project for automation homework, and then got a personal access token from github for a new repo, named `automation` .
I'm just not sure how to add this token to .Renviron , basically not sure how to add multiple PATHs to it, since it' already set to the repo for the R package activity `foofactors` repo.
I'm using Linux Ubuntu FYI.

Thanks,
Golnaz

**Comment by jennybc** [comment]
Your GitHub PAT is not project specific. It is specific to *you* and whatever scopes you requested (presumably the defaults). But it grants you general permission to do things via the GitHub API.

Right now, I'm not sure what your plans are. The only functions on your radar that know how to use this PAT are `devtools::install_github()` and `devtools::use_github()`. Sadly, `devtools::use_github()` currently only operates on a Project/Git repo that is also an *R package*.

Connect your local and remote repos by following these directions:

http://stat545-ubc.github.io/git07_git-github-rstudio.html#step-2-plan-b-connect-a-local-rstudio-project-to-a-github-repo

**Comment by gjahesh** [comment]
Thanks Jenny, I was wandering between STAT545 Topics trying to remember where did I see that :)
Still not sure what's the difference when you create a repo on Github then link it from the local project and when you ask for the token and make the link by setting the PAT...
