### ISSUE TITLE
Vignettes Not Installing

### ISSUE THREAD

**Issue by mstrimas** [STAT545-UBC/Discussion#266]
The peer reviewer of my package wasn't able to see my vignette with `browseVignettes("foofactors")` despite it compiling and viewing fine for me locally (with Build & Reload). I've now noticed that I can't view my vignette either if I install it from GitHub and, in fact, I don't seem to be able to see anyones vignettes, including @jennybc. Anyone else having a similar issue?

**Comment by bdacunha** [comment]
Yes, I i think it's something recurring. In both of the packages that I checked, I couldn't see the vignettes

**Comment by kyleLesack** [comment]
I had the same problem, and eventually found a workaround that worked for me. It's pretty kludgy though, so you might want to wait for someone to post a proper answer.

Anyways, I ended up using the *install_local* command for [devtools](https://cran.r-project.org/web/packages/devtools/devtools.pdf), with the "build_vignettes = TRUE" option.

*E.g.:*
install_local("../foofactors_0.0.0.9000.tar.gz", build_vignettes = TRUE)

This only worked once though. However, if I deleted the "tar.gz" file that the command produced, along with the vignettes produced in the repo and my local R installation, I was able to create them once again using the *install_local* command. 

It only worked when I deleted the "foofighters" vignette file in my R installation folder (this is different from assignment working directory). In my case, the directory was:

D:\Documents\R\win-library\3.2\foofactors

I'm sure there is a way better way of doing this, but this worked for me at least.

**Comment by jennybc** [comment]
I have updated my [peer review instructions](http://stat545-ubc.github.io/hw08_package_onramp-peer-review.html#install-your-peers-package) to include this advice now. Specify `build_vignettes = TRUE` inside `install_github()`:

``` r
library(devtools)
install_github("PEERGITHUBUSERNAME/foofactors", build_vignettes = TRUE)
library("foofactors")
## ... and you're off to the races ...
```

**Comment by mstrimas** [comment]
Thanks!
