### ISSUE TITLE
using gapminder.tsv

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#267]
Hello,

I have managed to download the gapminder data as a tsv in order to make a makefile. This is the code from my Rscript:
'''
library(downloader)
download(url ="https://raw.githubusercontent.com/jennybc/gapminder/master/inst/gapminder.tsv", destfile = "gapminder.tsv")
'''

And this actually works when I build and clean all in the makefile...

But now that I want to work with the data, I feel that is in a weird format and I can't plot or do anything else. I tried using as.data.frame to change the format... but it's not the right way to go...
Probably this is a very stupid/basic question...but for some reason I don't know what to do.

Brenda

**Comment by oganm** [comment]
What do you mean by a weird format it should be the same as the gapminder dataset you know and love. How did you try to read it?

**Comment by sho-87** [comment]
You'd have to use `read.table()` or `read.delim()` to get it into the correct format after you download it

**Comment by bdacunha** [comment]
I'm using read.delim() but still I cannot make it plot lifeExp vs year

**Comment by bdacunha** [comment]
well I don't know what happened, but I closed R, reopened it and now i can work with it...
