### ISSUE TITLE
Can't download packages from github

### ISSUE THREAD

**Issue by wang114** [STAT545-UBC/Discussion#268]
I ran into the following problem. When I want to download packages from github, I have an error message:

         devtools::install_github("wang114/foofactorsran")
         Using github PAT from envvar GITHUB_PAT
         Downloading GitHub repo wang114/foofactorsran@master
         Error in download(dest, src, auth) : client error: (401) Unauthorized

How could I fix this? Thank you.

**Comment by kenmansfield** [comment]
"error: (401) Unauthorized" generally means you need a username and password.

**Comment by wang114** [comment]
How do I set the username and password?

**Comment by jennybc** [comment]
To install from a private GitHub repo, you will need a GitHub personal access token. As explained in this part of our "how to build an R package" lesson:

http://stat545-ubc.github.io/packages05_foofactors-package-02.html#connect-to-github
