### ISSUE TITLE
how many scripts

### ISSUE THREAD

**Issue by molliejmcdowell** [STAT545-UBC/Discussion#269]
Hi, I'm a little confused about the wording of homework 9. Should we aim to complete every bullet point under "exploratory analyses" and "statistical analyses" as well as "generate figures", or are five+ scripts fine?

**Comment by jennybc** [comment]
If you choose the "just tell me what to do option", yes do each bullet point. I but I'd expect each major heading to correspond to one script. I don't think it will be as high as *five*. But the number doesn't really matter, as long as it's 3 or more. I want to see at least these separate steps: some data acquisition, some data prep and/or analysis and/or visualization, and some reporting.

**Comment by molliejmcdowell** [comment]
k thanks for the explanation!
