### ISSUE TITLE
how to add the residual error?

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#271]
Hello,

I have this function that gives a table with the slope and intercept, but I don't know how can I add the residual error to this output.. is it possible? or should I create a new function for the residuals?

le_lin_fit <- function(dat, offset = 1952) {
	if (!is.data.frame(dat))
		stop('I am sorry, but this function only works for data.frame input. \n', 'You have to provide an object of class: ', data.frame(dat))
	the_fit1 <- lm(lifeExp ~ I(year - offset), dat)
	setNames(data.frame(t(coef(the_fit1))), c("intercept", "slope"))
}

Thanks,

Brenda

**Comment by cheny19** [comment]
`resid(the_fit1)` or `residuals(the_fit1)` will return the residual of each point in your fitted model. So you can just add another column to your output that computes the maximum residual.

**Comment by jennybc** [comment]
The best way to get residual standard error is this:

``` r
rse <- sqrt(deviance(jfit)/df.residual(fit))
```

You'll need to add that to the thing you're returning. Something like so:

``` r
setNames(data.frame(t(c(coef(the_fit1), rse))), c("intercept", "slope", "rse"))
```

Note: I'm not running any of this code, so take it with a grain of salt.

**Comment by bdacunha** [comment]
thanks!
