### ISSUE TITLE
adding another column?

### ISSUE THREAD

**Issue by bdacunha** [STAT545-UBC/Discussion#272]
``` r
le_lin_fit <- function(dat, offset = 1952) {
	if (!is.data.frame(dat))
		stop('I am sorry, but this function only works for data.frame input. \n', 'You have to provide an object of class: ', data.frame(dat))
	the_fit1 <- lm(lifeExp ~ I(year - offset), dat)
	rse <- sqrt(deviance(the_fit1)/df.residual(the_fit1))
	setNames(data.frame(t(c(coef(the_fit1), rse))), c("intercept", "slope", "rse"))
}

fit_1 <- bdat %>% 
	group_by(country) %>% 
	do(le_lin_fit(.)) 
fit_1
```

The output this will give me is a data frame that has the country, the slope, intercept and the residual error. However, I also need the continent column. i tried adding it using inner_join and it works, but the output repeats itself (for example, I get somethings like this:

```
country  continent  slope  intercept  error
peru      americas  0.9      -5             15
peru      americas  0.9     -5              15
peru      americas  0.9     -5              15
peru      americas  0.9     -5              15
chile      ..........
```

And I only want one of each country... is there any other way to add a column?

Thanks

Brenda

**Comment by jennybc** [comment]
Maybe try semi join?

**Comment by jennybc** [comment]
You don't say what you're joining to.

**Comment by bdacunha** [comment]
I'm joining the complete data frame (gap minder) with the new data frame containing the slope, intercept and residual error... I will try semi_join

**Comment by jennybc** [comment]
Wait, that's not going to work. It won't bring in a new column. But you need to look at the cheatsheet and figure out which join best fits the bill. Then manufacture the table to join to.

http://stat545-ubc.github.io/bit001_dplyr-cheatsheet.html

**Comment by jennybc** [comment]
Just add `continent` to the `group_by()` statement. Sorry didn't think of that sooner.

**Comment by bdacunha** [comment]
Thanks jenny!... I was about to write that I did that and it worked!
