### ISSUE TITLE
Creating PDFs via latex in command line/make

### ISSUE THREAD

**Issue by samhinshaw** [STAT545-UBC/Discussion#276]
Can anyone suggest a good tutorial/walkthrough for learning the ins and outs of creating PDFs from markdown/noweb? I tried using a few different methods in the homework, following [Jenny's mention of LaTeX](http://stat545-ubc.github.io/hw09_automation.html#i-want-to-aim-higher): 
> Use Pandoc and/or LaTeX to explore new territory in document compilation. You could use Pandoc as an alternative to rmarkdown (or knitr) for Markdown to HTML conversion; you’d still use rmarkdown for conversion of R Markdown to Markdown. You would use LaTeX to get PDF output from R Markdown.  

* Creating a [.Rnw file](https://github.com/STAT545-UBC/samuel_hinshaw/blob/master/homework/homework9/homework9.Rnw) with the appropriate formatting, such as:
```
<<>>=
read_chunk('join.R')
@
```
* Running the commands:
```
R -e 'library(knitr);knit("homework9.Rnw")'   
pdflatex homework9.tex
```
This enters some type of interactive mode in terminal, throwing errors left and right. 
* Or instead using `knit2pdf`
```
R -e 'library(knitr);knit2pdf("homework9.Rnw")'
```
This throws more errors left and right, ending with:
```
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'homework9.tex' failed.
LaTeX errors:
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
! Missing $ inserted.
<inserted text> 
                $
l.3 ...d the `knitr` package so we can call `read_
                                                  chunk()`
! LaTeX Error: Environment knitrout undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
! Undefined control sequence.
l.5 \definecolor
                {shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{...
The control sequence at the end of the top line
of your error mess
Calls: knit2pdf -> <Anonymous> -> texi2dvi
Execution halted
```

Unfortunately, all of these methods give me various errors. I wanted to attempt to use latex instead of pandoc, but it seems like pandoc may just be a [simpler solution](http://stackoverflow.com/questions/11025123/how-to-convert-r-markdown-to-pdf).

* Using pandoc to create a PDF from the HTML output of rmarkdown or knitr:
```
pandoc -s homework9.html -o homework9.pdf
```
This works perfectly.  Should I just use this workflow for automation?

Should I bother learning LaTeX if markdown is  "good enough"?

#### Sources
[Karl Broman](http://kbroman.org/knitr_knutshell/pages/latex.html)
[Yihui Xie](http://yihui.name/en/2013/10/markdown-or-latex/)
[Jenny Bryan](http://stat545-ubc.github.io/automation00_index.html#more-examples)
[Ask Ubuntu](http://askubuntu.com/questions/166679/how-can-i-convert-a-tex-file-to-pdf-on-via-the-command-line)
[Andrew Young](http://www-rohan.sdsu.edu/~aty/bibliog/latex/LaTeXtoPDF.html)

**Comment by BernhardKonrad** [comment]
Hi, good job at trying this!

Unfortunately I can't access your minimal example and hence can't reproduce your exact errors. Your last `pandoc` command is what Jenny was referring to on the course webpage, at least almost. The workflow is `R Markdown` -> `Markdown` with `knitr` (or `rmarksdown`), then `Markdown` -> `pdf` with `pandoc` (which in turn uses `LaTeX`). No need to create an intermediate html. You can request the `markdown` file in the YAML with 
```R
output:
    md_document
```


With this your overall workflow would be

```bash
Rscript -e "library(knitr); knit('homework9.Rmd');"
pandoc -s homework9.md -o homework9.pdf
```

(`pandoc -s homework9.md -o homework9.tex` if you want a compilable `LaTeX` source code.)

**Comment by BernhardKonrad** [comment]
Whether you want to learn LaTeX depends on what you want to use it for, and what your collaborators are using. In Mathematics there is no way around it, but I have heard rumours that other so-called "Sciences" can manage without :stuck_out_tongue_winking_eye:

**Comment by samhinshaw** [comment]
Thank you for describing the workflow and other possibilities! After posting this, I also realized I could request a PDF output in the YAML
```
output: 
  pdf_document
```
and then knit directly to PDF with 
```
Rscript -e "rmarkdown::render('homework9.Rmd')"
```
Note that in this case, for some reason
```
Rscript -e "library(knitr); knit('homework9.Rmd');"
```
still creates an md document, not a PDF. 

Also interestingly, (but perhaps obviously?) the PDF resulting from this method looks different from the PDF created by pandoc. 

I guess I'm just confused about the relationship between TeX, LaTeX and noweb, as compared with (R) Markdown, knitr, Sweave, pandoc, and the rmarkdown package.  I could probably use a history lesson. 

From my understanding:
* TeX (1978): typesetting system for publication
* LaTeX (1985): document markup language, somehow distinct from TeX?
* noweb (1989): incorporates code into TeX/LaTeX, etc  
--- time gap? ---
* Sweave (2003): package to incorporate R into LaTeX
* Markdown (2004): document markup language aimed at readability
* Pandoc (2006): document converter used by RStudio
* Knitr (2012): package to incorporate R into markdown, LaTeX, HTML, etc
* R Markdown (2012): like noweb for markdown, incorporates pandoc & knitr in a more user-friendly manner
	(knitr & R Markdown developed in tandem at RStudio)

### Sources
[R Markdown](http://rmarkdown.rstudio.com/)
[R Markdown Advanced Customization](http://rmarkdown.rstudio.com/html_document_format.html#advanced-customization)
[R Markdown v2 changes](http://rmarkdown.rstudio.com/authoring_migrating_from_v1.html)
[Jenny's R Markdown Notes](http://stat545-ubc.github.io/block007_first-use-rmarkdown.html)
[Karl Broman Knitr w/ R Markdown](http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html)
[Yihui Xie's Knitr FAQs](https://github.com/yihui/knitr/blob/master/FAQ.md)
[Pandoc Readme](http://pandoc.org/README.html)
[RStudio Blog](http://blog.rstudio.org/2014/06/18/r-markdown-v2/)
Wikipedia

**Comment by BernhardKonrad** [comment]
Yeah, lol, I should have mentioned the `pdf_document` in the YAML if all you want is a pdf.

My simplified version of the history lesson would be the following. There are two markup languages, LaTeX (with TeX, LaTeX, noweb) and markdown. LaTeX is pretty old, extremely powerful (read: can become complicated) and is usually translated into eps/dvi/pdf. Then people wanted to write dynamic reports that incorporate R scripts and invented Sweave, which uses LaTeX to make pdfs. The pipeline is Sweave: Rnw File -> TeX File -> PDF File

In a parallel universe Markdown was build, a less powerful (read: can do most things really easily) markup language built for the web, hence it usually translates to html. Then people wanted to write dynamic reports that incorporate R scripts and invented knitr, which processes the newly invented R Markdown format into HTML. The pipeline is R Markdown: Rmd File -> Markdown File -> HTML File

And then the two universes met. In fact, many such universes met as there is an abundance of file formats out there. Luckily, there is one tool to tame them all: Pandoc. Well, most, anyway. Pandoc is the swiss-army knife of document conversion (see http://pandoc.org/diagram.jpg). It doesn't follow the old patterns and can translate pretty much anything to anything else. Hence you can sneak pandoc in between whatever pipeline to change the output, e.g. you could Rnw -> Tex File -> HTML or Rmd -> Markdown -> PDF.

Sources:
http://pandoc.org/
http://learndataanalysis.com/markdown-and-sweave-r

**Comment by samhinshaw** [comment]
Interesting, thank you for the clarification!  This all makes a bit more sense now. I'll have to think about learning LaTeX.  I'm sure at some point it will become necessary :confounded:
