### ISSUE TITLE
httr POST

### ISSUE THREAD

**Issue by lmguzman** [STAT545-UBC/Discussion#277]
Hi, 

Im trying to use the google flight API, and the way I understand it, to be able to interact with it, I need to POST to the url a json request. And im able to do that successfully (it says status: 200) but im not sure how to actually get the response from the API. Any help would be very much appreciated!

url <- "https://www.googleapis.com/qpxExpress/v1/trips/search"

all_text <- '{
"request": {
  "passengers": {
    "kind": "qpxexpress#passengerCounts",
    "adultCount": 1,
    "childCount": integer,
    "infantInLapCount": integer,
    "infantInSeatCount": integer,
    "seniorCount": integer
  },
  "slice": [
    {
      "kind": "qpxexpress#sliceInput",
      "origin": NYC,
      "destination": YVR,
      "date": 12-25-2015,
      "maxStops": integer,
      "maxConnectionDuration": integer,
      "preferredCabin": string,
      "permittedDepartureTime": {
        "kind": "qpxexpress#timeOfDayRange",
        "earliestTime": string,
        "latestTime": string
      },
      "permittedCarrier": [
        string
        ],
      "alliance": string,
      "prohibitedCarrier": [
        string
        ]
    }
    ],
  "maxPrice": string,
  "saleCountry": string,
  "refundable": boolean,
  "solutions": integer
}
}'

b1 <- POST(url, body = all_text, encode = "son")

> b1
Response [http://httpbin.org/post]
  Date: 2015-12-01 23:24
  Status: 200
  Content-Type: application/json
  Size: 1.34 kB
{
  "args": {}, 
  "data": "{\n\"request\": {\n  \"passengers\": {\n    \"kind\": \"qpxexpress#passengerCounts\",\n    \"adultCount\": 1,\n    \"child...
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "application/json, text/xml, application/xml, */*", 
    "Accept-Encoding": "gzip, deflate", 
    "Content-Length": "846", 
    "Host": "httpbin.org", 
...
>

**Comment by jennybc** [comment]
I'm not entirely sure of what we're talking about. But in general you get the content out of such a request via `httr::content()`.

**Comment by lmguzman** [comment]
Hi @jennybc Thank you. I can see that gives me the contest of my request. But Im not sure how to get a reply. This is the API im working with. https://qpx-express-demo.itasoftware.com.
I sent a request using POST and basically in the body of the request I put what they suggest for the json request. Im just not sure if Im getting the replies from them. But then when I check with content it says that the status is 200

**Comment by jennybc** [comment]
Given what I see above, I would expect `b1` to be the reply, so to speak.

**Comment by aammd** [comment]
Yes, that makes sense to me also. If i try your example: 

```
b1 <- POST(url = url, body = all_text, encode = "json")
content(b1)
```

I get the "reply", which in their case is a statement informing me that I need to authenticate. 200 is the Good News status code, that means a response has been set.
Is this helping?

**Comment by lmguzman** [comment]
Wait, so I need to get an authentication to be able to get the flights?

**Comment by oganm** [comment]
You need an api key. In the site you can see a sign up option. You'll probably have to add that key to some part of your request

**Comment by lmguzman** [comment]
Interesting, thank you, I thought I only needed a key for more than 50 queries.

**Comment by oganm** [comment]
Nope. The key is how they track how many queries every individual makes. [This](https://developers.google.com/qpx-express/v1/prereqs) link has the steps you need to set up the whole thing.

**Comment by lmguzman** [comment]
Thanks!!, I was trying to set up the key and they ask me the type key based on what is asking for the indo. If its a browser, or a server or an android or os. And so Im not sure what type of key I would need, and then If I chose this key, it means someone else would not be able to run my homework right?

**Comment by oganm** [comment]
If you hardcode the key or push the file with the key as well it should be fine. Hardcoding is probably a better choice here since you don't have to worry about any sensitive information. Just make sure that reviewers and graders won't reach the total of 50 requests

**Comment by jennybc** [comment]
@lmguzman Where are the exact choices re: the type of key? Can you point me to the webpage?

**Comment by jennybc** [comment]
Oh I found it. I suggest you use an API that requires less complicated authentication for your homework. This is beyond the scope of what we've covered and beyond what I want to explain in these threads.

**Comment by lmguzman** [comment]
Hi @jennybc yeah, thats a good idea. Thanks so much, sorry for it being so complicated!
