### ISSUE TITLE
How to install "new" packages on "old" version of R? [ install_github,  homework 8]

### ISSUE THREAD

**Issue by KPdir** [STAT545-UBC/Discussion#279]
I was trying to peer-review HW08 for one of our classmates using ```install_github```. I got the following error: 
     -----------------------------------
ERROR: this R is version 3.2.1, package 'HW08package' requires R >=  3.2.2
      -----------------------------------

I got around this by downloading the package and manually modifying "R >= 3.2.2" to "R >= 3.2.1" in the description file and then built the package. I'm guessing this not advised?

I was wondering if there is a workaround for this? **This issue is not critical for me at the moment** but would definitely be nice to know if there is a workaround.

**Comment by jennybc** [comment]
What you did is the workaround. By default, `devtools` sets the minimum R version to whatever is running at the time of the `create()` call and I'm making everyone run the current R release.

In real life, the package author should try to figure out what version or R is actually required and set the minimum version to that. But that's harder than it sounds.

**Comment by KPdir** [comment]
Awesome, thanks!
