### ISSUE TITLE
Error: parse error:premature EOF ?

### ISSUE THREAD

**Issue by zhamel** [STAT545-UBC/Discussion#283]
I am trying to look at the number of languages spoken in each country and the number of bird observations. In order to get the number of observations in all cuntries (based on country code) for which I have info about the # of language, I am running the following code:

```{r}
region_bird <- countryinfo_num_lang_code %>% 
  select(countryCode) %>% 
  group_by(countryCode) %>% 
  do(nrow(ebirdregion(.)))
```

But I keep getting this error:
```{r}
Error: parse error: premature EOF
                                       
                     (right here) ------^
```

I tried googling but didn't find much... Any suggestions about what's happening? How I can fix it?

I have already ran a similar code for which I did not get any error...:

```{r}
m <- countryinfo_num_lang %>% 
  select(countryCode, countryName, languages, lang_num) %>% 
  group_by(countryCode) %>% 
  do(as.data.frame(ebirdregioncheck('country',.)))
```

**Comment by jennybc** [comment]
Was it a troublesome country after all?

**Comment by zhamel** [comment]
No, it was because I wasn't passing my data as character, so I just has to add `as.character(.)` within my `do()` function:

```{r}
region_bird <- countryinfo_num_lang_code %>% 
  select(countryCode) %>% 
  group_by(countryCode) %>% 
  do(as.data.frame(nrow(ebirdregion(as.character(.)))))
```
