### ISSUE TITLE
geonamesUsername issue

### ISSUE THREAD

**Issue by Poush87** [STAT545-UBC/Discussion#285]
Hi,

When I run the following code as an R script it works fine (my geonamesUsername is saved in .Rprofile in the same directory as my R project). 
library(geonames)
countrynames <- GNcountryInfo()

But when I try automating the process using a Makefile in the same directory (but in a folder), I get the following error: 
No geonamesUsername set. See http://geonames.wordpress.com/2010/03/16/ddos-part-ii/ and set one with options(geonamesUsername="foo") for some services to work.

I assume the .Rprofile file should be in the same directory as the R project, and not in the folder where my Makefile resides. What am I missing here? 

Thanks!

Poushali

**Comment by jennybc** [comment]
`.Rprofile` is found in current working directory when R is launched. It sounds like yours is not being found when running via make. I suspect you need to move, copy, or soft link it to the directory where the Makefile lives. Caveat: I don't fully where everything is relative to each other.

**Comment by Poush87** [comment]
The Makefile lives in a folder for HW10, in stat545 directory and .Rprofile is in the same directory. 
I'm trying to use 
options()$geonamesUsername but that doesn't seem to work with Make either.

**Comment by jennybc** [comment]
Sorry. Do Makefile and `.Rprofile` live in same directory? How are you running make? If we visit your course repo, we will see the current state?

**Comment by Poush87** [comment]
Yes they do.. I just updated the course repo so you should be able to see the Makefile and associated R scripts in HW10 folder. Thanks Jenny!
