### ISSUE TITLE
HW11 (Shiny) is out - due next Friday Dec 11

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#287]
The last homework is ready, you can start working on it. I will hold regular office hours on Tues/Thurs if you need help with Shiny.

http://stat545-ubc.github.io/hw11_shiny.html

I strongly recommend (as Jenny mentioned in class) that you deploy your app to shinyappsio early and often.  It can be very annoying to try to understand why your app works on your computer but doesn't work on shinyappsio, so by deploying your app often you can at least reduce your frustration by knowing exactly what piece of code broke it.

**Comment by jennybc** [comment]
A complementary tactic is to commit often. For example right after you add a new feature to your app and run it successfully locally. Then if you break the "deploy early, deploy often" rule, at least you can checkout earlier commits and see if deployment works. If it does, that will narrow things down re: where things got weird.

**Comment by oganm** [comment]
If you are using shinyapps.io to test your deployment you might want to reduce the timeout of the apps. In default settings any app will remain in running state for about 15 mins which means that if you test it 4 times with some distance in between, a whole hour of your quota will be gone. I doubt your homework will shave of the entire 25 hours but it can be important for your future work

**Comment by jennybc** [comment]
@oganm Good point. What setting do you recommend and can you tell people how to adjust the timeout?

**Comment by oganm** [comment]
I'd go with 5 mins which is the minimum. If the app has actual users it can be annoying for them but for testing it should be fine. To change it just go to app settings as shown below

![selection_033](https://cloud.githubusercontent.com/assets/6352379/11637335/9669a72c-9cd5-11e5-81d6-7e8a1b58554c.png)

![selection_034](https://cloud.githubusercontent.com/assets/6352379/11637339/9d3ae0f2-9cd5-11e5-95e5-db192304356d.png)
