### ISSUE TITLE
Public API keys

### ISSUE THREAD

**Issue by sho-87** [STAT545-UBC/Discussion#290]
For the homework I want to wrap the google books API. I already have a developer account on there and have generated a public API key for the project

Is this something that I can/should include in the R code? They require you to pass an API key as one of the params in the URL. Should this be the API key I generated for the project? Or should I expect users to create their own key in order to use it?

**Comment by jennybc** [comment]
Is it an API where the user will then go through the OAuth2 dance to authenticate? If so, it is my opinion that yes you can put the app key into your project as a default, so a first-time user can just use it.

**Comment by sho-87** [comment]
I figured out how to do it now without having to use the API key. But how would you handle API keys for future, non-school related, projects where OAuth2 is required?

**Comment by jennybc** [comment]
You can look at how I did it in [`googlesheets`](https://github.com/jennybc/googlesheets). The package includes default client id and secret but there are ways for user to provide their own.
