### ISSUE TITLE
API Keys - Best Practices

### ISSUE THREAD

**Issue by samhinshaw** [STAT545-UBC/Discussion#294]
I apologize if I missed this discussion in class, but what are the best practices for storing API Keys, particularly using `.Rprofile` versus `.Renviron`?  From the [class notes](http://stat545-ubc.github.io/webdata02_activity.html),  I understand they can both retrieve a key via   
`Sys.getenv("APIKeyName")`
or
`getOption("APIKeyName")`  
From what I could gather, `.Rprofile` is generally used to store R code run on startup (for example `library(dplyr)`), whereas `.Renviron` is generally used to store variables such as our `GITHUB_PAT`.  

Sources:
[R Documentation: Startup](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html)
[Grokbase](http://grokbase.com/t/r/r-help/021rxvtnxb/r-renviron-and-rprofile)

**Comment by jennybc** [comment]
I triggered a discussion of this recently via Twitter. It got written up on the Revolutions blog:

http://blog.revolutionanalytics.com/2015/11/how-to-store-and-use-authentication-details-with-r.html

I tend to favour `.Renviron` but as you can see, there is no consensus.

**Comment by samhinshaw** [comment]
Ah-hah, perfect!  Thank you, I should really check twitter more than once a month...
