### ISSUE TITLE
Handed in homework 8 with name homework 10.

### ISSUE THREAD

**Issue by y252zhan** [STAT545-UBC/Discussion#295]
Hi Jenny,

I created an issue with name "Mark homework 10 of Yucheng-Zhang" to hand in my homework 8. Because homework 8 was originally named homework 10.

I found you re-use this issue (which was created for homework 8) to assign peer review for homework 10. I'm wondering if I should leave it, or I should create another issue to hand in homework 10. And will that influence my homework 8 grade?

Thank you!

**Comment by jennybc** [comment]
You can edit the name of any issue create.
