### ISSUE TITLE
Pipe to two commands

### ISSUE THREAD

**Issue by samhinshaw** [STAT545-UBC/Discussion#298]
I'm pretty sure the answer to this question is "no", but I thought I might as well ask!

In R, you can run two commands on the same line like so:
```
head(mtcars); tail(mtcars)
```

**Is there any way to pipe (`%>%`) to two separate functions?** For example, instead of writing:
```
mtcars %>% 
	select(mpg, cyl) %>% 
	head()
mtcars %>% 
	select(mpg, cyl) %>% 
	tail()
```
It'd be nice to just be able to write:
```
mtcars %>% 
	select(mpg, cyl) %>% 
	head(); tail()
```

This seems not to work because R is essentially treating the semicolon as a line break.  So by giving tail a new argument, this works:
```
mtcars %>% 
	select(mpg, cyl) %>% 
	head(); tail(mtcars)
```
But it's not really solving the problem since I'm not getting the desired output for `tail()`.  Any thoughts?

**Comment by ksamuk** [comment]
Maybe magrittr's lambda expression syntax is what you're after? 

```{r}
mtcars %>% 
  select(mpg, cyl) %>% 
  {
    x <- head(.)
    y <- tail(.)
    print(x)
    print(y)
  } 
```

**Comment by jennybc** [comment]
Also look at the tee operator:

``` r
library(magrittr)
1:5 %T>% 
  str() %>%
  mean()
#>  int [1:5] 1 2 3 4 5
#> [1] 3
```

https://github.com/smbache/magrittr

**Comment by samhinshaw** [comment]
Thank you!
