### ISSUE TITLE
Students: it's your time to mark us, how did we do? Survey for course feedback, please fill out!

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#300]
STAT545 changes every year and tries to constantly adapt and evolve itself to be as useful as possible.

We'd appreciate if you took a super short survey (just a few questions) to let us know what was good and what was less good about the course. We also want some feedback about the TAs so that we know if we did a good job or if there are things we could improve on.

The survey is **optional**, and it's **completely anonymous**, so feel free to be as honest as you want.  We welcome any feedback.

http://goo.gl/forms/te6fLJCUQs

**Comment by daattali** [comment]
Thank you to the 5 people who filled out the form so far. Hopefully we'll get a lot more submissions!

To the person who inquired about S3/S4 development: feel free to ask us questions if you have anything in particular you'd like to discuss. I also highly recommend Hadley's Avanced R book, there's a section on [OO](http://adv-r.had.co.nz/OO-essentials.html) that talks about S3 and S4 as well.

**Comment by jennybc** [comment]
Where did this all end up? Take the discussion over the instructors repo, if necessary.

**Comment by daattali** [comment]
The responses are all stored in a Google Form, I'll try to find it and link
to it later
