### ISSUE TITLE
Packages depending on objects in other packages

### ISSUE THREAD

**Issue by mstrimas** [STAT545-UBC/Discussion#306]
I've just starting writing a package with a variety of spatial analysis function. The standard spatial objects in R are defined in the packages `sp` and `raster` and these packages also define things like subsetting with `x[conditions]` for spatial objects. Since I'll be using these objects and methods extensively, would this be a case where these packages would best be put under "Depends" in the Description file?

**Comment by mstrimas** [comment]
Or, does it make sense to leave `sp` as an "Import" and put an `import("sp")` directive in the NAMESPACE file. As I understand it from reading the R Packages book, this would make everything in `sp` available within my package, but would not attach `sp` when my package is attached.  

Hmmm... reading through Hadley's R Packages book has left me more confused. It seems even if I put a package as "Depends", I need an `import()` directive, since "Depends" will only lead to a package being imported if my package is attached. For example, if someone refers to one of my functions with `my_package::my_function()`, I could get an error since my_package isn't attached and therefore the packages it "Depends" on aren't attached.  

This all leads me to wonder: why does the Import/Depends distinction even exist?

**Comment by jennybc** [comment]
This passage is the most relevant, from the bottom of the [Search Path section](http://r-pkgs.had.co.nz/namespace.html#search-path):

> Now’s a good time to come back to an important issue which we glossed over earlier. What’s the difference between Depends and Imports in the DESCRIPTION? When should you use one or the other?

> Listing a package in either Depends or Imports ensures that it’s installed when needed. The main difference is that where Imports just loads the package, Depends attaches it. There are no other differences. The rest of the advice in this chapter applies whether or not the package is in Depends or Imports.

> Unless there is a good reason otherwise, you should always list packages in Imports not Depends. That’s because a good package is self-contained, and minimises changes to the global environment (including the search path). The only exception is if your package is designed to be used in conjunction with another package. For example, the analogue package builds on top of vegan. It’s not useful without vegan, so it has vegan in Depends instead of Imports. Similarly, ggplot2 should really Depend on scales, rather than Importing it.

Whatever you do, you as package author will need to adjust accordingly and none of this should ever be apparent to the user. That is, if you go the Imports route, you will need to either import the whole namespace (not advised), import individual functions, or use the `other_pkg::other_fxn()` approach. From your description, this sounds like one of those situations where you might actually want to use Depends.

**Comment by daattali** [comment]
There's one blog post I bookmarked a year ago because it's excellent , but quite long, and explains this stuff.  

http://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/

There's a section on Depends vs Imports, but it's worth reading the whole thing (it is a bit lengthy)

**Comment by mstrimas** [comment]
Thanks Jenny and Dean. A lot of my confusion has to do with working with S3/4 objects in other packages. I'll read through these and see if it they clear things up.
