### ISSUE TITLE
Google Data Science talk

### ISSUE THREAD

**Issue by hui-tony-zk** [STAT545-UBC/Discussion#307]
@STAT545-UBC/2015_students 

There's a Data Science Seminar by Tim Hesterberg from Google happening on January 15 at 6pm. More details here: http://makedatasense.ca/data-science-seminar-series/#google

(sorry if this is spammy, but figured you guys might be interested in this)

**Comment by jennybc** [comment]
No need to apologize @hui-tony-zk -- I meant to do this too. So thanks.
