### ISSUE TITLE
Extending Data Frames

### ISSUE THREAD

**Issue by mstrimas** [STAT545-UBC/Discussion#309]
Not sure if anyone is still watching this space, but I thought I'd give it a shot. I'm working on building my first real [package](https://github.com/mstrimas/camtrapr), which is for working with data from wildlife camera traps. I currently have a function (`cam_process`) that processes a set of photos into a data frame. I'm now working on writing a variety of functions that manipulate or analyze this data frame.

These functions will only work with data frames that have been output from `cam_process` (i.e. they have columns site, camera, species, and datetime). So, I'm wondering if it makes sense to define a class (S3 or S4) that extends data.frame then define all the functions as methods for this class. Or, am I overthinking this, would it be better to just have normal functions with a bunch of checks at the beginning to ensure that the data frame has the right characteristics.

**Comment by jennybc** [comment]
I highly recommend you create an S3 class for this.

Even all you want to do is create a nice print method, it is often sufficient justification.

**Comment by mstrimas** [comment]
Perfect, that's what I've been doing. Good to hear I'm on the right track!

**Comment by jennybc** [comment]
You will want to think about what your class inherits from. I assume `tbl_df` and `data.frame` will be on the radar. This way you can provide methods, like a print method, for operations you really want to control. And let default behaviour happen for other things, such as subsetting.

**Comment by jennybc** [comment]
But note your objects will lose your `cam_process` class unless you implement your own subsetting methods.

**Comment by mstrimas** [comment]
Yes, I've noticed I keep losing the S3 class when I use `dplyr` functions. A bit of a pain...

**Comment by jennybc** [comment]
Which dplyr functions are we talking about? Here's an example of me adding the `a` class to the usual `tbl_df`, `tbl` and `data.frame` classes. And it survives `dplyr::select()` but not `dplyr::filter()`.

``` r
library(dplyr)
library(gapminder)
(x <- structure(gapminder, class = c("a", class(gapminder))))
#> Source: local data frame [1,704 x 6]
#> 
#>        country continent  year lifeExp      pop gdpPercap
#>         (fctr)    (fctr) (int)   (dbl)    (int)     (dbl)
#> 1  Afghanistan      Asia  1952  28.801  8425333  779.4453
#> 2  Afghanistan      Asia  1957  30.332  9240934  820.8530
#> 3  Afghanistan      Asia  1962  31.997 10267083  853.1007
#> 4  Afghanistan      Asia  1967  34.020 11537966  836.1971
#> 5  Afghanistan      Asia  1972  36.088 13079460  739.9811
#> 6  Afghanistan      Asia  1977  38.438 14880372  786.1134
#> 7  Afghanistan      Asia  1982  39.854 12881816  978.0114
#> 8  Afghanistan      Asia  1987  40.822 13867957  852.3959
#> 9  Afghanistan      Asia  1992  41.674 16317921  649.3414
#> 10 Afghanistan      Asia  1997  41.763 22227415  635.3414
#> ..         ...       ...   ...     ...      ...       ...
class(x %>% select(-continent))
#> [1] "a"          "tbl_df"     "tbl"        "data.frame"
class(x %>% filter(country == "Canada"))
#> [1] "tbl_df"     "tbl"        "data.frame"
```

So yeah you'd need subsetting methods that preserve class. Are you mostly worried about using `dplyr` functions inside your package functions or out in scripts that use your package?

**Comment by mstrimas** [comment]
Within functions in the package I just add the class back to the object before returning it, which seems to solve the issue. So I suppose I'm mostly worried about use outside the package. I'm not keen on defining a bunch of subsetting methods, so I'll probably just leave it for now, maybe define an `as_cam_process()` function so users can convert correctly formatted data frames back to this class.

**Comment by jennybc** [comment]
Sounds like you have a good plan.
