### ISSUE TITLE
Setting up Git/Cloning my repo to my local computer

### ISSUE THREAD

**Issue by RosieRedfield** [STAT545-UBC/Discussion#315]
I'm following the Happy Git instructions, and got to step 10.2.  But when I enter 'less README.md' my terminal shows the title of the repo and the contents of the README (' Repo!' and 'for STAT 545A' and then adds many lines of tilde and freezes and beeps at me.
![image](https://cloud.githubusercontent.com/assets/7291055/18330588/57472cec-750e-11e6-9179-d8c72b3942d7.png)

**Comment by samhinshaw** [comment]
Ah yes, you have stumbled into the wonderful world of command-line text editors/viewers ([less, vim, nano, etc](https://xkcd.com/378/)). The reason you're getting error beeps is that  [`less` is just a text viewer](https://en.wikipedia.org/wiki/Less_(Unix)), so when the `less` program is open in terminal, the keyboard is used for command shortcuts, not text entry.  For example "q" is quit and "h" is help.  

If you'd like to try using less, you can type `man less` or `less --help` for a manual or summary of available commands. However, it could be just as effective to print the contents of a file to screen with `cat README.md`. If you'd like to try a simpler command-line text editor, I'd recommend `nano`. 

I think you also may be able to open your README.md in textedit with `open -a TextEdit README.md`

**Comment by RosieRedfield** [comment]
TextEdit works, but then I get stuck at the next step...  Maybe I'll wait until I understand WHY I'm doing this.
Thanks!

**Comment by jennybc** [comment]
@RosieRedfield what OS are you on? Your screenshot looks like you have ended up in an editor. You've definitely ended up somewhere that we didn't mean you to. Those `less` commands should just print something to screen and are there as sanity checks that things that should exist do, in fact, exist.

**Comment by RosieRedfield** [comment]
Old MacBook Pro.  Mac OS 10.10.3, I think.  
Is the goal that I should be able to make an edit in my shell and have it show up on github, and make an edit in github and have it show up in my shell?

**Comment by jennybc** [comment]
> Is the goal that I should be able to make an edit in my shell and have it show up on github, and make an edit in github and have it show up in my shell?

Yes that is a long-term goal. But not the goal of [10.2 Clone the repo to your local computer](http://happygitwithr.com/push-pull-github.html#clone-the-repo-to-your-local-computer), so I've obviously set you up for failure there. Feel free to wait on this, since you don't need Git/GitHub set up for tomorrow.

But if you feel like continuing, just ignore the `less` commands! They shouldn't be *doing* anything, just printing stuff to screen. So skip 'em. @samhinshaw can you follow up so we revise the instructions appropriately?

**Comment by RosieRedfield** [comment]
at 10.3, I can add my new line and see it with TextEdit, but 'git commit -a' gets me into another tilde-beep situation!
I'll try to stay for office hours after tomorrow's class.

**Comment by samhinshaw** [comment]
The issue you're running into there is that git wants you to specify a commit message, for example:
```
git commit -m "A commit from my local computer"
```
But we'll get to this in class tomorrow, and I'll be around after class to answer any questions :smiley:

**Comment by RosieRedfield** [comment]
Hi again Sam,

Thanks for all your help this morning.  I've now completed Step 10 and most of Step 13.  But the conflicting-edits problem this morning has left a toxic residue that prevented RStudio from completing the 'push' step (see screenshot of RStudio error message below).

Is there a way to fix this?

Thanks,

Rosie

![first commit from rstudio](https://cloud.githubusercontent.com/assets/7291055/18367994/8f1328fa-75d2-11e6-9fe6-965abd5aaa8c.png)

**Comment by samhinshaw** [comment]
Hi Rosie, 

I can think of two quick ways to try to fix this issue. 

1. Simple - try restarting the computer. Hopefully this will fix the issue!
2. Try git's recommendation of manually deleting the file. This can happen from time to time when you are using git in the command line as well as git in RStudio. In terminal, type the command below. 

Cautionary note: be VERY CAREFUL when using the `rm` command (short for "remove"), as this command irreversibly deletes files, and typos can be dangerous. If you'd prefer to avoid this danger, you can go to your `.git/` directory in finder and delete the index.lock file manually.  If Finder is not set up to show hidden files, you can also use *Go > Go to Folder*. 
```
rm /Users/rosie/stat545_test/Sept8_git/.git/index.lock
```

**Comment by jennybc** [comment]
I started replying to this but got sidetracked. I would do @samhinshaw's second suggestion. Do exactly as git says and delete that lock file.

The part of this that is so perverse is that one often creates the most Git puzzles for oneself when least equipped to solve them = at the very start. Sorry about the lack of usability for Git.

You could also just trash this entire git repository and chalk it up to a learning experience. This is just some remnant of an earlier snafu.
