### ISSUE TITLE
no file on git tab-beginner question

### ISSUE THREAD

**Issue by rfalsafi1373** [STAT545-UBC/Discussion#318]
Hello everyone, i am a beginner so my apologies and it is a question and an observation: after the class i created a new Rmarkdown file "AfterClassTesting" and everything went fine just i could not see any files in the git tab on the top, right side to stage and then commit
I finally closed the Rstudio session, opened it again and then I could see and managed to stage, and commit and push them
Is it normal? am i doing something

**Comment by jennybc** [comment]
First, I would just be happy that you now have the Git tab.

Second, why would this happen? Most likely explanations:

  * You had launched this RStudio instance *before* you installed Git. Seems unlikely, at this point, but possible.
  * When you create this new Rmd file, you were not inside an RStudio Project that was a Git repo. But somehow, when you relaunched, you were.

I would let this be a mystery and be glad that all seems well.

**Comment by rfalsafi1373** [comment]
I shall continue on my path and will be positive about it.  
:)
Thank you very much
