### ISSUE TITLE
Video from 9/13 class?

### ISSUE THREAD

**Issue by scienceisfiction** [STAT545-UBC/Discussion#322]
I'm trying to sell friends and colleagues on this RStudio/GitHub workflow and was hoping to share the video spoof on thriller/horror film trailers about improved workflow thanks to use of these tools. I looked through the slides and links on the website but couldn't find it--where would I find the link?
Thanks!

**Comment by samhinshaw** [comment]
[Here you go](https://www.youtube.com/watch?v=s3JldKoA0zw) 😄

**Comment by jennybc** [comment]
Will one of you open an issue on the course website repo to remind me to add that?

**Comment by scienceisfiction** [comment]
Thank you!
