### ISSUE TITLE
Rmarkdown shortcut

### ISSUE THREAD

**Issue by jaehyuns** [STAT545-UBC/Discussion#339]
Hi Jenny, I would like to ask you how you typed the below one in the class
'''{r}

'''
I saw you not typing each of them like ' ' ' { r } enter enter ' ' '  but you used something like a shortcut. (was it copypaste?)

**Comment by ksedivyhaley** [comment]
Win:  Ctrl+Alt+I
Mac: Command+Option+I

[Keyboard shortcuts list here](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)

**Comment by jaehyuns** [comment]
Thank you very much!!
