### ISSUE TITLE
lotr project didn't make it into github repository

### ISSUE THREAD

**Issue by kjkaal** [STAT545-UBC/Discussion#361]
I committed and pushed the changes to the lotr files from today to github but can't find it on there anywhere.

I can easily locate the files on my computer but since they are their own project they are outside of the folder that is linked to the class repo.
How do I get the lotr_tidy .Rproj into my class repo or generally into github?

**Comment by jennybc** [comment]
I own the lotr-tidy project and have not given any of you permission to push. So it's not possible for you to **push** into it. You must have gotten some sort of error message on the attempt to push.

If you want to work on someone else's project like this, you need a different workflow: you need to **fork** the repo on GitHub. Then clone it to your computer. Then when you push, by default, you will push into **your copy or fork**. And, if you want, you can propose your changes back to me as a pull request.

I've never demo'd this workflow in STAT 545 before. But maybe we could do it? 🤔 We are already very busy in class, though.

**Comment by kjkaal** [comment]
Yes, just checked, the push did not go through.

Will we be using lotr data or gapminder for HW_04?
If it involves lotr, I am not clear on how we would submit that to our class repo if the project itself is not part of it.

**Comment by jennybc** [comment]
No I don't think you'll use the LOTR data.

But even if you did, you could copy over, say, the main tidy CSV file to your repo. Commit it. And start coding around it.
