### ISSUE TITLE
Peer Review - how to get to one I've been assigned?

### ISSUE THREAD

**Issue by AlexisBlack2g** [STAT545-UBC/Discussion#362]
Hi all - probably a silly question, but how do I find the peer reviews I've been assigned to, other than clicking the link in my email? 
(I believe I've missed one of the reviews I should have completed for HW02, but don't have the emails anymore, so I'm not sure. If I was assigned to you and haven't responded yet, my apologies!)

**Comment by jennybc** [comment]
Try this URL to see all issues on github.com assigned to you:

https://github.com/issues/assigned

**Comment by jennybc** [comment]
Or click on "mentioned" there.

**Comment by AlexisBlack2g** [comment]
yay - thank you!
