### ISSUE TITLE
My Peer Reviews

### ISSUE THREAD

**Issue by sinaneza** [STAT545-UBC/Discussion#370]
Dear Professor and TA

 I think I have to inform you that my peer reviews on hw01 and hw02  were done as a direct comment on the main issue created by designated peers (I mean mark homework02 ...), not in the issue created by the professor assigning me the peer review.

As a result, I would appreciate whether you could consider those comments as my peer review.

@jennybc 

Sincerely Yours.
Sina Nezafatkhah

**Comment by jennybc** [comment]
Thanks for letting us know @sinaneza. The TA will be looking at all of those issue, so in that case they will still find your reviews when they mark. At least I hope so! Let me know if you get penalized for no review and we can sort it out.

**Comment by jrebane** [comment]
Hi @sinaneza - no worries about the review. I found it eventually and assessed it accordingly.

Thanks for checking in regardless!

**Comment by sinaneza** [comment]
Dear Professor
Thanks for your kind remarks

I have noticed that our TA, Johanes (@jrebane) said that no peer review of
me was conducted for steif_jonathan-zvi's hw02.

I think that this was the only review I did as a direct comment on the
peer's original issue for his/her homework.

@jennybc @jrebane

regards
Sina Nezafatkhah

**Comment by sinaneza** [comment]
@jrebane

Thanks alot.
I appreciate you.
