### ISSUE TITLE
microsoft c + + runtime error when try to embed images

### ISSUE THREAD

**Issue by kmcmahen** [STAT545-UBC/Discussion#386]
Every time I try to embed the plot images generated in hw05 into my .Rmd file, I get a Microsoft C++ runtime error and my RStudio shuts down. It happens when I copy the path to the image into ![Alt text](/path/to/img.png).

I unfortunately have some spaces in some of the folder names (including my main username) - is it possible that this is the cause? Any recommendations?

**Comment by samhinshaw** [comment]
That does seem odd. Are you embedding with an absolute path (one starting with C:/, for example) or relative path? That may help clear up your suspicion with spaces in file names. 

Otherwise, is it possible to get a copy of the error message, or does it only flash quickly before RStudio crashes?

**Comment by kmcmahen** [comment]
Here is my code and a snip of the error (it doesn't close till I exit or press okay). As far as I know I'm using an absolute path...

![image](https://cloud.githubusercontent.com/assets/22041501/19614405/ba06c01e-97a9-11e6-86c1-a45f59d8cc63.png)

![image](https://cloud.githubusercontent.com/assets/22041501/19614310/bfee7f5e-97a8-11e6-916b-222d3b6c28f8.png)

**Comment by jennybc** [comment]
Agree that the rampant space are asking for heartache.

But why can't you use a path relative to the project? That seems preferable anyway. What other person in the world would this path work for? No one. Absolute paths are, in general, to be avoided. Or, more precisely, only formed at run-time, in a specific context, where they can be guaranteed to be correct.

**Comment by samhinshaw** [comment]
It looks like your problem may be unrelated.  

https://support.rstudio.com/hc/en-us/community/posts/210524068--Runtime-to-terminate-in-an-unusual-way-

However, you could still try embedding with a relative path, which is essentially to say '<WorkingDirectory>/path/to/image'

**Comment by oganm** [comment]
Remember when adding a relative path you do not put a / at the beginning of the address though

**Comment by kmcmahen** [comment]
No luck with the relative path either... I will plan to come to office hours!

**Comment by samhinshaw** [comment]
Worth trying this--mentioned by Kevin at the very end of the linked RStudio Help thread:
![delete](https://cloud.githubusercontent.com/assets/14186005/19621687/1be006ea-984c-11e6-9e97-087144c18259.png)


That's:
```
<project>/.Rproj.user/notebooks
<project>/.Rproj.user/unsaved-notebooks
```

**Comment by kmcmahen** [comment]
FYI - if anyone else was having this issue, it was solved by downloading the new preview version of R Studio
