### ISSUE TITLE
Can't push to github

### ISSUE THREAD

**Issue by kjkaal** [STAT545-UBC/Discussion#387]
Hello,

I am unable to push my HW_5 to github. I am getting an error message saying the following
To https://github.com/STAT545-UBC/kaal_katrin-julia.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/STAT545-UBC/kaal_katrin-julia.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I think it may be related to removing a file on github labeled Rapp.history earlier today.
I have no iead how this file ended up on github and removed it to keep my repo clean.
I didn't pull before trying to push and now, when I try to pull from github it's telling me
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

Nor sure how to submit my HW if I can't resolve this tonight.

**Comment by kjkaal** [comment]
I looked up the error code on github help. I pasted what it said below.
I can't figure out what *exactly* I need to type into Terminal to get it to work. 
I don't know what my branch name is...

Dealing with non-fast-forward errors
Sometimes, Git can't make your change to a remote repository without losing commits. When this happens, your push is refused.

If another person has pushed to the same branch as you, Git won't be able to push your changes:

git push origin master
To https://github.com/USERNAME/REPOSITORY.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/USERNAME/REPOSITORY.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.
You can fix this by fetching and merging the changes made on the remote branch with the changes that you have made locally:

git fetch origin
# Fetches updates made to an online repository
git merge origin YOUR_BRANCH_NAME
# Merges updates made online with your local work
Or, you can simply use git pull to perform both commands at once:

git pull origin YOUR_BRANCH_NAME
# Grabs online updates and merges them with your local work

**Comment by jennybc** [comment]
The formatting of your message makes it really hard to read. You can insert text verbatim, such as stuff you've copied from the terminal, by surrounding it with three backticks. 

<pre lang="no-highlight"><code>```
blah blah blah
```
</code></pre>

which will appear here as:

```
blah blah blah
```

While composing a comment, you can always click the "Preview" tab to see what it's going to look like, so you can refine.

Armed with this new knowledge, can you show me what `git status` shows? You could also repeat some of the above info, in a more readable form.

**Comment by kjkaal** [comment]
I included a screen shot of what 'github help' says about non-fast-forward errors, which my problem apparently falls under.
I have tried all three suggested commands in Terminal but they all gave me a 'fatal error'. 
This is what my terminal says when I open it:
```
Last login: Fri Oct 21 23:06:19 on ttys000
Katrins-MacBook-Pro:~ kjk$ 
```

![screen shot 2016-10-22 at 11 07 55 am](https://cloud.githubusercontent.com/assets/22040785/19621499/2029c6b8-9848-11e6-8b96-70d0bb2164b3.png)

**Comment by samhinshaw** [comment]
I'm so sorry this has happened to you! At the beginning of class Jenny mentioned that git is great until you run into problems... this is that point 😢 
The first thing I'd recommend doing is copying your entire repository to another folder somewhere else on your computer so you've got a backup. 

Fortunately you don't have to worry about branch names (you only have master): 
![master](https://cloud.githubusercontent.com/assets/14186005/19621608/2aecec36-984a-11e6-9564-f8de33a72a84.png)

If you're reading help online, it may get confusing if you see references to merging branches.  You're not merging branches, but merging local & remote.  Fortunately, the process is essentially the same!  What you want to do is resolve the merge, and then git will let you push and pull again. This needs to be done locally. 

The first thing to do would be to navigate to your git repo in terminal and run `git status`. If you're not comfortable navigating around your computer with change directory commands, you can also open your R project/repo in Rstudio, and then go to [Tools] -> [Shell], which will open terminal in your repo's working directory. 

Then, could you print that error message here, within the backtick formatting Jenny mentioned?

Further reading in [this StackExchange thread](https://stackoverflow.com/questions/11646107/you-have-not-concluded-your-merge-merge-head-exists): `git merge --abort`

You can also check out the [Official Git Documentation](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#Basic-Merge-Conflicts) 🎉, which is an awful read but will give you the most detail on solving this error.

**Comment by jennybc** [comment]
I suspect you need to do `git merge --abort`, `git pull`, `git push`. But you still haven't shown us the output of `git status` which would make the situation much more clear. We don't need the screenshots of the github help. We need to see information about the status of your particular repository.

So this is still my question:

> Armed with this new knowledge, can you show me what `git status` shows? You could also repeat some of the above info, in a more readable form.

**Comment by kjkaal** [comment]
Sorry, I misunderstood which part of my original message you meant.
This is the error message I get when I try to pull from github:
```
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
```
This is the error message I get when I try to push to github:
```
To https://github.com/STAT545-UBC/kaal_katrin-julia.git
! [rejected] master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/STAT545-UBC/kaal_katrin-julia.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by kjkaal** [comment]
I did what Sam mentioned and ran `git status` from the shell in RStudio.
This is what it told me:
```
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
```

**Comment by kjkaal** [comment]
It seems I was able to resolve the problem by following Sam's suggestions.
I am able to push again but now my .Rmd doesn't knit anymore due to a file finding problem :(

**Comment by ksedivyhaley** [comment]
Have you tried pulling?

"Integrate the remote changes (e.g. 'git pull ...') before pushing again."

I got a similar error and that fixed it for me. It should integrate with
your new stuff OK but you can backup HW 5 in another folder somewhere just
in case.

**Comment by khushahal** [comment]
hey i am also facing same problem  see here ----


$ git push origin master
To https://github.com/khushahal/khsprivatechat.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/khushahal/khsprivatechat.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

another command git status 
$ git status
On branch master
nothing to commit, working tree clean

i am anable to commit my project to github since 2 days

**Comment by FiloSpaTeam** [comment]
@khushahal the same for me. I need to force to push and Github diffs doesn't see changes in Diff view but they are in the code O.o

**Comment by mayurpaghdal07** [comment]
@kjkaal  write this command 
git pull --allowed-unrelated-histories origin master
git push -u origin master

**Comment by febu1300** [comment]
delete the repository on github create new(don't commit on github), push your files from you localhost.

**Comment by cyWisp** [comment]
Had the same problem- mayurpaghdal07's solution worked for me. Thank you!!!

**Comment by xajhwj** [comment]
! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:xajhwj/JAVA.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Me too,how to do it???

**Comment by vincenzocoia** [comment]
@xajhwj Try doing a `git pull` before pushing.

**Comment by mohammedmunna** [comment]
try: 
```
git pull --allow-unrelated-histories origin master
git push -u origin master
```

**Comment by Prasan1** [comment]
@mohammedmunna thanks for those two lines on your comment. That solved my problem.

**Comment by sriiraj** [comment]
> try:
> 
> ```
> git pull --allow-unrelated-histories origin master
> git push -u origin master
> ```
> git pull --allow-unrelated-histories origin master was not working for me plzz help me with this?

**Comment by umahari** [comment]
blahhhhhhhh

**Comment by Jeysoon** [comment]
git push origin master --force worked just fine for me

**Comment by rajeshmitsm** [comment]
git pull --allow-unrelated-histories origin master
git push -u origin master

  these commands just worked...thanks alot

**Comment by OMoF** [comment]
git pull --allow-unrelated-histories origin master
git push -u origin master

this to line work for mee 
tnx a lot.!!!!!!!!!!!!!

**Comment by revoldo** [comment]
git push origin master --force
work for me, thanks

**Comment by alexey100196** [comment]
git push origin master --force
Спасибо

**Comment by hussein18149** [comment]
To https://github.com/AshaAbukar/AFRICAN-BUZZ.git
 ! [rejected]        blue -> blue (non-fast-forward)
error: failed to push some refs to 'https://github.com/AshaAbukar/AFRICAN-BUZZ.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.


how can i attend that

**Comment by ML-magazine** [comment]
Basically, this issue occurs when online and offline repositories are not merged. 
If you added a theme or upgrade on github, it means your local repo needs to be upgraded as well. To solve this, I would advise you clone your online repo to your favorite directory-desktop, (git clone https... ). This is a manual solution, works all the time. Now you can add, commit and push.

**Comment by annatorsu** [comment]
> git push origin master --force
> work for me, thanks

worked thanks

**Comment by annatorsu** [comment]
> git push origin master --force worked just fine for me

**Comment by annatorsu** [comment]
worked thanks

**Comment by clouddjoe1** [comment]
git push origin master --force

 worked just fine for me

**Comment by Mann23** [comment]
> 
> 
> @kjkaal write this command
> git pull --allowed-unrelated-histories origin master
> git push -u origin master

what does this line do?
