### ISSUE TITLE
The R graph catalog page appears to be down (http://shiny.stat.ubc.ca/r-graph-catalog/ )

### ISSUE THREAD

**Issue by philstraforelli** [STAT545-UBC/Discussion#481]
Has the site been moved? Is it available elsewhere?

**Comment by jennybc** [comment]
No, not moved, but obviously down. I need to move that. But in the meantime, I've asked the sysadmin what's up. Thanks.

**Comment by jennybc** [comment]
Back up now! Thanks for letting me know.

**Comment by giannetti** [comment]
Sorry to be a nag, but it appears to be down again. Clearly many of us rely upon it!
