### ISSUE TITLE
Git Bash Issue

### ISSUE THREAD

**Issue by sinaneza** [STAT545-UBC/Discussion#485]
Hi Everyone

I want to start working with Rstudio after a while.

I have installed Rstudio and git on my new laptop; however, while opening shell in Rstudio, cmd.exe opens instead of git bash.

Can anyone help me with this issue??

Best
Sina
@jennybc

**Comment by oganm** [comment]
what happens when you do `git status`

**Comment by jennybc** [comment]
Re-googling this myself ... one possible line of inquiry is looking at your PATH.

**Comment by sinaneza** [comment]
Hi all 
Thanks for your quick responses.
git status says: "fatal: Not a git repository or any of the paren directories: .git".
@oganm @jennybc

**Comment by sinaneza** [comment]
I realized the problem.

Problem was that I should have started a repo in my github and then copied the url path of that repo in  the url section, while creating a git new project in Rstudio
Again thank you very much for your helps professor Bryan @jennybc  and Ogan Mancarci @oganm

**Comment by jennybc** [comment]
Well, glad it's sorted out.
