### ISSUE TITLE
Help needed to get git work on RStudio

### ISSUE THREAD

**Issue by lh563** [STAT545-UBC/Discussion#512]
Hi everyone, 

I got trouble on today's class and cannot get git work on my computer. I kept being informed that the git was not detected on the system path even when after I config the git. Anyone can help?
@vincenzocoia

**Comment by vincenzocoia** [comment]
@lh563 Can you indicate the error message that you're getting? Also, are you interacting with git through RStudio?

**Comment by lh563** [comment]
change the path for git from /usr/bin/git to /usr/local/bin/git, and then problem solved
