### ISSUE TITLE
Little trick to reorder factor based on row order in data.frame using dplyr

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#52]
Ever since starting to use `dplyr` extensively a few weeks ago I've been using this "trick" to easily order the levels of a factor based on the row order of a dataframe.   
In short: if you have a data.frame with the rows in order and you want the levels of one of the columns to be in that same order, you can use `df <- mutate(df, col = factor(col, col))`.  That might look a little weird, but think about it for a minute and see why it works :)  
It's not fancy or clever or anything, it's just a little nicer and easier to write than the ways I was previously using to do this.

Example:
```
library(dplyr)
df <- data.frame(
	num = 5:1,
	word = c("five", "four", "three", "two", "one"))
levels(df$word) # levels are alphabetical by default
df$word # right now the order is 5,4,3,2,1
df <- df %>%
	arrange(num) %>%   # rearrange the df in the order we want (1,2,3,4,5)
	mutate(word = factor(word, word)) # this line reorders the factor in the same order
levels(df$word)  # now the levels are 1,2,3,4,5
```

I hope some of you will find this useful

**Comment by davidroberson** [comment]
This was very helpful as I have 96 subject id's.  I want to facet wrap (ggplot2) by the row order of the data frame and not alphabetically.  

Thanks.

**Comment by sjackman** [comment]
I still use this trick a lot to give my levels a meaningful order without having to hard-code the order in the code.

**Comment by colinbrislawn** [comment]
This was so helpful. I wish this functionality was in base R.

I found this method worked for me:
```R
df <- df %>%
    arrange(num) %>%   # rearrange the df in the order we want
    mutate(word = factor(word, unique(word)) # reorders the factor in the matching order
```

Note that I'm using `unique(word)` to deal with any duplicates in this category.

Is there a better way to do this programmatically?

**Comment by sjackman** [comment]
I believe the `unique` is not necessary. Duplicates are handled appropriately by `factor`.
Does Forcats have this functionality? http://forcats.tidyverse.org

**Comment by colinbrislawn** [comment]
>Evaluation error: factor level [2] is duplicated.

That's what I get when I don't use `unique(word)`. 🤷‍♂️ 

Looks like [fct_reorder](https://forcats.tidyverse.org/reference/fct_reorder.html) might be the tidyverse way of doing this.

**Comment by sjackman** [comment]
```
> x <- c("a", "b", "b", "c"); factor(x, x)
Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [3] is duplicated
```
I see the same error as you, Colin. I stand corrected.
