### ISSUE TITLE
Rendering large html files on GitHub

### ISSUE THREAD

**Issue by rasiimwe** [STAT545-UBC/Discussion#526]
Hi, 

I have an rmd file with a few plotly plots that I would like to knit to html for my plotly plots to be rendered.

Commiting staged file changes is successful with the warning  `the diff is extremely large & may cause Rstudio to slow down or even hang`

**On github:** The file can't be rendered because it's large 👇 

`View Raw`
`(Sorry about that, but we can’t show files that are this big right now.)`

👉 How best can such large html files be rendered on github?

Thanks

**Comment by zeeva85** [comment]
Just a thought , Maybe GitHub pages ?

**Comment by rasiimwe** [comment]
Issue solved by following this [guide](https://www.finex.co/how-to-display-html-in-github/)
