### ISSUE TITLE
Installing Plotly Package 

### ISSUE THREAD

**Issue by JasmineLib** [STAT545-UBC/Discussion#527]
Hi all,

I'm having some trouble installing the plotly package.
when I run:
install.packages("plotly")
it seems to install, but when I try to load the package: library(plotly), it says "Error in library(plotly) : there is no package called ‘plotly’" 

so far, I have tried updating RStudio, updating all my packages (including ggplot2). 
I am currently using R version 3.3.3, and am in the process of updating to 3.5.1 on a mac. 

Chad tried to help me with this, but we weren't able to solve the problem yet. If anyone has tips on how to get plotly running, and also can help us update R (as we were having issues with this too) it would be really appreciated! 

Thanks,
Jasmine

**Comment by ChadFibke** [comment]
Hey @JasmineLib,

Option 1:
Open up the R (not R studio) application on your mac > Click the R tab (found in the menu bar, to the right of the apple icon) > Click the "Check For R Updates" >  Then follow the installation process in R. 

Option 2:
Go to the  [R for Mac site](https://cran.r-project.org/bin/macosx/) > Click on the "R-3.5.1.pkg" link and let it download > click on the downloaded pkg icon that has R-3.5.1 (This appeared on my desktop) > Then it will take you through the normal installation process that you'd follow for any other application you download like google chrom. 

If neither of these options work please let me know!

**Comment by JasmineLib** [comment]
@ChadFibke Thank you so much for the extra help!! 

I was able to update R using the second option you posted. I was also able to re-install all the packages in this this newest version of R, and plotly appears to be working for me now! 
Thanks again! 

For anyone experiencing the same plotly issue, I think the problem I was having was that the version of R i was using was out of date.
