### ISSUE TITLE
R Markdown functions for Exercise 2

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#545]
@545a-2019-20-team
In Exercise 2, the instructions state that we should 
"Did you use at least three functions?
Given that you did, does your code run error-free?"

Are these the same functions that we used in Exercise 1, or is there a different type of code that we need to use?

**Comment by NarayanGopinathan** [comment]
Moreover, are the functions the same as code? Do RMarkdown functions count as code or is that something distinct?

**Comment by aleurcelay** [comment]
The markdown functionalities are different than the code functions for exploring your dataset. Some of these functions that we are asking you to use in the exercise 2 are, for example: `str()` or `summary()`

**Comment by vincenzocoia** [comment]
> Are these the same functions that we used in Exercise 1

No, Exercise 1 refers to five markdown features. Exercise 2 refers to three R functions.

> Moreover, are the functions the same as code?

Well, the code you write ought to explicitly contain a function.

**Comment by vincenzocoia** [comment]
Beat me to it, @aleurcelay :)

**Comment by NarayanGopinathan** [comment]
Thanks!
