### ISSUE TITLE
Email address spelled incorrectly

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#546]
R Terminal is giving me error messages because my email address is spelled incorrectly. How can I fix this? 
![image](https://user-images.githubusercontent.com/34103046/64915817-caa33980-d724-11e9-8267-b26ec4b4fbbd.png)

**Comment by vincenzocoia** [comment]
My first guess is the space after the double dash. `-- global` should be `--global`. Does this make a difference?

**Comment by NarayanGopinathan** [comment]
No, I  had mistyped my own email. Alejandra helped me figure this one out. Thanks!
