### ISSUE TITLE
Object gapminder not  found

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#547]
I have downloaded the gapminder data package again to do Exercise 2, but I did when I try to use the functions like 'summary()' with it, it says that the object 'gapminder' is not found. Why am I not able to use the gapminder data?

![image](https://user-images.githubusercontent.com/34103046/64925571-64abc600-d7a7-11e9-840d-35efa68de020.png)

**Comment by vincenzocoia** [comment]
It looks like the order in which you executed your code is different from the order it appears in your script. Did you run line 53 before line 54?

**Comment by NarayanGopinathan** [comment]
I ran summary(gapminder) on its own, by selecting run selected line.

**Comment by NarayanGopinathan** [comment]
I reran it and it seems  to be working. Thanks!
