### ISSUE TITLE
Peer review user not found

### ISSUE THREAD

**Issue by vittorioromaniello** [STAT545-UBC/Discussion#551]
Hi, 

I have been assigned to peer review the homework of @carleenaortega but when i open the hw repository i get a 404 error.

https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-carleenaortega 

What should i do?

**Comment by carleenaortega** [comment]
Hi,
I am away this week and Vincenzo gave me an extension for the assignment
until Sept 27th. Let me know if there's anything I need to do.

Thanks,
Carleena


>>> vittorioromaniello <notifications@github.com> 09/19/19 8:29 PM >>>
Hi,
 I have been assigned to peer review the homework of @carleenaortega but
when i open the hw repository i get a 404 error.
 https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-carleenaortega
 What should i do?

**Comment by yuliaUU** [comment]
Pick a random person from a list and review their work!

**Comment by yuliaUU** [comment]
@vittorioromaniello  who did you end up choosing?

**Comment by vittorioromaniello** [comment]
I chose @chiukenny, also left a comment in my submission to avoid confusion.

**Comment by yuliaUU** [comment]
Thanks a lot!
