### ISSUE TITLE
.md file is not showing up properly

### ISSUE THREAD

**Issue by smithlauren** [STAT545-UBC/Discussion#555]
I am just finishing up my homework and checked my .md file in Github, but it shows up with the YAML header items in a table (?), and none of my other work shows up correctly. I'm also not realizing that this also happened with my cm007.md file that I did in class today. 
This is what I have in my header:

title: "Homework 2"
author: "Lauren Smith"
date: "September 24, 2019"
output: 
  html_document:
    keep_md: true

Here is the link to my hw02 folder with the  hw02.md file in it: https://github.com/STAT545-UBC-hw-2019-20/stat545-hw-smithlauren/tree/master/hw02

**Comment by wvictor14** [comment]
Hi Lauren,

The problem with your md file is that the `DT::datatable()` function produces output that is only compatible with html, but not markdown.

If you want your markdown to display those tables, I would suggest using `kable` instead of `datatable`

Victor
