### ISSUE TITLE
Late uploading the URL

### ISSUE THREAD

**Issue by nshen7** [STAT545-UBC/Discussion#556]
Hi, I forgot to upload the URL for Assignment 2 so now it's showing "LATE". But my repo history would show that the homework is done on time... Is there any chance it won't be counted as late?

**Comment by aleurcelay** [comment]
Hello @NingShen1997, 

I can take a look at your homework later. 
Next time, please put your tag release link on Canvas!

**Comment by nshen7** [comment]
> Hello @NingShen1997,
> 
> I can take a look at your homework later.
> Next time, please put your tag release link on Canvas!

Of course. Thank you!

**Comment by vincenzocoia** [comment]
As long as the submission happened before the deadline, you're fine. Any penalty would just be confined to the "tidy submission" section of your homework.
