### ISSUE TITLE
HW04 code

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#564]
Dear team,
I am working on homework 4 as I had received a compassionate extension. I have completed exercise 1, but I have received errors in trying to do exercise 2 and 3. 

![image](https://user-images.githubusercontent.com/34103046/66672449-245b2e80-ec13-11e9-872a-a8f2bbc769e2.png)

I was surprised to see in exercise 2 that it "could not find function "%>%"", as the %>% operator is something we have used many times. Can anyone help me figure  out what's wrong here?

Similarly, for exercise 3, I  copied and pasted the code from the assignment, but it couldn't run. It "could not find function "read_csv". How am I supposed to get the email list?

**Comment by aleurcelay** [comment]
Hi @NarayanGopinathan,

I think you didn't load the `tidyverse`, try loading it and running the code again.

**Comment by NarayanGopinathan** [comment]
Got it, thanks!
