### ISSUE TITLE
How to use Write_csv

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#565]
Hi,
For Exercise 3 in Assignment 5, I have to experiment with write_csv and read_csv. I found [this website ](https://www.rdocumentation.org/packages/readr/versions/0.1.1/topics/write_csv) explaining it, but I  still couldn't make it work. Can anyone help me write a csv file from R?

![image](https://user-images.githubusercontent.com/34103046/66944883-e7bc7800-f002-11e9-950b-69f17f8f4cff.png)

**Comment by kgwkyle** [comment]
Try using this format instead: 

_write_csv(**dataset-to-be-used**, here::here("**new-name-for-file**.csv"))_

This will place the CSV file in your working directory. Note that you need to change the name of the **bold** items.

**Comment by NarayanGopinathan** [comment]
Hi Kyle,
Thanks for that! Unfortunately, I did that and had the same problem. 

![image](https://user-images.githubusercontent.com/34103046/66950142-afba3280-f00c-11e9-8b15-fd5a1300aa9f.png)

**Comment by NarayanGopinathan** [comment]
Actually, I did it again and it worked! It wrote the csv to my hard drive under my documents. 
Thanks Kyle!
