### ISSUE TITLE
GGSave 

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#567]
Hi team,
Exercise 5  requires us to use ggsave(). How does ggsave() work? I tried using the instructions [from this website](https://www.rdocumentation.org/packages/ggplot2/versions/3.2.1/topics/ggsave), but I got an error message. When I tried putting in other things in  the place of 'filename', such as "Life expectancy plot", I still got error messages. 

![image](https://user-images.githubusercontent.com/34103046/66965809-ddfd3980-f02f-11e9-8d8a-288b69df085a.png)

By the way, I am hoping to save an image that I had previously generated in exercise 4. 
![image](https://user-images.githubusercontent.com/34103046/66965903-38969580-f030-11e9-950e-4e1cf2e1afc2.png)

**Comment by dy-lin** [comment]
Try:
1. `ggsave("life expectancy by continent", ...)`
2. `ggsave(filename = "life expectancy by continent", ...)`

I think your error originates by the use of `==` instead of `=`.

Also consider using `device = "png"`, and making your filename `"life_expectancy_by_continent.png`"

**Comment by NarayanGopinathan** [comment]
It worked! Thank you!
