### ISSUE TITLE
My Assignment 5 will not knit to PDF

### ISSUE THREAD

**Issue by NarayanGopinathan** [STAT545-UBC/Discussion#568]
I have completed assignment 5, however, and knitted it to html without a problem. However, when I try to knit to PDF, it does not work. Is this a problem, and can I fix it? Or should I just submit what I have to Github and Canvas?

![image](https://user-images.githubusercontent.com/34103046/66982253-8b8d3e80-f06a-11e9-8b46-365f94ad49b0.png)

**Comment by dy-lin** [comment]
Did you try installing `tinytex`?

Something like this maybe?
```
install.packages("tinytex")
library(tinytex)
tinytex::install_tinytex()
```

I think just submitting an `html` knit file is fine, as long as you provide the GitHub Pages link. I don't see that it says anywhere on Assignment 5 that our submission must contain a pdf.

**Comment by NarayanGopinathan** [comment]
Thanks! I have finished and submitted i t.
