### ISSUE TITLE
Error in file(filename, "r", encoding = encoding) :    cannot open the connection

### ISSUE THREAD

**Issue by jordanbrace** [STAT545-UBC/Discussion#64]
Hi,

I've written a pipeline for assignment 9, but I cannot get my makefile to work. Whenever I run source() I get the following error:

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '00_gapminder-pipeline_download-data.R': No such file or directory

I am in the right directory, and there are no typos in the code. Does anyone know what the issue might be?

If it's relevant I'm running RStudio in Windows.

**Comment by armstrong2k** [comment]
Hi

I'm getting the below error while submitting programme assignment 3

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'best.R': No such file or directory

Any solution to resolve this issue

Thankful if you could help me
