### ISSUE TITLE
Future plans for your STAT 545 / 547 coursework repository

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#83]
Hi all,

@santina has raised the question about whether and how to reveal your coursework publicly:

> … making our own course repository public so that we can show other people what type of R projects we have done. It would be beneficial to one's Github account profile …

This is a great point. Once I get the marks submitted I will post again on this thread with some advice -- both conceptual and mechanical -- on how you to make some or all of your coursework visible to the world.

**Comment by Creagh** [comment]
I'd like to bump up this issue.

I'm still wondering if we can/should make our coursework publicly visible.

**Comment by jennybc** [comment]
Hi @Creagh.

In terms of "can", yes you can. You would need to fork your course repo to a repo associated with you personally. Then you could do whatever you want. You could make it public, for example. Or you could just keep a private copy in your own account for posterity. If you don't have any private repos or are running low, I note Bitbucket has unlimited private repos (?I think?).

In terms of "should", it's more complicated. While I have no qualms about students using the internet, with attribution, while they do their STAT 545 work, I don't want wholesale copying and pasting. Which could be tempting if entire course repos are out there in full glory. I wonder if the bits of your work that you want to share are ... the bits that are the most customized and therefore un-copyable? Like an R package or Shiny app? What are you thinking?

**Comment by Creagh** [comment]
Thanks for your response @jennybc 

I was originally thinking that I would like to make my entire course repo public, as a sort of portfolio of the things I've learned in your course. That said, I understand your desire to not tempt future students to start wholesale copy & pasting.

If you prefer, perhaps I can just share the R package and Shiny app from my course repo.

**Comment by daattali** [comment]
@Creagh I had the exact same question about a different course I took with @jennybc , and the main argument against me simply making my whole course repo public was the same one given here: students in the next offering can just copy-n-paste complete assignments. So I did what Jenny suggested and moved the repo to BitBucket.  Yes, you do get unlimited private repositories there.  And if want to showcase your R package and shiny app, you can make separate repos for them as she suggested
