### ISSUE TITLE
Office hours

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#85]
Office hours will be held in ESB 3174, a dedicated room across from the main Statistics Department Office:

  * Tuesdays and Thursdays 11:00am - 12:00pm, right after class <-- **NOTE: we've scaled back to 1 hour, not 2**

**Comment by jennybc** [comment]
@daattali I hope these times work for you? At least for this week? @BernhardKonrad might hang out with us some in class and/or office hours this week, so cc'ing him as well.

**Comment by BernhardKonrad** [comment]
Indeed, I'm around this week and would be more than happy to help. I also look forward to seeing @daattali :)

**Comment by daattali** [comment]
This Wednesday I have a doctor appt at 2pm so I would need to leave campus at 1 that day.  If it'll make it a lot easier for you to keep that specific timeslot and you need me, let me know, I can probably change my appointment to later

**Comment by jennybc** [comment]
@daattali How about you pick the time that works for you Wednesday and we change the time? I'm willing to gamble that we can get that room or something similar.

**Comment by daattali** [comment]
Either <any time> until 1pm 
Or 4pm until <any time>

So I'll tentatively say 11am-1pm

**Comment by jennybc** [comment]
@daattali OK I changed to 11am - 1pm on Wednesday. Will try to confirm room but I imagine office staff not around today.

**Comment by BernhardKonrad** [comment]
I have a meeting Wednesday at 10:30, so I'll be late for office hours.

**Comment by jennybc** [comment]
TAs: you ask for the key to unlock the room from the main STAT office, just across the hall.

**Comment by ksamuk** [comment]
Hi all! I will definitely be there for office hours tomorrow at 11:00AM.

**Comment by BernhardKonrad** [comment]
First week is over, this should be closed or renamed.

**Comment by jennybc** [comment]
thanks @BernhardKonrad will soon delete this convo because this thread is special
