### ISSUE TITLE
Practice issue for 2015 students

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#86]
For the new 2015 crew.

Feel free to post on this thread to convince yourself that you have a GitHub account and can participate in a discussion on an issue thread. Play with the markdown formatting if you wish. This is just a safe place to practice. Remember, however, that it is PUBLIC.

**Comment by AdrianLJones** [comment]
testing, testing, 1,2,3

**Comment by jennybc** [comment]
I hear you @AdrianLJones !
