### ISSUE TITLE
Missed 1st Class

### ISSUE THREAD

**Issue by ahippman** [STAT545-UBC/Discussion#88]
@jennybc , so sorry I missed the first class!!! I just realized that the course started today and not Thursday. What do I have to do now? Is there already homework? Is there a way to look at the lecture notes from today?
Thanks for any help,
Anna

**Comment by namanpaul** [comment]
@ahippman I guess, the first class notes would be sufficient enough. 
Long story short, we need to be ready with R and RStudio installed on our machines. Setting up/ following the twitter account. And yes, skimming through the amazing articles and blog posts @jennybc talked about today.

**Comment by jennybc** [comment]
http://stat545-ubc.github.io/cm001_course-intro-sw-install-account-signup.html

**Comment by ahippman** [comment]
@jennybc and @namanpaul Thanks a lot! I am on it! See you Thursday!

**Comment by jennybc** [comment]
@ahippman Glad you are sorted. So at this point, you close the issue. I could do it but it's good for you to do. Good practice for how this whole thing works going forward. :)

@namanpaul Thanks for answering! This is exactly how this place is supposed to work. The more link-y you can make answers, the better. Good practice for how this whole thing works going forward. :)
