### ISSUE TITLE
GitHub Desktop: read about before you install Git + Git client .... or not

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#89]
In mid August, GitHub announced the release of GitHub Desktop:

https://desktop.github.com

I have not used it but if you are starting from scratch, it should be on your radar.

Assuming it's like previous products GitHub has offered, this will presumably install Git on your computer AND give you a nice Git GUI AND hold your hand when you talk to GitHub. In the past, we had some misgivings about the GitHub Git clients, especially for Windows, but maybe this time it's better?

In any case, I will update course materials to mention this but wanted to put this here in the meantime.

Would love to hear about people's experience with this new product. Tell us which OS you're using.

**Comment by daattali** [comment]
Turns out it's not really a new tool: they previously had a GitHub for Windows client and a GitHub for Mac, but they looked completely different. So GitHub Desktop is simply unifying these two and naming it as one product instead of two.  If I recall correctly, GitHub for Windows was more problematic than Sourcetree for students last year, but perhaps they improved the setup with this new branding.

**Comment by jennybc** [comment]
Interesting @daattali.

For the record Windows folks, we did not like GitHub for Windows because it was hard? impossible? to tell where it left the Git executable. Which is necessary if you want to be able to do git operations from the command line or RStudio, etc., which you definitely want. I believe I described the "hand-holding" as too much like "handcuffs". I don't know if this has gotten better with the new unified product.

**Comment by Haycen** [comment]
I don't know much about Git clients but GitHub Desktop seems quite intuitive for beginners.

[See this video](https://css-tricks.com/first-impression-of-github-desktop/ )

**Comment by daattali** [comment]
The trouble some students ran into last year was that this tool doesn't ask
nor tell you where git gets installed, which is important for hooking up
git with RStudio.  For some people it installed git in a sensible location
(C:/Program Files/git) but for some it was in a really awkward directory.
Perhaps it's better now though.

---
http://deanattali.com
