### ISSUE TITLE
UBC R Study Group

### ISSUE THREAD

**Issue by minisciencegirl** [STAT545-UBC/Discussion#91]
Are you interested in building on your R coding skills and meet other R enthusiasts?

Come check out the UBC R study group: http://minisciencegirl.github.io/studyGroup/

We meet once a week for:
1) Skill Sharing: Share your favourite coding skills and tools with your friends and colleagues in friendly, no-pressure work-alongs.
2) Co-Working: Get together to work on your coding projects, help each other out and share your work.
3) Community Building: Meet new people in your field, organization or community - and find out what we can do when we work together.

Open an issue on our GitHub repo to suggest an event or watch the repo for future events! 
https://github.com/minisciencegirl/studyGroup/issues

Hope to see you there!

**Comment by jennybc** [comment]
I want to give a special endorsement for the upcoming presentation by Richard Iannone, creator of the [DiagrammeR package](http://rich-iannone.github.io/DiagrammeR/). The package itself is amazing and equally impressive is his presentation of it on the web.

30 September 2014, 4:00PM
Biodiversity Room 224
Learn how and why you can use [DiagrammeR](http://rich-iannone.github.io/DiagrammeR/)
