### ISSUE TITLE
RStudio keyboard shortcuts

### ISSUE THREAD

**Issue by daattali** [STAT545-UBC/Discussion#92]
Many students are asking "how did you do *that cool thing*?" when @jennybc uses RStudio live in class.

You can see the RStudio keyboard shortcuts [here](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts).  You can also go to RStudio, click on the `help` menu, then click on `Keyboard Shortcuts`, and it will show you all the shortcuts.

**Comment by npjc** [comment]
Going meta: The keyboard shortcut to bring up the shortcut quick reference within RStudio:
<kbd>shift <kbd>option <kbd>K
