### ISSUE TITLE
question about updating R

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#95]
After I have updated R, I had to install all my packages. Is there a way to make it automatically install all my packages?

**Comment by ksamuk** [comment]
update.packages() should do the trick!

**Comment by csiu** [comment]
In addition to @ksamuk, here is an excerpt from one of the course pages (i.e. [Installing R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html)):

> - If you upgrade R, you will need to update any packages you have installed. The command below should get you started, though you may need to specify more arguments if, e.g., you have been using a non-default library for your packages.
>
> ```
update.packages(ask = FALSE, checkBuilt = TRUE)
```
> Note: this will only look for updates on CRAN. So if you use a package that lives only on GitHub or if you want a develoment version from GitHub, you will need to update manually, e.g. via `devtools::install_github()`.
