### ISSUE TITLE
question about hw 1

### ISSUE THREAD

**Issue by cathyxijuan** [STAT545-UBC/Discussion#97]
I just want to make sure that I am not missing anything.. Hw1 repositories are not read yet? Is that correct? And we need to repositories to do the hw?

**Comment by csiu** [comment]
Correct (since the assignment is to add a `README.md` file to the repo that has yet to be handed out)

**Comment by RashedHUBC** [comment]
i am also confused whether I am missing anything. I haven't got any email to join the repository to submit our homework 1.

**Comment by csiu** [comment]
- The github repos have not yet been assigned
- You can still create the `README.md` files locally
- When you finally get your repo, you can `push` the readme to the repo

**Comment by RashedHUBC** [comment]
Okay. I understand. Thanks.

**Comment by jennybc** [comment]
You should have the email invitation now. Phew.
