### ISSUE TITLE
Course repos are (in theory) set up

### ISSUE THREAD

**Issue by jennybc** [STAT545-UBC/Discussion#98]
You should have received an email inviting you to join our Organization and your own team, specifically.

Once you accept, I would expect you to have access to your own private course repository.

Please let me know if this is NOT what you are seeing.

**Comment by sho-87** [comment]
Received the email, joined the team, but the team does not have any existing repos and it won't let me create a new one...maybe I'm looking in the wrong place?

**Comment by JoeyBernhardt** [comment]
I've also received the email, joined the team, but can't find my own private repository. Thanks for any guidance!

**Comment by weininghu1012** [comment]
Same issues here! Any help would be appreciated!


Weining

**Comment by jennybc** [comment]
OK. Thanks for letting me know. On it.

![](http://i.imgur.com/9rCAjiK.gif)

**Comment by RashedHUBC** [comment]
Me too. I've also received the email, joined the team, but can't find my own private repository.

**Comment by jokagyeman** [comment]
I am having the same problem.

**Comment by jennybc** [comment]
Yes I think it's pretty clear it's universal. When I hook up one, I will hook up all. No need to keep reporting, unless someone's got a new problem to report.

Please hold.

**Comment by jennybc** [comment]
OK. Please see if you now have a repository.

Example: Let's pretend I'm a student. My official name would be `jennifer_bryan`. That would be the name of my singleton team. That would also be the name of my private course repo, so I would go to `https://github.com/STAT545-UBC/jennifer_bryan` and see a repo with a README.

I'd love to hear of a couple successes, if they exist. Once I've heard of a few, we can set that aside and leave this thread open for people with novel problems.

**Comment by jennybc** [comment]
I would also like to hear of a couple successes of a student **writing** to their repo. That can be as simple as an edit through the GitHub browser interface. I just want to make sure you've got the correct permissions.

Could someone with pre-existing GitHub experience reach out as a guinea pig for something else I'd like to check?

**Comment by weininghu1012** [comment]
Yeah, I have edit the README . Please have a look.
https://github.com/STAT545-UBC/weining_hu




Weining

**Comment by jennybc** [comment]
Thanks @weininghu1012. :tada: 

Note: that link will 404 most other people FWIW because these repos are private within the Organization and, at the moment, private to the specific student. In due course I will make your repos visible to each other, but I haven't done that yet.

**Comment by SarahQiong** [comment]
I think I complete the edit both from the browser and RStudio. So happy it works:)

**Comment by JoeyBernhardt** [comment]
I edited my README from Rstudio...so I think it worked!

**Comment by ahippman** [comment]
I can;t seem to find an invite yet. Can anybody let me know what the sender email is or the header so I can look for it more specifically. So far nothing (i.e. "Jennifer" or "STAT" or "Invitation" has led to any hits. Spam folder also empty. Any help appreciated. Does anybody else have the same problem (earlier there seemed to be more with no email invitation)?

**Comment by zhamel** [comment]
It should come from this "GitHub" <support@github.com> in your mailbox. 
Otherwise, if you go directly to your GitHub profil page, you would see the invite at the top of the page.. I think!

**Comment by jennybc** [comment]
@ahippman I never got any survey data from you :( which meant I didn't have your github username. Can you fill out the survey (again)?

**Comment by ahippman** [comment]
@jennybc I filled it out directly in class... hmmm, I filled it in again just now but somehow the submit button is not cooperating.... I will try a couple more times but will also write a real email with the info to you. Sorry about that!

**Comment by ahippman** [comment]
@jennybc Great, after I sent the email to you... this time it worked and I did get the same message as in class "Thank you, your response was submitted". Hope, one way or another, you will have all the info. Cross my fingers :)

**Comment by RashedHUBC** [comment]
Yeah. It is working. I edited README.md file from the RStudio as well as from the browser. My one is there.
https://github.com/STAT545-UBC/md-rashedul_hoque

**Comment by arunmarria** [comment]
@jennybc I am sorry to say despite the fact that I completed survey in class, I did not received an email invitation. Please let me know what can be done to access my repository?

**Comment by jennybc** [comment]
@arunmarria Yeah you're there in the survey data with the same github username you show here. Not sure what went wrong but I'm going to do a second wave today and will make sure you're in it.

**Comment by cathyxijuan** [comment]
@jennybc  Hi Jenny, I think I am successful at completing the hw. Here is my repository: https://github.com/STAT545-UBC/cathy_zhang.git
I am a question about the hw. It says that we should try to create a link to our course website. Is that supposed to be done in RMarkdown? If not, where should I go to create the link?

**Comment by ahippman** [comment]
@jennybc Finally! I made it! Funny thing with my RStudio. In order to be able to give RStudio the URL, I have to go:

    File > New Project > Version Control > Git > entering GIT URL, File Name etc > Create

If I go the route of

    File > New Project > Empty Project > entering File Name directory location etc and checking the box with "Create a Git repository", it will NOT ask me for an URL and I have no idea where I would enter it...probably through the shell. But when I tried it using the shell button provided in the Git tab within RStudio it didnt seem to work either... Will probably drop by office hours to clarify how I would go about going this route.. 

@zhamel Thanks for providing the email sender ID earlier!

**Comment by jennybc** [comment]
@ahippman 

You have the right workflow and it's the one laid out in [Claim your private STAT 545 repository](http://stat545-ubc.github.io/git08_claim-stat545-repo.html). Think of this as "GitHub first, then RStudio".

The other one you mention -- let's call it "RStudio first, then GitHub" -- is more clunky. But I do describe it in [Connect a local RStudio project to a GitHub repo](http://stat545-ubc.github.io/git07_git-github-rstudio.html#step-2-plan-b-connect-a-local-rstudio-project-to-a-github-repo) because it will inevitably be necessary at some point.

**Comment by jennybc** [comment]
@cathyxijuan 

I am just recommending you insert a link to the course webpage in your README. Use the Markdown syntax for creating a link:

     [STAT 545 webpage](http://stat545-ubc.github.io)

and you'll get a link like this: [STAT 545 webpage](http://stat545-ubc.github.io).

**Comment by jennybc** [comment]
@arunmarria

For the record, I never needed to add you or anything. Everything was set up properly in the first wave for your team/repo and I see you've managed to claim the repo. Not sure where the wires got crossed but I see all is well.

**Comment by arunmarria** [comment]
@jennybc Yaah! It's fine, I was able to submit the homework as well. Thanks.

**Comment by DimitriosK** [comment]
@jennybc
  I redid my survey this morning but wasn't able to see my invitation for the course repository yet. Any help would be appreciated.

**Comment by jennybc** [comment]
@DimitriosK 

We are not quite as automated as you think :grimacing:. Let me hit the "do all the stuff" again button again.

**Comment by jennybc** [comment]
@DimitriosK @BattaLiu

You two should be set up now. Check your email.

**Comment by jennybc** [comment]
I think we're done here.
